acmaesoptimizer.cpp
static ivec acmaes::inverse(const ivec &indices)
References acmaes::inverse.
Referenced by acmaes::inverse, acmaes::AcmaesOptimizer::updateCovariance.
static vec acmaes::sequence(double start, double end, double step)
Referenced by acmaes::AcmaesOptimizer::AcmaesOptimizer.
void optimizeACMA_C(long runid, callback_type func, callback_parallel func_par, int dim, double *init, double *lower, double *upper, double *sigma, int maxEvals, double stopfitness, double stopTolHistFun, int mu, int popsize, double accuracy, long seed, bool normalize, bool use_delayed_update, int update_gap, int workers, double *res)
References Fitness::setNormalize.
uintptr_t initACMA_C(long runid, int dim, double *init, double *lower, double *upper, double *sigma, int maxEvals, double stopfitness, double stopTolHistFun, int mu, int popsize, double accuracy, long seed, bool normalize, bool use_delayed_update, int update_gap)
References noop_callback, noop_callback_par, Fitness::setNormalize.
void destroyACMA_C(uintptr_t ptr)
void askACMA_C(uintptr_t ptr, double *xs)
References Fitness::decode.
int tellACMA_C(uintptr_t ptr, double *ys)
int tellXACMA_C(uintptr_t ptr, double *ys, double *xs)
References Fitness::encode.
int populationACMA_C(uintptr_t ptr, double *xs)
int resultACMA_C(uintptr_t ptr, double *res)
References Fitness::evaluations.
int testACMA_C(int n, double *res)