arm.py
examples::arm.stdout
examples::arm.format
examples::arm.level
int examples::arm.dim
examples.arm.forward_kinematics(q)
Calculates links positions given joint angles.
Parametersq numpy.ndarray (n_links,) array of angles in radians adapted from https://github.com/tsitsimis/planar-robot/blob/master/planarobot/planar_arm.py
Referenced by examples.arm.fitness.__call__.
examples.arm.plot3d(ys, name, xlabel='', ylabel='', zlabel='')
Referenced by examples.arm.plot_archive.
examples.arm.plot_archive(problem, archive=None)
References examples.arm.plot3d.
Referenced by examples.arm.optimize_qd.
examples.arm.optimize_qd(dim)
References examples.arm.plot_archive.