Fitness
callback_type Fitness::_func
Referenced by eval, eval, Fitness.
callback_parallel Fitness::_func_par
Referenced by Fitness, values.
int Fitness::_dim
Referenced by eval, eval, Fitness, sample, sample.
int Fitness::_nobj
Referenced by eval, eval, Fitness.
vec Fitness::_lower
Referenced by feasible, Fitness, getClosestFeasible, getClosestFeasible_i, getClosestFeasibleNormed, getMinValues, hasBounds, norm, norm_i, sample, sample_i, setClosestFeasible, violations.
vec Fitness::_upper
Referenced by feasible, Fitness, getClosestFeasible, getClosestFeasible_i, getClosestFeasibleNormed, getMaxValues, setClosestFeasible, violations.
vec Fitness::_scale
Referenced by decode, encode, norm, norm_i, sample, sample_i, scale.
vec Fitness::_typx
Referenced by decode, encode, typx.
bool Fitness::_normalize
Referenced by decode, encode, Fitness, getClosestFeasibleNormed, setClosestFeasible, setNormalize.
bool Fitness::_terminate
Referenced by eval, eval, Fitness, setTerminate, terminate.
long Fitness::_evaluationCounter
Referenced by eval, eval, evaluations, Fitness, incrEvaluations, resetEvaluations, values.
Fitness::Fitness(callback_type func, callback_parallel func_par_, int dim, int nobj, const vec &lower, const vec &upper)
References _dim, _evaluationCounter, _func, _func_par, _lower, _nobj, _normalize, _terminate, _upper.
bool Fitness::terminate()
References _terminate.
Referenced by optimizePGPE_C.
vec Fitness::eval(const vec &X)
References _dim, _evaluationCounter, _func, _nobj, _terminate.
vec Fitness::eval(const double *const p)
References _dim, _evaluationCounter, _func, _nobj, _terminate.
vec Fitness::getClosestFeasible(const vec &X) const
References _lower, _upper.
Referenced by askCRFMNES_C, values.
double Fitness::getClosestFeasible_i(int i, double x_i)
References _lower, _upper.
vec Fitness::getClosestFeasibleNormed(const vec &X) const
References _lower, _normalize, _upper.
void Fitness::setClosestFeasible(mat &X) const
References _lower, _normalize, _upper.
vec Fitness::norm(const vec &X) const
References _lower, _scale.
double Fitness::norm_i(int i, double x) const
References _lower, _scale.
bool Fitness::feasible(int i, double x)
References _lower, _upper.
bool Fitness::hasBounds()
References _lower.
vec Fitness::sample(pcg64 &rs)
References _dim, _lower, _scale, uniformVec.
vec Fitness::sample(pcg64 &rs, vec &up, vec &lo)
References _dim, uniformVec.
double Fitness::sample_i(int i, pcg64 &rs)
References _lower, _scale, distr_01.
double Fitness::sample_i(int i, pcg64 &rs, vec &up, vec &lo)
References distr_01.
int Fitness::evaluations()
References _evaluationCounter.
Referenced by optimizeBite_C, optimizeCRFMNES_C, optimizeDE_C, optimizePGPE_C, resultACMA_C, resultCRFMNES_C, resultDE_C, resultPGPE_C.
void Fitness::resetEvaluations()
References _evaluationCounter.
void Fitness::incrEvaluations()
References _evaluationCounter.
vec Fitness::scale()
References _scale.
vec Fitness::typx()
References _typx.
void Fitness::setNormalize(bool normalize)
References _normalize.
Referenced by initACMA_C, initCRFMNES_C, initPGPE_C, optimizeACMA_C, optimizeCRFMNES_C, optimizePGPE_C.
void Fitness::setTerminate()
References _terminate.
vec Fitness::encode(const vec &X) const
References _normalize, _scale, _typx.
Referenced by tellXACMA_C.
vec Fitness::decode(const vec &X) const
References _normalize, _scale, _typx.
Referenced by askACMA_C, askCRFMNES_C, values, violations.
void Fitness::values(const mat &popX, vec &ys)
References _evaluationCounter, _func_par, decode, getClosestFeasible.
Referenced by optimizePGPE_C.
vec Fitness::violations(const mat &X, double penalty_coef)
References _lower, _upper, decode, violations, zeros.
Referenced by violations.
void Fitness::getMinValues(double *const p) const
References _lower.
void Fitness::getMaxValues(double *const p) const
References _upper.