examples::trappist_delivery::trappist_schedule
examples.trappist_delivery.trappist_schedule::db
Referenced by examples.trappist_delivery.fitness.__call__, examples.trappist_delivery.trappist_schedule._fitness_impl, examples.trappist_delivery.fitness.convert, examples.trappist_delivery.trappist_schedule.example.
examples.trappist_delivery.trappist_schedule::n_stations
Referenced by examples.trappist_delivery.trappist_schedule._fitness_impl, examples.trappist_delivery.trappist_schedule._plot, examples.trappist_delivery.trappist_schedule.convert_to_chromosome, examples.trappist_delivery.trappist_schedule.example, examples.trappist_delivery.trappist_schedule.get_bounds.
examples.trappist_delivery.trappist_schedule::n_asteroids
Referenced by examples.trappist_delivery.trappist_schedule.convert_to_chromosome, examples.trappist_delivery.trappist_schedule.get_bounds, examples.trappist_delivery.trappist_schedule.get_nix.
examples.trappist_delivery.trappist_schedule::flat_db
Referenced by examples.trappist_delivery.trappist_schedule._fitness_impl.
examples.trappist_delivery.trappist_schedule::max_opportunities
Referenced by examples.trappist_delivery.trappist_schedule.get_bounds.
examples.trappist_delivery.trappist_schedule::start_time
Referenced by examples.trappist_delivery.trappist_schedule._fitness_impl, examples.trappist_delivery.trappist_schedule._plot, examples.trappist_delivery.trappist_schedule.get_bounds.
examples.trappist_delivery.trappist_schedule::end_time
Referenced by examples.trappist_delivery.trappist_schedule._fitness_impl, examples.trappist_delivery.trappist_schedule._plot, examples.trappist_delivery.trappist_schedule.get_bounds.
examples.trappist_delivery.trappist_schedule::station_gap
Referenced by examples.trappist_delivery.trappist_schedule._fitness_impl, examples.trappist_delivery.trappist_schedule.example.
examples.trappist_delivery.trappist_schedule::materials
examples.trappist_delivery.trappist_schedule.__init__(self, path=os.path.join(".", "trappist/candidates.txt"), n_stations=12, start_time=0.0, end_time=80.0, station_gap=1.0, materials=("Material A", "Material B", "Material C",))
examples.trappist_delivery.trappist_schedule.get_nobj(self)
There is only one objective for this challenge: to maximise the minimum amount of material collected per station.
Number of objectives.
examples.trappist_delivery.trappist_schedule.get_nix(self)
Each assignment consists of a pair of asteroid ID and station ID, hence the total number is 2 x the number of asteroids.
Number of integer components of the chromosome.
References examples.trappist_delivery.trappist_schedule.n_asteroids.
examples.trappist_delivery.trappist_schedule.get_nec(self)
There are two equality constraints (cf.
_fitness_impl() for details). Number of equality constraints.
examples.trappist_delivery.trappist_schedule.get_nic(self)
There are two equality constraints (cf.
_fitness_impl() for details). Number of inequality constraints.
examples.trappist_delivery.trappist_schedule.get_bounds(self)
Bounds for chromosome elements.
Bounds for each element in the chromosome.
References examples.trappist_delivery.trappist_schedule.end_time, examples.trappist_delivery.trappist_schedule.max_opportunities, examples.trappist_delivery.trappist_schedule.n_asteroids, examples.trappist_delivery.trappist_schedule.n_stations, examples.trappist_delivery.trappist_schedule.start_time.
examples.trappist_delivery.trappist_schedule.fitness(self, x)
A wrapper for the fitness function (called for evaluation only).
The chromosome has the following format: Start and end times for each station, in order of Station ID Asteroid / station assignments with the corresponding arrival times. Format[ Station 1 start time, Station 1 end time, | Station 2 start time, Station 2 end time, | Station 11 start time, Station 11 end time, | Station 12 start time, Station 12 end time, | Asteroid ID, Station ID, Opportunity ID, | Asteroid ID, Station ID, Opportunity ID, | Asteroid ID, Station ID, Opportunity ID, | Asteroid ID, Station ID, Opportunity ID | ] All IDs (for asteroids, stations and opportunities) are 1-based. This is particularly relevant for the opportunity IDs since they are converted to 0-based indices in the fitness evaluation function by subtracting 1. Stations must be activated sequentially (not in parallel) but not necessarily in order of their ID. There must be a minimal gap (called 'station gap') between the end time of one station and the start time of the next. Every asteroid must be either asigned to a station or unassigned. The asteroid / station assignments do not have to be in any particular order, but all asteroid IDs must appear in the chromosome, even if some asteroids are unassigned. - Assigned asteroids must have corresponding Station IDs between 1 and the number of stations. - Unassigned asteroids must have a Station ID 0. x A chromosome in the format specified above. A tuple containing the fitness followed by the equality and inequality constraints.
References examples.trappist_delivery.trappist_schedule._fitness_impl.
examples.trappist_delivery.trappist_schedule.pretty(self, x)
Fitness evaluation function with pretty printing.
x A chromosome.
References examples.trappist_delivery.trappist_schedule._fitness_impl.
examples.trappist_delivery.trappist_schedule.plot(self, x, ax=None, path=None)
Plot the total material masses accumulated at each station and the asteroid / station assignments.
x A chromosome. ax Plot axes. Defaults to None. path A file to save the plot to. Defaults to None. Plot axes.
References examples.trappist_delivery.trappist_schedule._fitness_impl.
examples.trappist_delivery.trappist_schedule.example(self)
An example method returning a minimal chromosome that assigns a single asteroid to each station.
A valid chromosome.
References examples.trappist_delivery.trappist_schedule.convert_to_chromosome, examples.trappist_delivery.trappist_schedule.db, examples.trappist_delivery.trappist_schedule.n_stations, examples.trappist_delivery.trappist_schedule.station_gap.
examples.trappist_delivery.trappist_schedule.convert_to_chromosome(self, x)
Creates a valid chromosome from an incomplete one.
Here, 'incomplete' means that all station windows are provided but only some asteroids are assigned. This method completes the chromosome by assigning the missing asteroids to station 0, which means that those asteroids will not be considered in the fitness evaluation. x Incomplete chromosome. Complete chromosome.
References examples.trappist_delivery.trappist_schedule.n_asteroids, examples.trappist_delivery.trappist_schedule.n_stations.
Referenced by examples.trappist_delivery.trappist_schedule.example.
examples.trappist_delivery.trappist_schedule._load(self, path)
Load the database from an external JSON file.
path The path to the database file The path to the database file.
examples.trappist_delivery.trappist_schedule._flatten(self, db)
Flatten the database.
db The database of possible asteroid / station assignment opportunities. A flat version of the database with (asteroid ID, station ID, opportunity ID) tuples as keys and (arrival time, mass A, mass B, mass C) tuples as values and the maximum number of opportunities for any asteroid / station pair in the database.
examples.trappist_delivery.trappist_schedule._plot(self, masses, schedule, ax=None, path=None)
Plot the total material masses at each station and the schedule vs.
opportunities for each station. masses A 2D array containing the masses corresponding to all assignment opportunities. schedule The actual scheduled asteroid / station assignments and their corresponding masses. ax Plot axes. Defaults to None. path A file to save the plot to. Defaults to None. Plot axes.
References examples.trappist_delivery.trappist_schedule.end_time, examples.trappist_delivery.trappist_schedule.n_stations, examples.trappist_delivery.trappist_schedule.start_time.
Referenced by examples.trappist_delivery.trappist_schedule._fitness_impl.
examples.trappist_delivery.trappist_schedule._fitness_impl(self, x, logging=False, plotting=False, ax=None, path=None)
Computes the constraints and the fitness of the provided chromosome.
1. Equality constraints: 1.1. Asteroid IDs: all asteroids in the database must be present in the chromosome. 1.2. Opportunity IDs: all opportunity IDs in the chromosome must correspond to opportunities in the database. 2. Inequality constraints: 2.1. Station gaps: all station gaps must be greater than a minimal time period (self.station_gap) 2.2. Arrival times: all asteroid arrival times must be between the start and end times of the corresponding station 3. Fitness: 3.1 Iterate over the chromosome and add the masses of the materials for all assigned asteroids with valid transfers 3.2 Find the minimum mass of each material per station. This is the final fitness. x A list of integers and floats in the following format: Station start and end times (2 x self.n_stations) The following items for all selected asteroids (3 x self.n_asteroids integers in total): Asteroid ID Station ID Opportunity ID The triplets do not have to be ordered by asteroid ID. logging Logging switch. Defaults to False. plotting Plotting switch. Defaults to False. ax Plot axes. Defaults to None. path File path for saving the plots. Defaults to None. A tuple containing: The fitness A list of equality constraints A list of inequality constraints Plot axes
References examples.trappist_delivery.trappist_schedule._plot, examples.trappist_delivery.trappist_schedule.db, examples.trappist_delivery.trappist_schedule.end_time, examples.trappist_delivery.trappist_schedule.flat_db, examples.trappist_delivery.trappist_schedule.n_stations, examples.trappist_delivery.trappist_schedule.start_time, examples.trappist_delivery.trappist_schedule.station_gap.
Referenced by examples.trappist_delivery.trappist_schedule.fitness, examples.trappist_delivery.trappist_schedule.plot, examples.trappist_delivery.trappist_schedule.pretty.