CBiteOptBase
const int CBiteOptBase< ptype >::MaxSelCount
that can be added to *this object (for static arrays).
The maximal number of selectors
double* CBiteOptBase< ptype >::MinValues
Minimal parameter values.
Referenced by CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::deleteBuffers, CBiteOptBase< ptype >::getRealValue, CBiteOptBase< ptype >::initBuffers, CBiteOptBase< ptype >::initCommonVars, CBiteOptBase< ptype >::updateDiffValues, CBiteOptBase< ptype >::wrapParamReal, CBiteOptBase< ptype >::~CBiteOptBase.
double* CBiteOptBase< ptype >::MaxValues
Maximal parameter values.
Referenced by CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::deleteBuffers, CBiteOptBase< ptype >::initBuffers, CBiteOptBase< ptype >::initCommonVars, CBiteOptBase< ptype >::updateDiffValues, CBiteOptBase< ptype >::wrapParamReal, CBiteOptBase< ptype >::~CBiteOptBase.
double* CBiteOptBase< ptype >::DiffValues
values.
Difference between maximal and minimal parameter
Referenced by CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::deleteBuffers, CBiteOptBase< ptype >::getRealValue, CBiteOptBase< ptype >::initBuffers, CBiteOptBase< ptype >::updateDiffValues, CBiteOptBase< ptype >::wrapParamReal, CBiteOptBase< ptype >::~CBiteOptBase.
double* CBiteOptBase< ptype >::DiffValuesI
Inverse DiffValues.
Referenced by CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::deleteBuffers, CBiteOptBase< ptype >::initBuffers, CBiteOptBase< ptype >::updateDiffValues, CBiteOptBase< ptype >::~CBiteOptBase.
double* CBiteOptBase< ptype >::BestValues
Best parameter vector.
Referenced by CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::deleteBuffers, CBiteOptBase< ptype >::getBestParams, CBiteOptBase< ptype >::initBuffers, CBiteOptBase< ptype >::updateBestCost, CBiteOptBase< ptype >::~CBiteOptBase.
double CBiteOptBase< ptype >::BestCost
Cost of the best parameter vector.
Referenced by CBiteOptBase< ptype >::getBestCost, CBiteOptBase< ptype >::initCommonVars, CBiteOptBase< ptype >::updateBestCost.
double* CBiteOptBase< ptype >::NewValues
Temporary new parameter buffer, with real values.
Referenced by CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::deleteBuffers, CBiteOptBase< ptype >::initBuffers, CBiteOptBase< ptype >::~CBiteOptBase.
int CBiteOptBase< ptype >::StallCount
The number of iterations without improvement.
Referenced by CBiteOptBase< ptype >::initCommonVars.
double CBiteOptBase< ptype >::HiBound
be used by the optimizer.
Higher cost bound, for StallCount estimation. May not
Referenced by CBiteOptBase< ptype >::initCommonVars.
double CBiteOptBase< ptype >::AvgCost
the optimizer.
Average cost in the latest batch. May not be used by
Referenced by CBiteOptBase< ptype >::initCommonVars.
CBiteSelBase* CBiteOptBase< ptype >::Sels[MaxSelCount][MaxSelCount]
indexed access in some cases.
Pointers to selector objects, for
Referenced by CBiteOptBase< ptype >::addSel, CBiteOptBase< ptype >::getSels, CBiteOptBase< ptype >::initCommonVars.
const char* CBiteOptBase< ptype >::SelNames[MaxSelCount][MaxSelCount]
Selector names.
Referenced by CBiteOptBase< ptype >::addSel, CBiteOptBase< ptype >::getSelNames.
int CBiteOptBase< ptype >::SelCount
The number of selectors in use.
Referenced by CBiteOptBase< ptype >::addSel, CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::getSelCount, CBiteOptBase< ptype >::initCommonVars.
CBiteSelBase* CBiteOptBase< ptype >::ApplySels[MaxApplySels][MaxApplySels]
select() function calls during the optimize() function call.
Selectors that were used in
Referenced by CBiteOptBase< ptype >::applySelsDecr, CBiteOptBase< ptype >::applySelsIncr, CBiteOptBase< ptype >::select.
int CBiteOptBase< ptype >::ApplySelsCount
optimize() function call.
The number of select() calls performed during the
Referenced by CBiteOptBase< ptype >::applySelsDecr, CBiteOptBase< ptype >::applySelsIncr, CBiteOptBase< ptype >::initCommonVars, CBiteOptBase< ptype >::select.
const int CBiteOptBase< ptype >::MaxApplySels
that can be used during a single optimize() function call.
The maximal number of selections
CBiteOptBase< ptype >::CBiteOptBase(const CBiteOptBase &)
References CBiteOptBase< ptype >::CBiteOptBase.
Referenced by CBiteOptBase< ptype >::CBiteOptBase, CBiteOptBase< ptype >::operator=.
CBiteOptBase & CBiteOptBase< ptype >::operator=(const CBiteOptBase &)
References CBiteOptBase< ptype >::CBiteOptBase.
CBiteOptBase< ptype >::CBiteOptBase()
References CBiteOptBase< ptype >::BestValues, CBiteOptBase< ptype >::DiffValues, CBiteOptBase< ptype >::DiffValuesI, CBiteOptBase< ptype >::MaxValues, CBiteOptBase< ptype >::MinValues, CBiteOptBase< ptype >::NewValues, CBiteOptBase< ptype >::SelCount.
virtual CBiteOptBase< ptype >::~CBiteOptBase()
References CBiteOptBase< ptype >::BestValues, CBiteOptBase< ptype >::DiffValues, CBiteOptBase< ptype >::DiffValuesI, CBiteOptBase< ptype >::MaxValues, CBiteOptBase< ptype >::MinValues, CBiteOptBase< ptype >::NewValues.
virtual const double * CBiteOptBase< ptype >::getBestParams() const
Best parameter vector.
References CBiteOptBase< ptype >::BestValues.
virtual double CBiteOptBase< ptype >::getBestCost() const
Cost of the best parameter vector.
References CBiteOptBase< ptype >::BestCost.
CBiteSelBase ** CBiteOptBase< ptype >::getSels()
Function returns a pointer to an array of selectors in use.
References CBiteOptBase< ptype >::Sels.
const char ** CBiteOptBase< ptype >::getSelNames() const
Function returns a pointer to an array of selector names.
References CBiteOptBase< ptype >::SelNames.
int CBiteOptBase< ptype >::getSelCount() const
Function returns the number of selectors in use.
References CBiteOptBase< ptype >::SelCount.
virtual void CBiteOptBase< ptype >::initBuffers(const int aParamCount, const int aPopSize, const int aCnsCount=0, const int aObjCount=1)
Function initializes all common buffers, and "PopSize" variables. This function should be called when population's dimensions were changed. This function calls the deleteBuffers() function to release any derived classes' allocated buffers. Allocates an additional vector for temporary use, which is at the same the last vector in the PopParams array. Derived classes should call this function of the base class. aParamCount New parameter count. aPopSize New population size. If <= 0, population buffers will not be allocated. aCnsCount New constraint value count. aObjCount New objective value count. If equals 0, a rank element will not be auto-added.
References CBiteOptBase< ptype >::BestValues, CBiteParPops< ptype >::CBiteParPops, CBiteOptBase< ptype >::DiffValues, CBiteOptBase< ptype >::DiffValuesI, CBiteOptBase< ptype >::MaxValues, CBiteOptBase< ptype >::MinValues, CBiteOptBase< ptype >::NewValues, CBitePop< ptype >::ParamCount.
virtual void CBiteOptBase< ptype >::deleteBuffers()
Function deletes buffers previously allocated via the initBuffers() function. Derived classes should call this function of the base class.
References CBiteOptBase< ptype >::BestValues, CBiteParPops< ptype >::CBiteParPops, CBiteOptBase< ptype >::DiffValues, CBiteOptBase< ptype >::DiffValuesI, CBiteOptBase< ptype >::MaxValues, CBiteOptBase< ptype >::MinValues, CBiteOptBase< ptype >::NewValues.
void CBiteOptBase< ptype >::initCommonVars(CBiteRnd &rnd)
Function initializes or resets common variables used by optimizers, to their default values, including value bounds, registered selectors, calls the resetCurPopPos() and updateDiffValues() functions. This function is usually called in the init() function of an optimizer.
References CBiteOptBase< ptype >::ApplySelsCount, CBiteOptBase< ptype >::AvgCost, CBiteOptBase< ptype >::BestCost, CBiteOptInterface::getMaxValues, CBiteOptInterface::getMinValues, CBiteOptBase< ptype >::HiBound, CBiteOptBase< ptype >::MaxValues, CBiteOptBase< ptype >::MinValues, CBitePop< ptype >::ParamCount, CBitePop< ptype >::resetCurPopPos, CBiteOptBase< ptype >::SelCount, CBiteOptBase< ptype >::Sels, CBiteOptBase< ptype >::StallCount, CBiteOptBase< ptype >::updateDiffValues.
void CBiteOptBase< ptype >::updateDiffValues()
Function updates values in the DiffValues array, based on values in the MinValues and MaxValues arrays.
References CBiteOptBase< ptype >::DiffValues, CBiteOptBase< ptype >::DiffValuesI, CBitePop< ptype >::IntMantMult, CBiteOptBase< ptype >::MaxValues, CBiteOptBase< ptype >::MinValues, CBitePop< ptype >::ParamCount.
Referenced by CBiteOptBase< ptype >::initCommonVars.
void CBiteOptBase< ptype >::updateBestCost(const double UpdCost, const double *const UpdValues, const int p=-1)
Function updates BestCost value and BestValues array, if the specified NewCost is better. UpdCost New solution's cost. UpdValues New solution's values. The values should be in the "real" value range. p New solution's position within population. If <0, position unknown, and the UpdCost should be evaluated.
References CBiteOptBase< ptype >::BestCost, CBiteOptBase< ptype >::BestValues, CBitePop< ptype >::copyValues.
double CBiteOptBase< ptype >::getRealValue(const ptype *const NormParams, const int i) const
Function returns specified parameter's value taking into account minimal and maximal value range. NormParams Parameter vector of interest, in normalized scale. i Parameter index.
References CBiteOptBase< ptype >::DiffValues, CBiteOptBase< ptype >::MinValues.
double CBiteOptBase< ptype >::wrapParamReal(CBiteRnd &rnd, const double v, const int i) const
Function wraps the specified parameter value so that it stays in the [MinValue; MaxValue] real range, by wrapping it over the boundaries using random operator. This operation improves convergence in comparison to clamping. v Parameter value to wrap. i Parameter index. Wrapped parameter value.
References CBiteOptBase< ptype >::DiffValues, CBiteRnd::get, CBiteOptBase< ptype >::MaxValues, CBiteOptBase< ptype >::MinValues.
void CBiteOptBase< ptype >::addSel(CBiteSelBase &s, const char *const sname)
Function adds a selector to the Sels list. s Selector object to add. sname Selector's name, should be a static constant.
References CBiteOptBase< ptype >::SelCount, CBiteOptBase< ptype >::SelNames, CBiteOptBase< ptype >::Sels.
int CBiteOptBase< ptype >::select(T &Sel, CBiteRnd &rnd)
Function performs choice selection based on the specified selector, and adds the selector to apply list. Sel Selector object. rnd PRNG object.
References CBiteOptBase< ptype >::ApplySels, CBiteOptBase< ptype >::ApplySelsCount.
void CBiteOptBase< ptype >::applySelsIncr(CBiteRnd &rnd, const double v=1.0)
Function applies selector increments on optimization success. rnd PRNG object. v Increment value, [0; 1].
References CBiteOptBase< ptype >::ApplySels, CBiteOptBase< ptype >::ApplySelsCount.
void CBiteOptBase< ptype >::applySelsDecr(CBiteRnd &rnd)
Function applies selector decrements on optimization fail. rnd PRNG object.
References CBiteOptBase< ptype >::ApplySels, CBiteOptBase< ptype >::ApplySelsCount.