crmfnes::CrfmnesOptimizer
int64_t crmfnes::CrfmnesOptimizer::runid
Referenced by CrfmnesOptimizer.
Fitness* crmfnes::CrfmnesOptimizer::fitfun
Referenced by CrfmnesOptimizer, doOptimize, getFitfun, tell.
int crmfnes::CrfmnesOptimizer::dim
Referenced by examples.damp.fitness.__call__, alpha_dist, ask, c1, CrfmnesOptimizer, eta_B, eta_conv_sigma, eta_stag_sigma, f, get_h_inv, getDim, anpcp.ANPCP.init_tsp, examples.siemens.Plant.next_product, examples.employee.problem.optimize, examples.employee.problem.optimize_mo, examples.damp.fitness.qd_fit, anpcp.ANPCP.random_x, anpcpc.ANPCPC.random_x, tell.
vec crmfnes::CrfmnesOptimizer::m
Referenced by ask, CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::sigma
Referenced by ask, CrfmnesOptimizer, tell.
int crmfnes::CrfmnesOptimizer::lamb
Referenced by alpha_dist, ask, c1, CrfmnesOptimizer, doOptimize, getPopsize, tell.
int crmfnes::CrfmnesOptimizer::mu
Referenced by examples.kepler.kepler.Kepler.__str__, examples.kepler.rvt.rvt.__str__, examples.kepler.rvt.rvt.apply_dv, ask, examples.kepler.kepler.Kepler.copy, examples.kepler.rvt.rvt.copy, CrfmnesOptimizer, examples.kepler.rvt.rvt.get_kepler, examples.kepler.rvt.rvt.kepler, examples.kepler.rvt.rvt.period, examples.kepler.rvt.rvt.plot, examples.kepler.kepler.Kepler.propagate_kepler, examples.kepler.rvt.rvt.propagate_lagrangian, examples.kepler.rvt.rvt.propagatetaylor, examples.kepler.rvt.rvt.rotate, examples.kepler.resonance.resonance.select_resonance.
bool crmfnes::CrfmnesOptimizer::use_constraint_violation
Referenced by CrfmnesOptimizer, tell.
pcg64* crmfnes::CrfmnesOptimizer::rs
Referenced by ask, CrfmnesOptimizer, ~CrfmnesOptimizer.
vec crmfnes::CrfmnesOptimizer::v
Referenced by examples.kepler.rvt.rvt.__str__, examples.kepler.rvt.rvt.apply_dv, ask, examples.kepler.rvt.rvt.copy, CrfmnesOptimizer, examples.kepler.rvt.rvt.kepler, examples.kepler.rvt.rvt.period, examples.kepler.rvt.rvt.plot, examples.kepler.rvt.rvt.propagate_lagrangian, examples.kepler.rvt.rvt.propagatetaylor, examples.kepler.rvt.rvt.rotate, tell.
vec crmfnes::CrfmnesOptimizer::D
Referenced by ask, CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::penalty_coef
Referenced by CrfmnesOptimizer, tell.
vec crmfnes::CrfmnesOptimizer::w_rank_hat
Referenced by CrfmnesOptimizer, tell.
vec crmfnes::CrfmnesOptimizer::w_rank
Referenced by CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::mueff
Referenced by CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::cs
Referenced by CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::cc
Referenced by CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::c1_cma
Referenced by c1, CrfmnesOptimizer.
double crmfnes::CrfmnesOptimizer::chiN
Referenced by CrfmnesOptimizer, tell.
vec crmfnes::CrfmnesOptimizer::pc
Referenced by CrfmnesOptimizer, tell.
vec crmfnes::CrfmnesOptimizer::ps
Referenced by CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::h_inv
Referenced by alpha_dist, CrfmnesOptimizer, get_h_inv.
double crmfnes::CrfmnesOptimizer::eta_m
Referenced by CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::eta_move_sigma
Referenced by CrfmnesOptimizer, tell.
double crmfnes::CrfmnesOptimizer::g
Referenced by fbcover.problem_fb.cost, CrfmnesOptimizer, edgecover.problem.fitness, tell.
int crmfnes::CrfmnesOptimizer::no_of_evals
Referenced by CrfmnesOptimizer, tell.
mat crmfnes::CrfmnesOptimizer::z
Referenced by ask, CrfmnesOptimizer, sort_indices_by, tell, w_dist_hat.
double crmfnes::CrfmnesOptimizer::f_best
Referenced by CrfmnesOptimizer, getBestValue, tell.
vec crmfnes::CrfmnesOptimizer::x_best
Referenced by CrfmnesOptimizer, getBestX, tell.
mat crmfnes::CrfmnesOptimizer::xs_no_sort
Referenced by getPopulation, tell.
vec crmfnes::CrfmnesOptimizer::evals_no_sort
Referenced by tell.
int crmfnes::CrfmnesOptimizer::iterations
Referenced by doOptimize, getIterations.
int crmfnes::CrfmnesOptimizer::maxEvaluations
Referenced by CrfmnesOptimizer, doOptimize.
double crmfnes::CrfmnesOptimizer::stopfitness
Referenced by CrfmnesOptimizer, tell.
int crmfnes::CrfmnesOptimizer::stop
Referenced by CrfmnesOptimizer, doOptimize, getStop, tell.
double crmfnes::CrfmnesOptimizer::normv
Referenced by ask, tell.
double crmfnes::CrfmnesOptimizer::normv2
Referenced by ask, tell.
vec crmfnes::CrfmnesOptimizer::vbar
Referenced by ask, tell.
mat crmfnes::CrfmnesOptimizer::y
Referenced by ask, examples.filter.filter.learn, tell.
mat crmfnes::CrfmnesOptimizer::x
Referenced by ask, examples.filter.filter.learn, tell.
crmfnes::CrfmnesOptimizer::CrfmnesOptimizer(int64_t runid_, Fitness *fitfun_, int dim_, vec m_, double sigma_, int lamb_, int maxEvaluations_, double stopfitness_, double penalty_coef_, bool use_constraint_violation_, int64_t seed)
References c1_cma, cc, chiN, constant, cs, D, dim, eta_m, eta_move_sigma, f_best, fitfun, g, get_h_inv, h_inv, lamb, m, maxEvaluations, mu, mueff, no_of_evals, normalVec, pc, penalty_coef, ps, rs, runid, crmfnes::sequence, sigma, stop, stopfitness, use_constraint_violation, v, w_rank, w_rank_hat, x_best, z, zeros.
virtual crmfnes::CrfmnesOptimizer::~CrfmnesOptimizer()
References rs.
void crmfnes::CrfmnesOptimizer::doOptimize()
References ask, fitfun, iterations, lamb, maxEvaluations, stop, tell.
mat crmfnes::CrfmnesOptimizer::getPopulation()
References xs_no_sort.
vec crmfnes::CrfmnesOptimizer::getBestX()
References x_best.
double crmfnes::CrfmnesOptimizer::getBestValue()
References f_best.
double crmfnes::CrfmnesOptimizer::getIterations()
References iterations.
int crmfnes::CrfmnesOptimizer::getStop()
References stop.
Fitness * crmfnes::CrfmnesOptimizer::getFitfun()
References fitfun.
int crmfnes::CrfmnesOptimizer::getDim()
References dim.
int crmfnes::CrfmnesOptimizer::getPopsize()
References lamb.
mat crmfnes::CrfmnesOptimizer::ask()
References D, dim, lamb, m, mu, normal, normv, normv2, rs, sigma, v, vbar, x, y, z.
Referenced by doOptimize.
void crmfnes::CrfmnesOptimizer::tell(vec &evs)
References c1, cc, cexp, chiN, constant, cs, D, dim, eta_B, eta_conv_sigma, eta_m, eta_move_sigma, eta_stag_sigma, evals_no_sort, f_best, fitfun, g, lamb, m, mueff, no_of_evals, normv, normv2, pc, penalty_coef, ps, sigma, sort_indices_by, stop, stopfitness, use_constraint_violation, v, vbar, w_dist_hat, w_rank, w_rank_hat, x, x_best, xs_no_sort, y, z, zeros.
Referenced by doOptimize.
double crmfnes::CrfmnesOptimizer::cexp(double a)
Referenced by f, f_prime, tell, w_dist_hat.
double crmfnes::CrfmnesOptimizer::c1(double lambF)
References c1_cma, dim, lamb.
Referenced by tell.
double crmfnes::CrfmnesOptimizer::eta_B(double lambF)
References dim.
Referenced by tell.
double crmfnes::CrfmnesOptimizer::alpha_dist(double lambF)
References dim, h_inv, lamb.
Referenced by w_dist_hat.
double crmfnes::CrfmnesOptimizer::w_dist_hat(mat z, double lambF)
References alpha_dist, cexp, z.
Referenced by tell.
double crmfnes::CrfmnesOptimizer::eta_stag_sigma(double lambF)
References dim.
Referenced by tell.
double crmfnes::CrfmnesOptimizer::eta_conv_sigma(double lambF)
References dim.
Referenced by tell.
double crmfnes::CrfmnesOptimizer::f(double a)
References cexp, dim.
Referenced by get_h_inv.
double crmfnes::CrfmnesOptimizer::f_prime(double a)
References cexp.
Referenced by get_h_inv.
double crmfnes::CrfmnesOptimizer::get_h_inv(int dim)
References dim, f, f_prime, h_inv.
Referenced by CrfmnesOptimizer.
int crmfnes::CrfmnesOptimizer::num_feasible(const vec &evals)
Referenced by sort_indices_by.
ivec crmfnes::CrfmnesOptimizer::sort_indices_by(const vec &evals, mat z)
References num_feasible, sort_index, z.
Referenced by tell.