fcmaes::evaluator::parallel
fcmaes.evaluator.parallel::evaluator
The evaluator instance responsible for managing.
Referenced by fcmaes.evaluator.parallel.__call__, fcmaes.evaluator.parallel_mo.__call__, fcmaes.evaluator.parallel.stop, fcmaes.evaluator.parallel_mo.stop.
fcmaes.evaluator.parallel.__init__(self, Callable[[ArrayLike], float] fun, Optional[int] workers=mp.cpu_count())
Initializes a new instance of the class.
fun (Callable[[ArrayLike], float]): A callable function that accepts an argument of type ArrayLike and returns a float. This function will be used as the evaluator. workers The number of worker processes to use. Defaults to the number of CPUs available on the machine.
np.ndarray fcmaes.evaluator.parallel.__call__(self, ArrayLike xs)
Evaluates the input using the provided evaluator function in parallel and returns the result.
xs Input data to be evaluated. np The result of the evaluation.
References fcmaes.evaluator.eval_parallel, fcmaes.evaluator.parallel.evaluator.
Referenced by hbv.hbv.qd_fitness, lrgv.lrgv.qd_fitness.
fcmaes.evaluator.parallel.stop(self)
Stops the evaluation process.
This method halts the ongoing evaluation process managed by the evaluator to prevent further execution or processing. RuntimeError If the evaluation process cannot be stopped.
References fcmaes.evaluator.parallel.evaluator, fcmaes.evaluator.parallel.stop.
Referenced by fcmaes.evaluator.parallel.stop.