acmaes::AcmaesOptimizer
mat acmaes::AcmaesOptimizer::popX
Referenced by getPopulation.
long acmaes::AcmaesOptimizer::runid
Referenced by AcmaesOptimizer.
Fitness* acmaes::AcmaesOptimizer::fitfun
Referenced by AcmaesOptimizer, ask, ask_all, do_optimize_delayed_update, doOptimize, getFitfun, getFitfunPar, getPopulation, tell, updateCMA.
vec acmaes::AcmaesOptimizer::guess
Referenced by AcmaesOptimizer.
double acmaes::AcmaesOptimizer::accuracy
Referenced by AcmaesOptimizer, updateCMA.
int acmaes::AcmaesOptimizer::popsize
Referenced by AcmaesOptimizer, ask_all, doOptimize, getPopsize, getPopulation, examples.benchmark_gtop_pygmo.Cma_pyg.minimize, examples.benchmark_gtop_pygmo.De_pyg.minimize, tell, tell_all, tell_all_asked, updateCMA.
vec acmaes::AcmaesOptimizer::inputSigma
Referenced by AcmaesOptimizer.
int acmaes::AcmaesOptimizer::dim
Referenced by examples.damp.fitness.__call__, AcmaesOptimizer, ask, ask_all, getDim, getPopulation, anpcp.ANPCP.init_tsp, examples.siemens.Plant.next_product, examples.employee.problem.optimize, examples.employee.problem.optimize_mo, examples.damp.fitness.qd_fit, anpcp.ANPCP.random_x, anpcpc.ANPCPC.random_x, tell, updateBD, updateCMA, updateCovariance, updateEvolutionPaths.
int acmaes::AcmaesOptimizer::maxEvaluations
Referenced by AcmaesOptimizer, do_optimize_delayed_update, doOptimize.
double acmaes::AcmaesOptimizer::stopfitness
Referenced by AcmaesOptimizer, updateCMA.
double acmaes::AcmaesOptimizer::stopTolUpX
Referenced by AcmaesOptimizer, updateCMA.
double acmaes::AcmaesOptimizer::stopTolX
Referenced by AcmaesOptimizer, updateCMA.
double acmaes::AcmaesOptimizer::stopTolFun
Referenced by AcmaesOptimizer, updateCMA.
double acmaes::AcmaesOptimizer::stopTolHistFun
Referenced by AcmaesOptimizer, updateCMA.
int acmaes::AcmaesOptimizer::mu
Referenced by examples.kepler.kepler.Kepler.__str__, examples.kepler.rvt.rvt.__str__, AcmaesOptimizer, examples.kepler.rvt.rvt.apply_dv, examples.kepler.kepler.Kepler.copy, examples.kepler.rvt.rvt.copy, examples.kepler.rvt.rvt.get_kepler, examples.kepler.rvt.rvt.kepler, examples.kepler.rvt.rvt.period, examples.kepler.rvt.rvt.plot, examples.kepler.kepler.Kepler.propagate_kepler, examples.kepler.rvt.rvt.propagate_lagrangian, examples.kepler.rvt.rvt.propagatetaylor, examples.kepler.rvt.rvt.rotate, examples.kepler.resonance.resonance.select_resonance, updateCMA, updateCovariance.
vec acmaes::AcmaesOptimizer::weights
Referenced by examples.harvesting.fitness.__call__, examples.jobshop.fitness.__call__, examples.trappist_delivery.fitness.__call__, AcmaesOptimizer, examples.harvesting.fitness.fun, examples.jobshop.fitness.fun, updateCMA, updateCovariance.
double acmaes::AcmaesOptimizer::mueff
Referenced by AcmaesOptimizer, updateCovariance, updateEvolutionPaths.
double acmaes::AcmaesOptimizer::sigma
Referenced by AcmaesOptimizer, ask, ask_all, tell, updateCMA, updateCovariance, updateEvolutionPaths.
double acmaes::AcmaesOptimizer::cc
Referenced by AcmaesOptimizer, updateCovariance, updateEvolutionPaths.
double acmaes::AcmaesOptimizer::cs
Referenced by AcmaesOptimizer, updateCMA, updateEvolutionPaths.
double acmaes::AcmaesOptimizer::damps
Referenced by AcmaesOptimizer, updateCMA.
double acmaes::AcmaesOptimizer::ccov1
Referenced by AcmaesOptimizer, updateBD, updateCovariance.
double acmaes::AcmaesOptimizer::ccovmu
Referenced by AcmaesOptimizer, updateBD, updateCovariance.
double acmaes::AcmaesOptimizer::chiN
Referenced by AcmaesOptimizer, updateCMA, updateEvolutionPaths.
double acmaes::AcmaesOptimizer::ccov1Sep
Referenced by AcmaesOptimizer.
double acmaes::AcmaesOptimizer::ccovmuSep
Referenced by AcmaesOptimizer.
double acmaes::AcmaesOptimizer::lazy_update_gap
Referenced by AcmaesOptimizer, updateCMA.
vec acmaes::AcmaesOptimizer::xmean
Referenced by AcmaesOptimizer, ask, ask_all, tell, updateCMA, updateEvolutionPaths.
vec acmaes::AcmaesOptimizer::pc
Referenced by AcmaesOptimizer, updateCMA, updateCovariance, updateEvolutionPaths.
vec acmaes::AcmaesOptimizer::ps
Referenced by AcmaesOptimizer, updateEvolutionPaths.
double acmaes::AcmaesOptimizer::normps
Referenced by AcmaesOptimizer, updateCMA, updateEvolutionPaths.
mat acmaes::AcmaesOptimizer::B
Referenced by AcmaesOptimizer, updateBD, updateEvolutionPaths.
mat acmaes::AcmaesOptimizer::BD
Referenced by AcmaesOptimizer, ask, ask_all, tell, updateBD, updateCovariance.
mat acmaes::AcmaesOptimizer::diagD
Referenced by AcmaesOptimizer, updateBD, updateCMA.
mat acmaes::AcmaesOptimizer::C
Referenced by AcmaesOptimizer, updateBD, updateCovariance.
vec acmaes::AcmaesOptimizer::diagC
Referenced by AcmaesOptimizer, updateBD, updateCMA.
mat acmaes::AcmaesOptimizer::arz
Referenced by ask_all, tell, updateCMA, updateCovariance.
mat acmaes::AcmaesOptimizer::arx
Referenced by AcmaesOptimizer, tell, updateCMA.
vec acmaes::AcmaesOptimizer::fitness
Referenced by AcmaesOptimizer, examples.employee.problem.optimize, quantumcomm.constellation_udp.pretty, tell, updateCMA.
int acmaes::AcmaesOptimizer::iterations
Referenced by AcmaesOptimizer, do_optimize_delayed_update, doOptimize, getIterations, tell, updateBD, updateCMA, updateEvolutionPaths.
int acmaes::AcmaesOptimizer::last_update
Referenced by updateCMA.
vec acmaes::AcmaesOptimizer::fitnessHistory
Referenced by AcmaesOptimizer, updateCMA.
int acmaes::AcmaesOptimizer::historySize
Referenced by AcmaesOptimizer.
double acmaes::AcmaesOptimizer::bestValue
Referenced by AcmaesOptimizer, getBestValue, updateCMA.
vec acmaes::AcmaesOptimizer::bestX
Referenced by AcmaesOptimizer, getBestX, examples.noisy_tsp.TSP.optimize_mo, updateCMA.
int acmaes::AcmaesOptimizer::stop
Referenced by AcmaesOptimizer, do_optimize_delayed_update, doOptimize, getStop, tell, tell_all, tell_all_asked, updateCMA.
int acmaes::AcmaesOptimizer::told
Referenced by doOptimize, tell, tell_all, tell_all_asked.
pcg64* acmaes::AcmaesOptimizer::rs
Referenced by AcmaesOptimizer, ask, ask_all, tell, ~AcmaesOptimizer.
bool acmaes::AcmaesOptimizer::computeArz
Referenced by AcmaesOptimizer, ask, ask_all, tell, tell_all, tell_all_asked.
acmaes::AcmaesOptimizer::AcmaesOptimizer(long runid_, Fitness *fitfun_, int popsize_, int mu_, const vec &guess_, const vec &inputSigma_, int maxEvaluations_, double accuracy_, double stopfitness_, double stopTolHistFun_, int update_gap_, long seed)
References accuracy, arx, B, BD, bestValue, bestX, C, cc, ccov1, ccov1Sep, ccovmu, ccovmuSep, chiN, computeArz, cs, damps, diagC, diagD, dim, fitfun, fitness, fitnessHistory, guess, historySize, inputSigma, iterations, lazy_update_gap, maxEvaluations, mu, mueff, normps, pc, popsize, ps, rs, runid, acmaes::sequence, sigma, stop, stopfitness, stopTolFun, stopTolHistFun, stopTolUpX, stopTolX, weights, xmean, zeros.
acmaes::AcmaesOptimizer::~AcmaesOptimizer()
References rs.
bool acmaes::AcmaesOptimizer::updateEvolutionPaths(const vec &zmean, const vec &xold)
References B, cc, chiN, cs, dim, iterations, mueff, normps, pc, ps, sigma, xmean.
Referenced by updateCMA.
double acmaes::AcmaesOptimizer::updateCovariance(bool hsig, const mat &bestArx, const mat &arz, const ivec &arindex, const mat &xold)
References arz, BD, C, cc, ccov1, ccovmu, dim, acmaes::inverse, mu, mueff, pc, sigma, sort_index, weights.
Referenced by updateCMA.
void acmaes::AcmaesOptimizer::updateBD(double negccov)
References B, BD, C, ccov1, ccovmu, diagC, diagD, dim, iterations.
Referenced by updateCMA.
mat acmaes::AcmaesOptimizer::ask_all()
References arz, BD, computeArz, dim, fitfun, normal, popsize, rs, sigma, xmean.
Referenced by doOptimize.
int acmaes::AcmaesOptimizer::tell_all(mat ys, mat xs)
References computeArz, popsize, stop, tell, told.
int acmaes::AcmaesOptimizer::tell_all_asked(mat ys, mat xs)
References computeArz, popsize, stop, tell, told.
mat acmaes::AcmaesOptimizer::getPopulation()
References dim, fitfun, popsize, popX.
vec acmaes::AcmaesOptimizer::ask()
References BD, computeArz, dim, fitfun, normalVec, rs, sigma, xmean.
Referenced by do_optimize_delayed_update.
int acmaes::AcmaesOptimizer::tell(double y, const vec &x)
References arx, arz, BD, computeArz, dim, fitfun, fitness, iterations, normal, popsize, rs, sigma, stop, told, updateCMA, xmean.
Referenced by do_optimize_delayed_update, doOptimize, tell_all, tell_all_asked.
void acmaes::AcmaesOptimizer::updateCMA()
References accuracy, arx, arz, bestValue, bestX, chiN, cs, damps, diagC, diagD, dim, fitfun, fitness, fitnessHistory, iterations, last_update, lazy_update_gap, mu, normps, pc, popsize, sigma, sort_index, stop, stopfitness, stopTolFun, stopTolHistFun, stopTolUpX, stopTolX, updateBD, updateCovariance, updateEvolutionPaths, weights, xmean.
Referenced by tell.
int acmaes::AcmaesOptimizer::doOptimize()
References ask_all, fitfun, iterations, maxEvaluations, popsize, stop, tell, told.
int acmaes::AcmaesOptimizer::do_optimize_delayed_update(int workers)
References vec_id::_id, vec_id::_v, ask, evaluator::evaluate, fitfun, iterations, maxEvaluations, evaluator::result, stop, tell.
vec acmaes::AcmaesOptimizer::getBestX()
References bestX.
double acmaes::AcmaesOptimizer::getBestValue()
References bestValue.
double acmaes::AcmaesOptimizer::getIterations()
References iterations.
int acmaes::AcmaesOptimizer::getStop()
References stop.
Fitness * acmaes::AcmaesOptimizer::getFitfun()
References fitfun.
int acmaes::AcmaesOptimizer::getDim()
References dim.
int acmaes::AcmaesOptimizer::getPopsize()
References popsize.
Fitness * acmaes::AcmaesOptimizer::getFitfunPar()
References fitfun.