CBiteOpt
typedef int64_t CBiteOpt::ptype
signed integer type, same as CBiteOptBase template parameter).
Parameter value storage type (should be a
CBiteSel< 4 > CBiteOpt::MethodSel
Population generator 4-method selector.
Referenced by CBiteOpt, optimize.
CBiteSel< 4 > CBiteOpt::M1Sel
Method 1's sub-method selector.
Referenced by CBiteOpt, optimize.
CBiteSel< 3 > CBiteOpt::M1ASel
Method 1's sub-sub-method A selector.
Referenced by CBiteOpt, optimize.
CBiteSel< 2 > CBiteOpt::M1BSel
Method 1's sub-sub-method B selector.
Referenced by CBiteOpt, optimize.
CBiteSel< 2 > CBiteOpt::M1CSel
Method 1's sub-sub-method C selector.
Referenced by CBiteOpt, optimize.
CBiteSel< 2 > CBiteOpt::M2Sel
Method 2's sub-method selector.
Referenced by CBiteOpt, optimize.
CBiteSel< 4 > CBiteOpt::M2BSel
Method 2's sub-sub-method B selector.
Referenced by CBiteOpt, optimize.
CBiteSel< 2 > CBiteOpt::PopChangeIncrSel
selector.
Population size change increase
Referenced by CBiteOpt, optimize.
CBiteSel< 2 > CBiteOpt::PopChangeDecrSel
selector.
Population size change decrease
Referenced by CBiteOpt, optimize.
CBiteSel< 2 > CBiteOpt::ParOpt2Sel
Parallel optimizer 2 use selector.
Referenced by CBiteOpt, generateSolPar.
CBiteSel< 2 > CBiteOpt::ParPopPSel[4][4]
probability selectors.
Parallel population use
Referenced by CBiteOpt, selectParPop.
CBiteSel< 2 > CBiteOpt::AltPopPSel
Alternative population use selector.
Referenced by CBiteOpt, selectAltPop.
CBiteSel< 2 > CBiteOpt::AltPopSel[4][4]
selectors.
Alternative population type use
Referenced by CBiteOpt, selectAltPop.
CBiteSel< 4 > CBiteOpt::MinSolPwrSel[4][4]
least-cost population index selection.
Power factor selectors, for
Referenced by CBiteOpt, getMinSolIndex.
CBiteSel< 4 > CBiteOpt::MinSolMulSel[4][4]
least-cost population index selection.
Multiplier selectors, for
Referenced by CBiteOpt, getMinSolIndex.
CBiteSel< 2 > CBiteOpt::Gen1AllpSel
Generator method 1's Allp selector.
Referenced by CBiteOpt, generateSol1.
CBiteSel< 2 > CBiteOpt::Gen1MoveAsyncSel
selector.
Generator method 1's Move async
Referenced by CBiteOpt, generateSol1.
CBiteSel< 4 > CBiteOpt::Gen1MoveSpanSel
selector.
Generator method 1's Move span
Referenced by CBiteOpt, generateSol1.
CBiteSel< 2 > CBiteOpt::Gen2ModeSel
Generator method 2's Mode selector.
Referenced by CBiteOpt, generateSol2.
CBiteSel< 2 > CBiteOpt::Gen2bModeSel
Generator method 2b's Mode selector.
Referenced by CBiteOpt, generateSol2b.
CBiteSel< 2 > CBiteOpt::Gen2cModeSel
Generator method 2c's Mode selector.
Referenced by CBiteOpt, generateSol2c.
CBiteSel< 2 > CBiteOpt::Gen2dModeSel
Generator method 2d's Mode selector.
Referenced by CBiteOpt, generateSol2d.
CBiteSel< 4 > CBiteOpt::Gen3ModeSel
Generator method 3's Mode selector.
Referenced by CBiteOpt, generateSol3.
CBiteSel< 4 > CBiteOpt::Gen4MixFacSel
selector.
Generator method 4's mixing count
Referenced by CBiteOpt, generateSol4.
CBiteSel< 2 > CBiteOpt::Gen5bModeSel
Generator method 5b's Mode selector.
Referenced by CBiteOpt, generateSol5b.
CBiteSel< 4 > CBiteOpt::Gen7PowFacSel
Generator method 7's Power selector.
Referenced by CBiteOpt, generateSol7.
CBiteSel< 2 > CBiteOpt::Gen8ModeSel
Generator method 8's mode selector.
Referenced by CBiteOpt, generateSol8.
CBiteSel< 4 > CBiteOpt::Gen8NumSel
Generator method 8's NumSols selector.
Referenced by CBiteOpt, generateSol8.
CBiteSel< 4 > CBiteOpt::Gen8SpanSel[2][2]
selectors.
Generator method 8's random span
Referenced by CBiteOpt, generateSol8.
CBitePop CBiteOpt::OldPop
probabilistically.
Population of older solutions, updated
Referenced by generateSol2d, generateSol7, init, optimize, updateDims.
bool CBiteOpt::DoInitEvals
"True" if initial evaluations should be performed.
Referenced by init, optimize.
bool CBiteOpt::DoEval
Temporary variable which equals to "true" if the newly-generated solution should be evaluated via the optcost() function.
Referenced by generateSolPar, optimize.
double CBiteOpt::NewCost
value (cost).
Temporary variable that receives objective function's
Referenced by generateSolPar, optimize.
CParOpt< CSpherOpt > CBiteOpt::ParOpt
Parallel optimizer.
Referenced by generateSolPar, init, updateDims.
CBitePop CBiteOpt::ParOptPop
Includes only its solutions.
Population of parallel optimizer's solutions.
Referenced by generateSolPar, init, selectAltPop, updateDims.
CParOpt< CNMSeqOpt > CBiteOpt::ParOpt2
Parallel optimizer2.
Referenced by generateSolPar, init, updateDims.
CBitePop CBiteOpt::ParOpt2Pop
Includes only its solutions.
Population of parallel optimizer 2's solutions.
Referenced by generateSolPar, init, selectAltPop, updateDims.
int CBiteOpt::UseParOpt
Parallel optimizer currently being in use.
Referenced by generateSolPar, init.
CBiteOpt::CBiteOpt()
References CBiteOptBase< int64_t >::addSel, AltPopPSel, AltPopSel, Gen1AllpSel, Gen1MoveAsyncSel, Gen1MoveSpanSel, Gen2bModeSel, Gen2cModeSel, Gen2dModeSel, Gen2ModeSel, Gen3ModeSel, Gen4MixFacSel, Gen5bModeSel, Gen7PowFacSel, Gen8ModeSel, Gen8NumSel, Gen8SpanSel, M1ASel, M1BSel, M1CSel, M1Sel, M2BSel, M2Sel, MethodSel, MinSolMulSel, MinSolPwrSel, ParOpt2Sel, ParPopPSel, PopChangeDecrSel, PopChangeIncrSel, CBiteParPops< int64_t >::setParPopCount.
Referenced by optimize.
void CBiteOpt::updateDims(const int aParamCount, const int PopSize0=0)
Function updates dimensionality of *this object. Function does nothing if dimensionality has not changed since the last call. This function should be called at least once before calling the init() function. aParamCount The number of parameters being optimized. PopSize0 The number of elements in population to use. If set to 0 or negative, the default formula will be used.
References CBiteOptBase< int64_t >::initBuffers, OldPop, CBitePop< int64_t >::ParamCount, ParOpt, ParOpt2, ParOpt2Pop, ParOptPop, CBitePop< int64_t >::PopSize.
void CBiteOpt::init(CBiteRnd &rnd, const double *const InitParams=NULL, const double InitRadius=1.0)
Function initializes *this optimizer. Does not perform objective function evaluations. rnd Random number generator. InitParams If not NULL, initial parameter vector, also used as centroid for initial population vectors. InitRadius Initial radius, multiplier relative to the default sigma value.
References CBiteOptBase< int64_t >::DiffValues, DoInitEvals, CBitePop< int64_t >::getGaussianInt, CBiteOptBase< int64_t >::initCommonVars, CBitePop< int64_t >::IntMantMult, CBiteOptBase< int64_t >::MinValues, OldPop, CBitePop< int64_t >::ParamCount, ParOpt, ParOpt2, ParOpt2Pop, ParOptPop, CBitePop< int64_t >::PopParams, CBitePop< int64_t >::PopSize, UseParOpt, CBitePop< int64_t >::wrapParam.
int CBiteOpt::optimize(CBiteRnd &rnd, CBiteOpt *const PushOpt=NULL)
Function performs the parameter optimization iteration that involves 1 objective function evaluation. rnd Random number generator. PushOpt Optimizer where the recently obtained solution should be "pushed", used for deep optimization algorithm. The number of non-improving iterations so far. A high value means optimizer has reached an optimization plateau. The suggested threshold value is ParamCount * 128. When this value was reached, the probability of plateau is high. This value, however, should not be solely relied upon when considering a stopping criteria: a hard iteration limit should be always used as in some cases convergence time may be very high with small, but frequent improving steps. This value is best used to allocate iteration budget between optimization attempts more efficiently.
References CBiteOptBase< int64_t >::applySelsDecr, CBiteOptBase< int64_t >::applySelsIncr, CBiteOpt, CBitePop< int64_t >::copy, CBitePop< int64_t >::CurPopPos, CBitePop< int64_t >::CurPopSize, CBitePop< int64_t >::CurPopSize1, CBitePop< int64_t >::CurPopSizeI, CBitePop< int64_t >::decrCurPopSize, DoEval, DoInitEvals, generateSol1, generateSol10, generateSol2, generateSol2b, generateSol2c, generateSol2d, generateSol3, generateSol4, generateSol5, generateSol5b, generateSol6, generateSol7, generateSol8, generateSol9, generateSolPar, CBiteRnd::get, CBitePop< int64_t >::getCurParams, CBitePop< int64_t >::getObjPtr, CBiteOptBase< int64_t >::getRealValue, CBitePop< int64_t >::incrCurPopSize, M1ASel, M1BSel, M1CSel, M1Sel, M2BSel, M2Sel, MethodSel, NewCost, CBiteOptBase< int64_t >::NewValues, OldPop, CBiteOptInterface::optcost, CBitePop< int64_t >::ParamCount, CBitePop< int64_t >::ParamCountI, CBiteParPops< int64_t >::ParPopCount, CBiteParPops< int64_t >::ParPops, PopChangeDecrSel, PopChangeIncrSel, CBitePop< int64_t >::PopParams, CBitePop< int64_t >::PopSize, CBiteOptBase< int64_t >::select, CBiteOptBase< int64_t >::StallCount, CBitePop< int64_t >::TmpParams, CBiteOptBase< int64_t >::updateBestCost, CBitePop< int64_t >::updateCentroid, updateParPop, CBitePop< int64_t >::updatePop, CBitePop< int64_t >::wrapParam.
void CBiteOpt::updateParPop(const double UpdCost, const ptype *const UpdParams)
Function updates an appropriate parallel population. UpdCost Cost of the new solution. UpdParams New parameter values.
References CBiteParPops< int64_t >::getMinDistParPop, CBiteParPops< int64_t >::ParPops, CBitePop< int64_t >::updatePop.
Referenced by optimize.
CBitePop & CBiteOpt::selectParPop(const int gi, CBiteRnd &rnd)
Function selects a parallel population to use for solution generation. With certain probability, *this object's own population will be returned instead of parallel population. gi Solution generator index (0-3). rnd PRNG object.
References CBitePop< int64_t >::CBitePop, CBiteRnd::getInt, CBiteParPops< int64_t >::ParPopCount, ParPopPSel, CBiteParPops< int64_t >::ParPops, CBiteOptBase< int64_t >::select.
Referenced by generateSol1, generateSol4, generateSol5, generateSol5b.
CBitePop & CBiteOpt::selectAltPop(const int gi, CBiteRnd &rnd)
Function selects an alternative, parallel optimizer's, population, to use in some solution generators. gi Solution generator index (0-3). rnd PRNG object.
References AltPopPSel, AltPopSel, CBitePop< int64_t >::CBitePop, CBitePop< int64_t >::CurPopSize, ParOpt2Pop, ParOptPop, CBiteOptBase< int64_t >::select.
Referenced by generateSol2b, generateSol4, generateSol5, generateSol5b.
int CBiteOpt::getMinSolIndex(const int gi, CBiteRnd &rnd, const int ps)
Function returns a dynamically-selected minimal population index, used in some solution generation methods. gi Solution generator index (0-3). rnd PRNG object. ps Population size.
References CBiteRnd::getPow, MinSolMulSel, MinSolPwrSel, CBiteOptBase< int64_t >::select.
Referenced by generateSol1, generateSol2, generateSol2b, generateSol3.
void CBiteOpt::generateSol1(CBiteRnd &rnd)
The original "bitmask inversion with random move" solution generator. Most of the time adjusts only a single parameter of a better solution, yet manages to produce excellent "reference points".
References CBitePop< int64_t >::CBitePop, CBitePop< int64_t >::copyParams, CBitePop< int64_t >::CurPopSize, Gen1AllpSel, Gen1MoveAsyncSel, Gen1MoveSpanSel, CBiteRnd::get, CBitePop< ptype >::getCurPopSize, CBiteRnd::getInt, getMinSolIndex, CBitePop< ptype >::getParamsOrdered, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBiteRnd::getTPDF, CBitePop< int64_t >::IntMantMask, CBitePop< int64_t >::ParamCount, CBitePop< int64_t >::ParamCountI, CBiteOptBase< int64_t >::select, selectParPop, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol2(CBiteRnd &rnd)
The "Differential Evolution"-based solution generator. Note that compared to a usual DE, this generator does not use crossover, and it uses one, or an average of two best solutions as the base.
References CBitePop< int64_t >::CurPopSize, CBitePop< int64_t >::CurPopSize1, Gen2ModeSel, CBiteRnd::getInt, getMinSolIndex, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol2b(CBiteRnd &rnd)
An alternative "Differential Evolution"-based solution generator.
References CBitePop< int64_t >::CBitePop, CBitePop< int64_t >::CurPopSize, CBitePop< int64_t >::CurPopSize1, Gen2bModeSel, CBiteRnd::getInt, getMinSolIndex, CBitePop< ptype >::getParamsOrdered, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, selectAltPop, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol2c(CBiteRnd &rnd)
"Differential Evolution"-based solution generator, almost an exact replica of the CDEOpt optimizer.
References CBitePop< int64_t >::CurPopSize, CBitePop< int64_t >::CurPopSize1, Gen2cModeSel, CBiteRnd::getBit, CBiteRnd::getInt, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getPowInt, CBiteRnd::getRaw, CBitePop< int64_t >::IntMantMask, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, CBitePop< int64_t >::TmpParams, CBitePop< int64_t >::zeroParams.
Referenced by generateSol2d, optimize.
void CBiteOpt::generateSol2d(CBiteRnd &rnd)
An alternative "Differential Evolution"-based solution generator that uses "OldPop" population.
References CBitePop< int64_t >::CurPopSize, Gen2dModeSel, generateSol2c, CBiteRnd::getInt, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, OldPop, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol3(CBiteRnd &rnd)
"Centroid mix with DE" solution generator, works well for convex functions. For DE operation, uses a better solution and a random previous solution.
References CBitePop< int64_t >::CurPopSize, Gen3ModeSel, CBiteRnd::get, CBitePop< int64_t >::getCentroid, getMinSolIndex, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol4(CBiteRnd &rnd)
"Entropy bit mixing"-based solution generator. Performs crossing-over of an odd number (this is important) of random solutions via XOR operation. Slightly less effective than the DE-based mixing, but makes the optimization method more diverse overall.
References CBitePop< int64_t >::CBitePop, CBitePop< int64_t >::copyParams, CBitePop< int64_t >::CurPopSize, Gen4MixFacSel, CBiteRnd::getBit, CBitePop< int64_t >::getCurPopSize, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, selectAltPop, selectParPop, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol5(CBiteRnd &rnd)
A novel "Randomized bit crossing-over" candidate solution generation method. Effective, but on its own cannot stand coordinate system offsets, converges slowly. Completely mixes bits of two randomly-selected solutions, plus changes 1 random bit. This method is similar to a biological DNA crossing-over, but on a single-bit scale.
References CBitePop< int64_t >::CBitePop, CBitePop< int64_t >::CurPopSize, CBiteRnd::getBit, CBitePop< ptype >::getCurPopSize, CBiteRnd::getInt, CBitePop< ptype >::getParamsOrdered, CBiteRnd::getRaw, CBiteRnd::getSqrInt, CBitePop< int64_t >::IntMantBits, CBitePop< int64_t >::IntMantMask, CBitePop< int64_t >::ParamCount, selectAltPop, selectParPop, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol5b(CBiteRnd &rnd)
"Randomized parameter cross-over" solution generator. Similar to the "randomized bit cross-over", but works with the whole parameter values.
References CBitePop< int64_t >::CBitePop, CBitePop< int64_t >::CurPopSize, CBitePop< int64_t >::CurPopSize1, Gen5bModeSel, CBiteRnd::getBit, CBitePop< ptype >::getCurPopSize, CBitePop< ptype >::getParamsOrdered, CBiteRnd::getSqrInt, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, selectAltPop, selectParPop, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol6(CBiteRnd &rnd)
A short-cut solution generator. Parameter value short-cuts: they considerably reduce convergence time for some functions while not severely impacting performance for other functions. Can use variation with randomization between two values, and a slight move towards real 0.
References CBitePop< int64_t >::CurPopSize, CBiteOptBase< int64_t >::DiffValuesI, CBiteRnd::getBit, CBiteRnd::getInt, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getPow, CBiteOptBase< int64_t >::getRealValue, CBiteOptBase< int64_t >::MinValues, CBitePop< int64_t >::ParamCount, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol7(CBiteRnd &rnd)
A solution generator that randomly combines solutions from the main and "old" populations. Conceptually, it can be called a weighted-random crossover that combines solutions from diverse sources.
References CBitePop< int64_t >::CurPopSize, Gen7PowFacSel, CBiteRnd::getBit, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getPow, OldPop, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol8(CBiteRnd &rnd)
Solution generator that is DE-alike in its base. It calculates a centroid of a number of best solutions, and then applies "mutation" operation between the centroid and the solutions, using a random multiplier. This generator is similar to the "move" operation of generator 1.
References CBitePop< int64_t >::copyParams, CBitePop< int64_t >::CurPopSize, Gen8ModeSel, Gen8NumSel, Gen8SpanSel, CBiteRnd::getGaussian, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBiteOptBase< int64_t >::NewValues, CBitePop< int64_t >::ParamCount, CBiteOptBase< int64_t >::select, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol9(CBiteRnd &rnd)
A "water drain" solution generator: makes a fixed-multiplier step from a better random solution 1 towards or away from worse random solution Moderately efficient on its own.
References CBitePop< int64_t >::CurPopSize, CBitePop< int64_t >::CurPopSize1, CBiteRnd::getBit, CBiteRnd::getInt, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBitePop< int64_t >::ParamCount, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSol10(CBiteRnd &rnd)
Solution generator based on SpherOpt's converging hyper-spheroid.
References CBitePop< int64_t >::CurPopSize, CBitePop< int64_t >::CurPopSize1, CBiteRnd::get, CBitePop< int64_t >::getParamsOrdered, CBiteRnd::getSqrInt, CBiteOptBase< int64_t >::NewValues, CBitePop< int64_t >::ParamCount, CBitePop< int64_t >::TmpParams.
Referenced by optimize.
void CBiteOpt::generateSolPar(CBiteRnd &rnd)
Solution generator that obtains solution from an independently-running parallel optimizer.
References CBitePop< int64_t >::CBitePop, CBiteOptBase< int64_t >::DiffValuesI, DoEval, CBiteOptBase< int64_t >::getBestParams, CBiteOptBase< int64_t >::MinValues, NewCost, CBiteOptBase< int64_t >::NewValues, CBitePop< int64_t >::ParamCount, ParOpt, ParOpt2, ParOpt2Pop, ParOpt2Sel, ParOptPop, CBiteOptBase< int64_t >::select, CBitePop< int64_t >::TmpParams, CBitePop< int64_t >::updatePop, UseParOpt.
Referenced by optimize.