CBiteOptInterface
CBiteOptInterface::CBiteOptInterface()
virtual CBiteOptInterface::~CBiteOptInterface()
virtual const double * CBiteOptInterface::getBestParams() const =0
Best parameter vector.
virtual double CBiteOptInterface::getBestCost() const =0
Cost of the best parameter vector.
virtual void CBiteOptInterface::getMinValues(double *const p) const =0
Virtual function that should fill minimal parameter value vector. p Minimal value vector.
Referenced by CBiteOptBase< ptype >::initCommonVars.
virtual void CBiteOptInterface::getMaxValues(double *const p) const =0
Virtual function that should fill maximal parameter value vector. p Maximal value vector.
Referenced by CBiteOptBase< ptype >::initCommonVars.
virtual double CBiteOptInterface::optcost(const double *const p)=0
Virtual function (objective function) that should calculate parameter vector's optimization cost. p Parameter vector to evaluate. Optimized cost.
Referenced by CNMSeqOpt::eval, CBiteOpt::optimize, CDEOpt::optimize, CSMAESOpt::optimize, CSpherOpt::optimize.