CBiteOptDeep
int CBiteOptDeep::ParamCount
The total number of internal parameter values in use.
Referenced by CBiteOptDeep, updateDims.
int CBiteOptDeep::OptCount
The total number of optimization objects in use.
Referenced by CBiteOptDeep, deleteBuffers, init, optimize, updateDims.
CBiteOptWrap** CBiteOptDeep::Opts
Optimization objects.
Referenced by CBiteOptDeep, deleteBuffers, init, optimize, updateDims.
CBiteOptWrap* CBiteOptDeep::BestOpt
Optimizer that contains the best solution.
Referenced by getBestCost, getBestParams, init, optimize.
CBiteOptWrap* CBiteOptDeep::CurOpt
Current optimizer object.
Referenced by getSelCount, getSelNames, getSels, init, optimize.
int CBiteOptDeep::StallCount
The number of iterations without improvement.
Referenced by init, optimize.
CBiteOptDeep::CBiteOptDeep()
References OptCount, Opts, ParamCount.
Referenced by CBiteOptDeep::CBiteOptWrap::CBiteOptWrap.
virtual CBiteOptDeep::~CBiteOptDeep()
References deleteBuffers.
virtual const double * CBiteOptDeep::getBestParams() const
Best parameter vector.
References BestOpt, getBestParams.
Referenced by getBestParams, biteopt::BiteOptimizer::getBestX.
virtual double CBiteOptDeep::getBestCost() const
Cost of the best parameter vector.
References BestOpt, getBestCost.
Referenced by biteopt::BiteOptimizer::doOptimize, getBestCost, biteopt::BiteOptimizer::getBestValue, optimize.
CBiteSelBase ** CBiteOptDeep::getSels()
Function returns a pointer to an array of selectors in use by the current CBiteOpt object.
References CurOpt, getSels.
Referenced by getSels.
const char ** CBiteOptDeep::getSelNames() const
Function returns a pointer to an array of selector names.
References CurOpt, getSelNames.
Referenced by getSelNames.
int CBiteOptDeep::getSelCount() const
Function returns the number of selectors in use by the current CBiteOpt object.
References CurOpt, getSelCount.
Referenced by getSelCount.
void CBiteOptDeep::updateDims(const int aParamCount, const int M=6, const int PopSize0=0)
Function updates dimensionality of *this object. Function does nothing if dimensionality has not changed since the last call. This function should be called at least once before calling the init() function. aParamCount The number of parameters being optimized. M The number of CBiteOpt objects. This number depends on the complexity of the objective function, if the default value does not produce a good solution, it should be increased together with the iteration count. Minimal value is 1, in this case a plain CBiteOpt optimization will be performed. PopSize0 The number of elements in population to use. If set to 0, the default formula will be used.
References deleteBuffers, OptCount, Opts, ParamCount, updateDims.
Referenced by biteopt::BiteOptimizer::BiteOptimizer, updateDims.
void CBiteOptDeep::init(CBiteRnd &rnd, const double *const InitParams=NULL, const double InitRadius=1.0)
Function initializes *this optimizer. Performs N=PopSize objective function evaluations. rnd Random number generator. InitParams Initial parameter values. InitRadius Initial radius, relative to the default value.
References BestOpt, CurOpt, init, OptCount, Opts, StallCount.
Referenced by biteopt::BiteOptimizer::BiteOptimizer, init.
int CBiteOptDeep::optimize(CBiteRnd &rnd)
Function performs the parameter optimization iteration that involves 1 objective function evaluation. rnd Random number generator. The number of non-improving iterations so far. The plateau threshold value is ParamCount * 64.
References BestOpt, CurOpt, getBestCost, CBiteRnd::getInt, OptCount, optimize, Opts, StallCount.
Referenced by biteopt::BiteOptimizer::doOptimize, optimize.
void CBiteOptDeep::deleteBuffers()
Function deletes previously allocated buffers.
References OptCount, Opts.
Referenced by updateDims, ~CBiteOptDeep.