CBiteOpt::CParOpt
CBiteOpt* CBiteOpt::CParOpt< T >::Owner
Owner object.
Referenced by CBiteOpt::CParOpt< T >::getMaxValues, CBiteOpt::CParOpt< T >::getMinValues, CBiteOpt::CParOpt< T >::optcost.
virtual void CBiteOpt::CParOpt< T >::getMinValues(double *const p) const
References CBiteOpt::CParOpt< T >::getMinValues, CBiteOpt::CParOpt< T >::Owner.
Referenced by CBiteOpt::CParOpt< T >::getMinValues.
virtual void CBiteOpt::CParOpt< T >::getMaxValues(double *const p) const
References CBiteOpt::CParOpt< T >::getMaxValues, CBiteOpt::CParOpt< T >::Owner.
Referenced by CBiteOpt::CParOpt< T >::getMaxValues.
virtual double CBiteOpt::CParOpt< T >::optcost(const double *const p)
References CBiteOpt::CParOpt< T >::optcost, CBiteOpt::CParOpt< T >::Owner.
Referenced by CBiteOpt::CParOpt< T >::optcost.