CBiteRnd
biteopt_rng CBiteRnd::rf
the default PRNG.
External random number generator to use; NULL: use
Referenced by advance, init.
void* CBiteRnd::rdata
Data pointer to pass to the "rf" function.
Referenced by advance, init.
uint64_t CBiteRnd::Seed
Referenced by advance, init.
uint64_t CBiteRnd::lcg
Referenced by advance, init.
uint64_t CBiteRnd::Hash
PRNG state variables.
Referenced by advance, init.
uint64_t CBiteRnd::BitPool
Bit pool.
Referenced by getBit.
int CBiteRnd::BitsLeft
The number of bits left in the bit pool.
Referenced by getBit, init.
CBiteRnd::CBiteRnd()
Default constructor, calls the init() function.
References init.
CBiteRnd::CBiteRnd(const int NewSeed)
Constructor, calls the init() function. NewSeed Random seed value.
References init.
void CBiteRnd::init(const int NewSeed, biteopt_rng const arf=NULL, void *const ardata=NULL)
Function initializes *this PRNG object. NewSeed New random seed value. Ignored, if "arf" is non-NULL. arf External random number generator to use; NULL: use the default PRNG. Note that the external RNG should be seeded externally. ardata Data pointer to pass to the "arf" function.
References advance, BitsLeft, Hash, lcg, rdata, rf, Seed.
Referenced by biteopt_minimize, CBiteRnd, CBiteRnd.
double CBiteRnd::get()
Random number in the range [0; 1).
References advance.
Referenced by CBiteOpt::generateSol1, CBiteOpt::generateSol10, CBiteOpt::generateSol3, getGaussian, getInt, getLog, CNMSeqOpt::init, CBiteOpt::optimize, CSpherOpt::optimize, CBitePop< ptype >::wrapParam, CBiteOptBase< ptype >::wrapParamReal.
int CBiteRnd::getInt(const int N1)
N1 Integer value range. Random integer number in the range [0; N1). N1 denotes the number of bins, not the maximal returned value.
References get.
Referenced by CBiteOpt::generateSol1, CBiteOpt::generateSol2, CBiteOpt::generateSol2b, CBiteOpt::generateSol2c, CBiteOpt::generateSol2d, CBiteOpt::generateSol5, CBiteOpt::generateSol6, CBiteOpt::generateSol9, CBiteOptDeep::optimize, CDEOpt::optimize, CBiteSelBase::reset, CBiteOpt::selectParPop.
double CBiteRnd::getSqr()
Random number in the range [0; 1). Beta distribution with Alpha=0.5, Beta=1 (squared).
References advance.
Referenced by getSqrInt.
double CBiteRnd::getPow(const double p)
Random number in the range [0; 1), raised to the specified power. The function has branching for optimization.
References advance.
Referenced by CBiteOpt::generateSol6, CBiteOpt::generateSol7, CBiteOpt::getMinSolIndex, getPowInt.
double CBiteRnd::getLog()
Random number in the range (-1; 1) with approximately logarithmic PDF, two-lobe with peak at 0.
References get.
Referenced by getLogInt.
int CBiteRnd::getSqrInt(const int N1)
N1 Integer value range. Random integer number in the range [0; N1). Beta distribution with Alpha=0.5, Beta=1 (squared). N1 denotes the number of bins, not the maximal returned value.
References getSqr.
Referenced by CBiteOpt::generateSol1, CBiteOpt::generateSol10, CBiteOpt::generateSol2, CBiteOpt::generateSol2b, CBiteOpt::generateSol2d, CBiteOpt::generateSol3, CBiteOpt::generateSol4, CBiteOpt::generateSol5, CBiteOpt::generateSol5b, CBiteOpt::generateSol8, CBiteOpt::generateSol9.
int CBiteRnd::getPowInt(const double p, const int N1)
N1 Integer value range. Random integer number in the range [0; N1), raised to the specified power. N1 denotes the number of bins, not the maximal returned value.
References getPow.
Referenced by CBiteOpt::generateSol2c, CDEOpt::optimize, CBiteSelBase::select.
int CBiteRnd::getLogInt(const int N1)
N1 Integer value range. Random integer number in the range [0; N1), with approximately logarithmic PDF, peak at 0.
References getLog.
uint64_t CBiteRnd::getRaw()
Uniformly-distributed random number in the "raw" scale.
References advance.
Referenced by CBiteOpt::generateSol2c, CBiteOpt::generateSol5, CDEOpt::optimize, CBitePop< ptype >::wrapParam.
double CBiteRnd::getTPDF()
TPDF random number in the range (-1; 1).
References advance.
Referenced by CBiteOpt::generateSol1.
double CBiteRnd::getGaussian()
Function generates a Gaussian-distributed pseudo-random number with mean=0 and std.dev=1. Algorithm is adopted from "Leva, J. L. 1992. "A Fast Normal Random Number Generator", ACM Transactions on Mathematical Software, vol. 18, no. 4, pp. 449-453".
References get.
Referenced by CBiteOpt::generateSol8, CBitePop< ptype >::getGaussianInt, CNMSeqOpt::init, CBiteOrt::sample.
int CBiteRnd::getBit()
Function returns the next random bit, usually used for 50% probability evaluations efficiently.
References advance, BitPool, BitsLeft.
Referenced by CBiteOpt::generateSol2c, CBiteOpt::generateSol4, CBiteOpt::generateSol5, CBiteOpt::generateSol5b, CBiteOpt::generateSol6, CBiteOpt::generateSol7, CBiteOpt::generateSol9, CDEOpt::optimize.
uint64_t CBiteRnd::advance()
Function advances the PRNG and returns the next PRNG value.
References Hash, lcg, rdata, rf, Seed.
Referenced by get, getBit, getPow, getRaw, getSqr, getTPDF, init.