CBitePop
const int CBitePop< ptype >::IntOverBits
The number of bits of precision required for integer centroid calculation and overflows.
Referenced by CBitePop< ptype >::updateCentroid.
const int CBitePop< ptype >::IntMantBits
Mantissa size of the integer parameter values (higher by 1 bit in practice for real value 1.0). Accounts for a sign bit, and possible accumulation overflows.
const int64_t CBitePop< ptype >::IntMantMult
multiplier.
Mantissa
Referenced by CBitePop< ptype >::getGaussianInt, CBiteOptBase< ptype >::updateDiffValues, CBitePop< ptype >::wrapParam.
const int64_t CBitePop< ptype >::IntMantMultM
IntMantMult.
Negative
Referenced by CBitePop< ptype >::wrapParam.
const int64_t CBitePop< ptype >::IntMantMult2
IntMantMult * 2.
=
Referenced by CBitePop< ptype >::wrapParam.
const int64_t CBitePop< ptype >::IntMantMask
corresponds to mantissa.
Mask that
Referenced by CBitePop< ptype >::wrapParam.
int CBitePop< ptype >::ParamCount
The total number of internal parameter values in use.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy, CBitePop< ptype >::copyParams, CBitePop< ptype >::copyValues, CBiteParPops< ptype >::getMinDistParPop, CBiteOptBase< ptype >::initBuffers, CBitePop< ptype >::initBuffers, CBiteOptBase< ptype >::initCommonVars, CBitePop< ptype >::updateCentroid, CBiteOptBase< ptype >::updateDiffValues, CBitePop< ptype >::updatePop, CBitePop< ptype >::zeroParams.
double CBitePop< ptype >::ParamCountI
= 1.0 / ParamCount.
Referenced by CBitePop< ptype >::initBuffers.
int CBitePop< ptype >::PopSize
The size of population in use (maximal).
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy, CBitePop< ptype >::initBuffers, CBitePop< ptype >::resetCurPopPos, CBitePop< ptype >::updateCentroid, CBitePop< ptype >::updatePop.
int CBitePop< ptype >::PopSize1
= PopSize - 1.
Referenced by CBitePop< ptype >::initBuffers, CBitePop< ptype >::resetCurPopPos, CBitePop< ptype >::updatePop.
int CBitePop< ptype >::CurPopSize
Current population size.
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::decrCurPopSize, CBitePop< ptype >::getCurPopSize, CBitePop< ptype >::incrCurPopSize, CBitePop< ptype >::resetCurPopPos.
int CBitePop< ptype >::CurPopSize1
= CurPopSize - 1.
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::decrCurPopSize, CBitePop< ptype >::incrCurPopSize, CBitePop< ptype >::resetCurPopPos.
double CBitePop< ptype >::CurPopSizeI
= 1.0 / CurPopSize.
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::decrCurPopSize, CBitePop< ptype >::incrCurPopSize, CBitePop< ptype >::resetCurPopPos.
int CBitePop< ptype >::CurPopPos
update. This variable should be initialized by the optimizer.
Current population position, for initial population
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::getCurParams, CBitePop< ptype >::getCurPopPos, CBitePop< ptype >::resetCurPopPos, CBitePop< ptype >::updatePop.
int CBitePop< ptype >::CnsCount
The number of constraints per solution.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy, CBitePop< ptype >::initBuffers.
int CBitePop< ptype >::ObjCount
The number of objectives per solution.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy, CBitePop< ptype >::initBuffers.
uint8_t* CBitePop< ptype >::PopParamsBuf
Buffer for all PopParams vectors.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::CBitePop, CBitePop< ptype >::deleteBuffers, CBitePop< ptype >::initBuffers.
ptype** CBitePop< ptype >::PopParams
Population parameter vectors. Always kept sorted in ascending cost order. Each vector represents a complex item, with additional data stored after parameter values (see Offs constants).
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy, CBitePop< ptype >::deleteBuffers, CBitePop< ptype >::getCurParams, CBitePop< ptype >::getParamsOrdered, CBitePop< ptype >::getPopParams, CBitePop< ptype >::initBuffers, CBitePop< ptype >::updateCentroid, CBitePop< ptype >::updatePop.
size_t CBitePop< ptype >::PopCnsOffs
a population item.
Byte offset to the constraint values within
Referenced by CBitePop< ptype >::getCnsPtr, CBitePop< ptype >::initBuffers.
size_t CBitePop< ptype >::PopObjOffs
population item.
Byte offset to the objective values within a
Referenced by CBitePop< ptype >::getObjPtr, CBitePop< ptype >::initBuffers.
size_t CBitePop< ptype >::PopRankOffs
item.
Byte offset to the rank value within a population
Referenced by CBitePop< ptype >::getRankPtr, CBitePop< ptype >::initBuffers.
size_t CBitePop< ptype >::PopItemSize
Size in bytes of population item.
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::initBuffers.
ptype* CBitePop< ptype >::CentParams
Centroid of the parameter vectors.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy, CBitePop< ptype >::deleteBuffers, CBitePop< ptype >::getCentroid, CBitePop< ptype >::initBuffers, CBitePop< ptype >::updateCentroid, CBitePop< ptype >::updatePop.
bool CBitePop< ptype >::NeedCentUpdate
"True" if centroid update is needed.
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::decrCurPopSize, CBitePop< ptype >::incrCurPopSize, CBitePop< ptype >::initBuffers, CBitePop< ptype >::resetCurPopPos, CBitePop< ptype >::updateCentroid, CBitePop< ptype >::updatePop.
double CBitePop< ptype >::CentLPC
Centroid averaging filter coefficient.
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::decrCurPopSize, CBitePop< ptype >::incrCurPopSize, CBitePop< ptype >::initBuffers, CBitePop< ptype >::resetCurPopPos, CBitePop< ptype >::updatePop.
ptype* CBitePop< ptype >::TmpParams
element of the PopParams array.
Temporary parameter vector, points to the last
Referenced by CBitePop< ptype >::initBuffers, CBitePop< ptype >::updateCentroid.
CBitePop< ptype >::CBitePop()
References CBitePop< ptype >::CentParams, CBitePop< ptype >::CnsCount, CBitePop< ptype >::ObjCount, CBitePop< ptype >::ParamCount, CBitePop< ptype >::PopParams, CBitePop< ptype >::PopParamsBuf, CBitePop< ptype >::PopSize.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy, CBitePop< ptype >::operator=, CBiteParPops< ptype >::setParPopCount.
CBitePop< ptype >::CBitePop(const CBitePop &s)
References CBitePop< ptype >::CBitePop, CBitePop< ptype >::CentParams, CBitePop< ptype >::CnsCount, CBitePop< ptype >::copy, CBitePop< ptype >::initBuffers, CBitePop< ptype >::ObjCount, CBitePop< ptype >::ParamCount, CBitePop< ptype >::PopParams, CBitePop< ptype >::PopParamsBuf, CBitePop< ptype >::PopSize.
virtual CBitePop< ptype >::~CBitePop()
References CBitePop< ptype >::deleteBuffers.
CBitePop & CBitePop< ptype >::operator=(const CBitePop &s)
References CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy.
virtual void CBitePop< ptype >::initBuffers(const int aParamCount, const int aPopSize, const int aCnsCount=0, const int aObjCount=1)
Function initializes all common buffers, and "PopSize" variables. This function should be called when population's dimensions were changed. This function calls the deleteBuffers() function to release any derived classes' allocated buffers. Allocates an additional vector for temporary use, which is at the same the last vector in the PopParams array. Derived classes should call this function of the base class. aParamCount New parameter count. aPopSize New population size. If <= 0, population buffers will not be allocated. aCnsCount New constraint value count. aObjCount New objective value count. If equals 0, a rank element will not be auto-added.
References CBitePop< ptype >::calcLP1Coeff, CBitePop< ptype >::CentLPC, CBitePop< ptype >::CentParams, CBitePop< ptype >::CnsCount, CBitePop< ptype >::deleteBuffers, CBitePop< ptype >::NeedCentUpdate, CBitePop< ptype >::ObjCount, CBitePop< ptype >::ParamCount, CBitePop< ptype >::ParamCountI, CBitePop< ptype >::PopCnsOffs, CBitePop< ptype >::PopItemSize, CBitePop< ptype >::PopObjOffs, CBitePop< ptype >::PopParams, CBitePop< ptype >::PopParamsBuf, CBitePop< ptype >::PopRankOffs, CBitePop< ptype >::PopSize, CBitePop< ptype >::PopSize1, CBitePop< ptype >::TmpParams.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::copy.
void CBitePop< ptype >::copy(const CBitePop &s)
Function copies population from the specified source population. If *this population has a different size, or is uninitialized, it will be initialized to source's population size. s Source population to copy. Should be initalized.
References CBitePop< ptype >::CBitePop, CBitePop< ptype >::CentLPC, CBitePop< ptype >::CentParams, CBitePop< ptype >::CnsCount, CBitePop< ptype >::copyParams, CBitePop< ptype >::CurPopPos, CBitePop< ptype >::CurPopSize, CBitePop< ptype >::CurPopSize1, CBitePop< ptype >::CurPopSizeI, CBitePop< ptype >::initBuffers, CBitePop< ptype >::NeedCentUpdate, CBitePop< ptype >::ObjCount, CBitePop< ptype >::ParamCount, CBitePop< ptype >::PopItemSize, CBitePop< ptype >::PopParams, CBitePop< ptype >::PopSize.
Referenced by CBitePop< ptype >::CBitePop, CBitePop< ptype >::operator=.
void CBitePop< ptype >::updateCentroid()
Function recalculates centroid based on the current population size. The NeedCentUpdate variable can be checked if centroid update is needed. This function resets the NeedCentUpdate to "false". This function should only be called after the population is filled.
References CBitePop< ptype >::CentParams, CBitePop< ptype >::copyParams, CBitePop< ptype >::IntOverBits, CBitePop< ptype >::NeedCentUpdate, CBitePop< ptype >::ParamCount, CBitePop< ptype >::PopParams, CBitePop< ptype >::PopSize, CBitePop< ptype >::TmpParams.
const ptype * CBitePop< ptype >::getCentroid() const
Function returns pointer to the centroid vector. The NeedUpdateCent should be checked and and if it is equal to "true", the updateCentroid() function called.
References CBitePop< ptype >::CentParams.
Referenced by CBiteParPops< ptype >::getMinDistParPop.
const ptype * CBitePop< ptype >::getParamsOrdered(const int i) const
Function returns population's parameter vector by the specified index from the ordered list. i Parameter vector index.
References CBitePop< ptype >::PopParams.
Referenced by CBiteOpt::generateSol1, CBiteOpt::generateSol2b, CBiteOpt::generateSol5, CBiteOpt::generateSol5b.
double * CBitePop< ptype >::getCnsPtr(ptype *const pp) const
Function returns pointer to constraint values sub-array within the specified population vector. pp Population vector pointer (usually within PopParams).
References CBitePop< ptype >::PopCnsOffs.
double * CBitePop< ptype >::getObjPtr(ptype *const pp) const
Function returns pointer to objective values sub-array within the specified population vector. pp Population vector pointer (usually within PopParams).
References CBitePop< ptype >::PopObjOffs.
Referenced by CBitePop< ptype >::updatePop.
double * CBitePop< ptype >::getRankPtr(ptype *const pp) const
Function returns pointer to the rank value sub-array within the specified population vector. pp Population vector pointer (usually within PopParams).
References CBitePop< ptype >::PopRankOffs.
Referenced by CBitePop< ptype >::updatePop.
const ptype ** CBitePop< ptype >::getPopParams() const
Function returns a pointer to array of population vector pointers, which are sorted in the ascending cost order.
References CBitePop< ptype >::PopParams.
Referenced by CBiteOrt::update.
ptype * CBitePop< ptype >::getCurParams() const
Function returns pointer to the next available parameter vector, at the initialization stage. When the population was filled, the function returns pointer to a temporary vector.
References CBitePop< ptype >::CurPopPos, CBitePop< ptype >::PopParams.
int CBitePop< ptype >::getCurPopSize() const
Function returns current population size.
References CBitePop< ptype >::CurPopSize.
Referenced by CBiteOpt::generateSol1, CBiteOpt::generateSol5, CBiteOpt::generateSol5b, CBiteOrt::update.
int CBitePop< ptype >::getCurPopPos() const
Function returns current population position.
References CBitePop< ptype >::CurPopPos.
void CBitePop< ptype >::resetCurPopPos()
Function resets the current population position to zero, and sets CurPopSize to PopSize. This function is usually called when the population needs to be completely changed. This function should be called before any updates to *this population (usually during optimizer's initialization).
References CBitePop< ptype >::calcLP1Coeff, CBitePop< ptype >::CentLPC, CBitePop< ptype >::CurPopPos, CBitePop< ptype >::CurPopSize, CBitePop< ptype >::CurPopSize1, CBitePop< ptype >::CurPopSizeI, CBitePop< ptype >::NeedCentUpdate, CBitePop< ptype >::PopSize, CBitePop< ptype >::PopSize1.
Referenced by CBiteOptBase< ptype >::initCommonVars.
void CBitePop< ptype >::incrCurPopSize()
Function increases current population size, and updates the required variables. This function can only be called if CurPopSize is less than PopSize, and previously the whole population was filled.
References CBitePop< ptype >::calcLP1Coeff, CBitePop< ptype >::CentLPC, CBitePop< ptype >::CurPopSize, CBitePop< ptype >::CurPopSize1, CBitePop< ptype >::CurPopSizeI, CBitePop< ptype >::NeedCentUpdate.
void CBitePop< ptype >::decrCurPopSize()
Function decreases current population size, and updates the required variables. This function can only be called if CurPopSize is greater than 1, and the whole population was filled.
References CBitePop< ptype >::calcLP1Coeff, CBitePop< ptype >::CentLPC, CBitePop< ptype >::CurPopSize, CBitePop< ptype >::CurPopSize1, CBitePop< ptype >::CurPopSizeI, CBitePop< ptype >::NeedCentUpdate.
int CBitePop< ptype >::updatePop(double UpdCost, const ptype *const UpdParams, const bool DoUpdateCentroid, const bool CanRejectCost=true)
Function replaces the highest-cost previous solution, updates centroid. This function considers the value of the CurPopPos variable - if it is smaller than the PopSize, the new solution will be added to population without any checks. UpdCost Cost of the new solution. UpdParams New parameter values. DoUpdateCentroid "True" if centroid should be updated using running sum. This update is done for parallel populations. CanRejectCost If "true", solution with a duplicate cost will be rejected; this may provide a performance improvement. Solutions can only be rejected when the whole population was filled. Insertion position, ">=CurPopSize" if the cost constraint was not met.
References CBitePop< ptype >::CentLPC, CBitePop< ptype >::CentParams, CBitePop< ptype >::copyParams, CBitePop< ptype >::CurPopPos, CBitePop< ptype >::getObjPtr, CBitePop< ptype >::getRankPtr, CBitePop< ptype >::NeedCentUpdate, CBitePop< ptype >::ParamCount, CBitePop< ptype >::PopParams, CBitePop< ptype >::PopSize, CBitePop< ptype >::PopSize1.
virtual void CBitePop< ptype >::deleteBuffers()
Function deletes buffers previously allocated via the initBuffers() function. Derived classes should call this function of the base class.
References CBitePop< ptype >::CentParams, CBitePop< ptype >::PopParams, CBitePop< ptype >::PopParamsBuf.
Referenced by CBitePop< ptype >::initBuffers, CBitePop< ptype >::~CBitePop.
void CBitePop< ptype >::zeroParams(ptype *const dst) const
An aux function that resets a parameter vector to zero values. dst Destination vector.
References CBitePop< ptype >::ParamCount.
void CBitePop< ptype >::copyParams(ptype *const dst, const ptype *const src) const
An aux function that copies a parameter vector. dst Destination vector. src Source vector.
References CBitePop< ptype >::ParamCount.
Referenced by CBitePop< ptype >::copy, CBitePop< ptype >::updateCentroid, CBitePop< ptype >::updatePop.
void CBitePop< ptype >::copyValues(double *const dst, const double *const src) const
An aux function that copies a real solution vector. dst Destination vector. src Source vector.
References CBitePop< ptype >::ParamCount.
Referenced by CBiteOptBase< ptype >::updateBestCost.
static ptype CBitePop< ptype >::wrapParam(CBiteRnd &rnd, const ptype v)
Function wraps the specified parameter value so that it stays in the [0.0; 1.0] range (including in integer range), by wrapping it over the boundaries using random operator. This operation improves convergence in comparison to clamping. v Parameter value to wrap. Wrapped parameter value.
References CBiteRnd::get, CBiteRnd::getRaw, CBitePop< ptype >::IntMantMask, CBitePop< ptype >::IntMantMult, CBitePop< ptype >::IntMantMult2, CBitePop< ptype >::IntMantMultM.
static ptype CBitePop< ptype >::getGaussianInt(CBiteRnd &rnd, const double sd, const ptype meanInt)
Function generates a Gaussian-distributed pseudo-random number, in integer scale, with the specified mean and std.dev. rnd Uniform PRNG. sd Standard deviation multiplier. meanInt Mean value, in integer scale.
References CBiteRnd::getGaussian, CBitePop< ptype >::IntMantMult.
static double CBitePop< ptype >::calcLP1Coeff(const double Count)
Function calculates averaging coefficient of a "leaky integrator" 1st order low-pass filter. Count An approximate number of samples to average.
Referenced by CBitePop< ptype >::decrCurPopSize, CBitePop< ptype >::incrCurPopSize, CBitePop< ptype >::initBuffers, CBitePop< ptype >::resetCurPopPos.