CNMSeqOpt
EState
int CNMSeqOpt::N
The total number of internal parameter values in use.
Referenced by calccent, copy, eval, init, initBuffers, optimize, updateDims.
int CNMSeqOpt::M
The number of points in a simplex.
Referenced by calccent, findhi, init, initBuffers, optimize, updateDims.
int CNMSeqOpt::M1
= M - 1.
Referenced by optimize, updateDims.
double CNMSeqOpt::M1i
= 1.0 / ( M - 1 ).
Referenced by calccent, copy, updateDims.
int CNMSeqOpt::xlo
Current lowest-cost parameter vector.
Referenced by init, optimize.
int CNMSeqOpt::xhi
Current highest-cost parameter vector.
Referenced by calccent, copy, findhi, optimize.
int CNMSeqOpt::xhi2
Current second-highest-cost parameter vector.
Referenced by findhi, optimize.
double** CNMSeqOpt::x
Parameter vectors for all points.
Referenced by calccent, copy, init, initBuffers, examples.filter.filter.learn, optimize.
double* CNMSeqOpt::y
Parameter vector costs.
Referenced by CNMSeqOpt, copy, deleteBuffers, findhi, initBuffers, examples.filter.filter.learn, optimize, ~CNMSeqOpt.
double* CNMSeqOpt::x0
Referenced by calccent, copy, initBuffers, optimize.
double* CNMSeqOpt::x1
Temporary parameter vector 1. Passed to stExpansion.
Referenced by initBuffers, optimize.
double CNMSeqOpt::y1
stExpansion.
Cost of temporary parameter vector 1. Passed to
Referenced by optimize.
double* CNMSeqOpt::x2
Temporary parameter vector 2.
Referenced by CNMSeqOpt, deleteBuffers, initBuffers, optimize, ~CNMSeqOpt.
double* CNMSeqOpt::rx
Lowest-cost parameter vector used during reduction.
Referenced by optimize.
int CNMSeqOpt::rj
Current vector index during reduction.
Referenced by optimize.
bool CNMSeqOpt::DoInitEvals
"True" if initial evaluations should be performed.
Referenced by init, optimize.
EState CNMSeqOpt::State
Current optimization state.
Referenced by init, optimize.
CNMSeqOpt::CNMSeqOpt()
References x2, y.
virtual CNMSeqOpt::~CNMSeqOpt()
References x2, y.
void CNMSeqOpt::updateDims(const int aParamCount, const int PopSize0=0)
Function updates dimensionality of *this object. aParamCount The number of parameters being optimized. PopSize0 The number of elements in population to use. If set to 0 or negative, the default formula will be used.
References initBuffers, M, M1, M1i, N, CBitePop< double >::ParamCount, CBitePop< double >::PopSize.
void CNMSeqOpt::init(CBiteRnd &rnd, const double *const InitParams=NULL, const double InitRadius=1.0)
Function initializes *this optimizer. Performs N=PopSize objective function evaluations. rnd Random number generator. InitParams If not NULL, initial parameter vector, also used as centroid. InitRadius Initial radius, relative to the default value. Set to negative to use uniformly-random sampling.
References CBitePop< double >::copyParams, CBiteOptBase< double >::DiffValues, DoInitEvals, CBiteRnd::get, CBiteRnd::getGaussian, CBiteOptBase< double >::initCommonVars, M, CBiteOptBase< double >::MinValues, N, State, stReflection, x, xlo.
int CNMSeqOpt::optimize(CBiteRnd &rnd, double *const OutCost=NULL, double *const OutValues=NULL)
Function performs the parameter optimization iteration that involves 1 objective function evaluation. rnd Random number generator. OutCost If not NULL, pointer to variable that receives cost of the newly-evaluated solution. OutValues If not NULL, pointer to array that receives newly-evaluated parameter vector, in real scale. The number of non-improving iterations so far.
References calccent, copy, CBitePop< double >::CurPopPos, DoInitEvals, eval, M, M1, N, CBitePop< double >::ParamCountI, rj, rx, CBiteOptBase< double >::StallCount, State, stContraction, stExpansion, stReduction, stReflection, x, x0, x1, x2, xhi, xhi2, xlo, y, y1.
virtual void CNMSeqOpt::initBuffers(const int aParamCount, const int aPopSize, const int aCnsCount=0, const int aObjCount=1)
Function initializes all common buffers, and "PopSize" variables. This function should be called when population's dimensions were changed. This function calls the deleteBuffers() function to release any derived classes' allocated buffers. Allocates an additional vector for temporary use, which is at the same the last vector in the PopParams array. Derived classes should call this function of the base class. aParamCount New parameter count. aPopSize New population size. If <= 0, population buffers will not be allocated. aCnsCount New constraint value count. aObjCount New objective value count. If equals 0, a rank element will not be auto-added.
References CBitePop< double >::CentParams, M, N, CBitePop< double >::PopParams, CBitePop< double >::TmpParams, x, x0, x1, x2, y.
Referenced by updateDims.
virtual void CNMSeqOpt::deleteBuffers()
Function deletes buffers previously allocated via the initBuffers() function. Derived classes should call this function of the base class.
References x2, y.
void CNMSeqOpt::findhi()
Function finds the highest-cost vector.
References M, xhi, xhi2, y.
Referenced by calccent, copy.
void CNMSeqOpt::calccent()
Function calculates the centroid vector that excludes a highest-cost parameter vector.
References CBitePop< double >::copyParams, findhi, M, M1i, N, x, x0, xhi.
Referenced by optimize.
void CNMSeqOpt::copy(const double *const ip, const double Cost)
Function replaces the highest-cost vector with a new vector. Function also resets the StallCount to 0. ip Input vector. Cost Input vector's cost.
References CBitePop< double >::copyParams, findhi, M1i, N, CBiteOptBase< double >::StallCount, x, x0, xhi, y.
Referenced by optimize.
double CNMSeqOpt::eval(CBiteRnd &rnd, const double *const Params, double *const OutCost=NULL, double *const OutValues=NULL)
Function evaluates parameter vector and applies value range wrapping, also records a new best solution. rnd Random number generator. Params Parameter vector to evaluate. OutCost If not NULL, pointer to variable that receives cost of the newly-evaluated solution. OutValues If not NULL, pointer to array that receives newly-evaluated parameter vector, in real scale.
References CBitePop< double >::copyValues, N, CBiteOptBase< double >::NewValues, CBiteOptInterface::optcost, CBiteOptBase< double >::updateBestCost, CBiteOptBase< double >::wrapParamReal.
Referenced by optimize.