LBFGSpp::LBFGSBSolver
typedef Eigen::Matrix<Scalar, Eigen::Dynamic, 1> LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::Vector
typedef Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic> LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::Matrix
typedef Eigen::Map<Vector> LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::MapVec
typedef std::vector<int> LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::IndexSet
const LBFGSBParam<Scalar>& LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_param
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::LBFGSBSolver, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
BFGSMat<Scalar, true> LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_bfgs
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
Vector LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_fx
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
Vector LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_xp
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
Vector LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_grad
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
Vector LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_gradp
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
Vector LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_drt
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
void LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset(int n)
References LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_bfgs, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_drt, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_fx, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_grad, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_gradp, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_param, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_xp.
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize, examples.siemens.Plant.simulate.
static void LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::force_bounds(Vector &x, const Vector &lb, const Vector &ub)
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize.
static Scalar LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::proj_grad_norm(const Vector &x, const Vector &g, const Vector &lb, const Vector &ub)
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize.
static Scalar LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::max_step_size(const Vector &x0, const Vector &drt, const Vector &lb, const Vector &ub)
Referenced by LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize.
LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::LBFGSBSolver(const LBFGSBParam< Scalar > &param)
Constructor for the L-BFGS-B solver. param An object of LBFGSParam to store parameters for the algorithm
References LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_param.
int LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize(Foo &f, Vector &x, Scalar &fx, const Vector &lb, const Vector &ub)
Minimizing a multivariate function subject to box constraints, using the L-BFGS-B algorithm. Exceptions will be thrown if error occurs. f A function object such that f(x, grad) returns the objective function value at x, and overwrites grad with the gradient. x In: An initial guess of the optimal point. Out: The best point found. fx Out: The objective function value at x. lb Lower bounds for x. ub Upper bounds for x. Number of iterations used.
References LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::force_bounds, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_bfgs, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_drt, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_fx, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_grad, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_gradp, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_param, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::m_xp, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::max_step_size, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::proj_grad_norm, LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::reset.
Referenced by dual_annealing::minLBFGS.