CBiteOrt
double CBiteOrt::CentPow
Centroid weighting power coefficient.
Referenced by CBiteOrt, updateWeights.
double CBiteOrt::CovUpdSlow
Covariance matrix update rate, slow.
Referenced by CBiteOrt, update.
double CBiteOrt::CovUpdFast
Covariance matrix update rate, fast.
Referenced by CBiteOrt, update.
double CBiteOrt::SigmaMulBase1
Sigma damping multiplier, for sphere.
Referenced by CBiteOrt, update.
double CBiteOrt::SigmaMulBase2
Sigma damping multiplier, for needle.
Referenced by CBiteOrt, update.
double CBiteOrt::SigmaMulExp2
Sigma expansion multiplier, for needle.
Referenced by CBiteOrt, update.
double CBiteOrt::EvalFac
The multiplier of the population size, affects the actual number of function evaluations performed, >=1.
Referenced by CBiteOrt, update, updateWeights.
double* CBiteOrt::CovParamsBuf
CovParams buffer.
Referenced by CBiteOrt, deleteBuffers, init, initBuffers.
double** CBiteOrt::CovParams
Covariance matrix.
Referenced by CBiteOrt, deleteBuffers, eigen, init, initBuffers, update.
double* CBiteOrt::BParamsBuf
BParams buffer.
Referenced by CBiteOrt, deleteBuffers, init, initBuffers.
double** CBiteOrt::BParams
Rotation matrix.
Referenced by CBiteOrt, deleteBuffers, eigen, init, initBuffers, ort, ortnc, sample, unort.
double* CBiteOrt::DParams
Std. deviations vector.
Referenced by CBiteOrt, deleteBuffers, eigen, init, initBuffers, sample, update.
double* CBiteOrt::DParamsN
Std. deviations vector, for negative values.
Referenced by CBiteOrt, deleteBuffers, init, initBuffers, sample, update.
double* CBiteOrt::PrevCentParams
Previous centroid vector.
Referenced by CBiteOrt, deleteBuffers, initBuffers, update.
double* CBiteOrt::WPopCent
Weighting coefficients for ordered population, for centroid calculation.
Referenced by calcCent, CBiteOrt, deleteBuffers, initBuffers, updateWeights.
double* CBiteOrt::WPopCov
Weighting coefficients for covariance calculation, squared.
Referenced by CBiteOrt, deleteBuffers, initBuffers, update, updateWeights.
double CBiteOrt::spc
spherical.
Distribution's sphericity coefficient. 1 - fully
Referenced by init, update.
CBiteOrt::CBiteOrt(const CBiteOrt &)
References CBiteOrt.
Referenced by CBiteOrt, operator=.
CBiteOrt & CBiteOrt::operator=(const CBiteOrt &)
References CBiteOrt.
CBiteOrt::CBiteOrt()
References BParams, BParamsBuf, CentPow, CovParams, CovParamsBuf, CovUpdFast, CovUpdSlow, DParams, DParamsN, EvalFac, PrevCentParams, SigmaMulBase1, SigmaMulBase2, SigmaMulExp2, WPopCent, WPopCov.
void CBiteOrt::updateDims(const int aParamCount, const int aPopSize)
Function updates dimensions of *this object. aParamCount The number of elements in the parameter vector. aPopSize Size of population used to calculate the rotation matrix.
References initBuffers, CBitePop< double >::ParamCount, CBitePop< double >::PopSize.
void CBiteOrt::updateWeights(const int UsePopSize)
Function updates centroid and covariance estimation weights. UsePopSize Population size to use.
References CentPow, EvalFac, WPopCent, WPopCov.
Referenced by update.
void CBiteOrt::init(const double *const InitCent=NULL, const double *const InitSigma=NULL)
Function initializes *this object to "no rotation" state, with the specified initial centroid and sigma. InitCent Initial centroids per parameter (NULL for origin). InitSigma Initial sigmas per parameter (NULL for 0.25).
References BParams, BParamsBuf, CBitePop< double >::CentParams, CovParams, CovParamsBuf, DParams, DParamsN, CBitePop< double >::ParamCount, spc.
void CBiteOrt::update(const CBitePop &ExtPop)
Function performs rotation matrix update. ExtPop External population.
References calcCent, CBitePop< double >::CBitePop, CBitePop< double >::CentParams, CBitePop< double >::copyParams, CovParams, CovUpdFast, CovUpdSlow, dotp, DParams, DParamsN, eigen, EvalFac, CBitePop< ptype >::getCurPopSize, CBitePop< ptype >::getPopParams, ortnc, CBitePop< double >::ParamCount, CBitePop< double >::PopParams, PrevCentParams, SigmaMulBase1, SigmaMulBase2, SigmaMulExp2, spc, CBitePop< double >::TmpParams, updateWeights, WPopCov.
void CBiteOrt::ort(const double *const ip, double *const op)
Function applies orthogonalization (rotation) to the parameter vector, subtracting centroid vector. ip Input unorthogonalized vector. op Output orthogonalized vector, can be equal to "ip".
References BParams, CBitePop< double >::CentParams, CBitePop< double >::ParamCount, CBitePop< double >::TmpParams.
void CBiteOrt::ortnc(const double *const ip, double *const op)
Function applies orthogonalization (rotation) to the parameter vector, without subtracting centroid vector. ip Input unorthogonalized vector. op Output orthogonalized vector, should not be equal to "ip".
References BParams, CBitePop< double >::ParamCount.
Referenced by update.
void CBiteOrt::unort(const double *const ip, double *const op)
Function undos orthogonalization (rotation) of the parameter vector, adding centroid vector. ip Input orthogonalized vector. op Output unorthogonalized vector, can be equal to "ip".
References BParams, CBitePop< double >::CentParams, CBitePop< double >::ParamCount, CBitePop< double >::TmpParams.
void CBiteOrt::sample(CBiteRnd &rnd, double *const op) const
Function "samples" new random population vector making a random draw from the current distribution. rnd Random number generator. op Resulting vector.
References BParams, CBitePop< double >::CentParams, DParams, DParamsN, CBiteRnd::getGaussian, CBitePop< double >::ParamCount, CBitePop< double >::TmpParams.
virtual void CBiteOrt::initBuffers(const int aParamCount, const int aPopSize, const int aCnsCount=0, const int aObjCount=0)
Function initializes all common buffers, and "PopSize" variables. This function should be called when population's dimensions were changed. This function calls the deleteBuffers() function to release any derived classes' allocated buffers. Allocates an additional vector for temporary use, which is at the same the last vector in the PopParams array. Derived classes should call this function of the base class. aParamCount New parameter count. aPopSize New population size. If <= 0, population buffers will not be allocated. aCnsCount New constraint value count. aObjCount New objective value count. If equals 0, a rank element will not be auto-added.
References BParams, BParamsBuf, CovParams, CovParamsBuf, DParams, DParamsN, CBitePop< double >::PopParams, CBitePop< double >::PopParamsBuf, PrevCentParams, WPopCent, WPopCov.
Referenced by updateDims.
virtual void CBiteOrt::deleteBuffers()
Function deletes buffers previously allocated via the initBuffers() function. Derived classes should call this function of the base class.
References BParams, BParamsBuf, CovParams, CovParamsBuf, DParams, DParamsN, PrevCentParams, WPopCent, WPopCov.
void CBiteOrt::eigen()
Function calculates eigenpairs of the current covariance matrix and updates DParams standard deviations vector.
References BParams, CovParams, DParams, CBitePop< double >::ParamCount, CBitePop< double >::TmpParams, tql2, tred2.
Referenced by update.
void CBiteOrt::calcCent(const double **const SortedParams, const int UsePopSize)
Function calculates centroid vector of population, with weighting. SortedParams Array of sorted population vectors. UsePopSize Population size to use.
References CBitePop< double >::CentParams, CBitePop< double >::ParamCount, WPopCent.
Referenced by update.
double CBiteOrt::dotp(const double *const p1, const double *const p2, const int c) const
Function calculates dot product of two per-parameter population vectors. p1 Parameter A's population vector. p2 Parameter B's population vector. c Element count.
Referenced by update.
static void CBiteOrt::tred2(const int n, double *d, double **V, double *e)
Householder triagonalization routine from JAMA package.
Referenced by eigen.
static double CBiteOrt::hypot_(double a, double b)
sqrt(a^2 + b^2) without under/overflow.
Referenced by tql2.
static double CBiteOrt::max_(const double a, const double b)
Function returns maximum of 2 values.
Referenced by tql2.
static void CBiteOrt::tql2(const int n, double *d, double **V, double *e)
Symmetric tridiagonal QL algorithm from JAMA package. Std. deviation vector sorting removed.
References hypot_, max_.
Referenced by eigen.