dual_annealing::Fitness
vec dual_annealing::Fitness::lower
Referenced by decode, encode, Fitness, getClosestFeasible, value.
vec dual_annealing::Fitness::upper
Referenced by Fitness.
const double dual_annealing::Fitness::LS_MAXITER_RATIO
Referenced by local_search.
const double dual_annealing::Fitness::LS_MAXITER_MIN
Referenced by local_search.
const double dual_annealing::Fitness::LS_MAXITER_MAX
Referenced by local_search.
callback_type dual_annealing::Fitness::func
Referenced by eval, Fitness.
long dual_annealing::Fitness::evaluationCounter
Referenced by eval, getEvaluations, maxEvalReached.
long dual_annealing::Fitness::maxEvals
Referenced by Fitness, maxEvalReached.
vec dual_annealing::Fitness::scale
Referenced by decode, encode, Fitness.
double dual_annealing::Fitness::bestY
Referenced by local_search, examples.noisy_tsp.TSP.optimize_mo, value.
vec dual_annealing::Fitness::bestX
Referenced by local_search, examples.noisy_tsp.TSP.optimize_mo, value.
dual_annealing::Fitness::Fitness(callback_type pfunc, vec *lower_limit, vec *upper_limit, long maxEvals_)
References func, lower, maxEvals, scale, upper.
vec dual_annealing::Fitness::getClosestFeasible(const vec &X) const
References lower.
Referenced by local_search, value.
double dual_annealing::Fitness::eval(const vec &X)
References evaluationCounter, func.
Referenced by value.
double dual_annealing::Fitness::value(const vec &X)
References bestX, bestY, decode, eval, getClosestFeasible, lower.
Referenced by dual_annealing::EnergyState::reset.
double dual_annealing::Fitness::local_search(const vec &x0, double currval, vec &res)
References bestX, bestY, getClosestFeasible, LS_MAXITER_MAX, LS_MAXITER_MIN, LS_MAXITER_RATIO, dual_annealing::minLBFGS.
vec dual_annealing::Fitness::encode(const vec &X) const
References lower, scale.
Referenced by optimizeDA_C.
vec dual_annealing::Fitness::decode(const vec &X) const
References lower, scale.
Referenced by optimizeDA_C, value.
int dual_annealing::Fitness::getEvaluations()
References evaluationCounter.
Referenced by optimizeDA_C.
bool dual_annealing::Fitness::maxEvalReached()
References evaluationCounter, maxEvals.