mode_optimizer::MoDeOptimizer
long mode_optimizer::MoDeOptimizer::runid
Referenced by MoDeOptimizer.
Fitness* mode_optimizer::MoDeOptimizer::fitfun
Referenced by getFitfun, init, MoDeOptimizer, modify, nextX, variation.
int mode_optimizer::MoDeOptimizer::popsize
Referenced by ask, getPopsize, getPopulation, init, examples.benchmark_gtop_pygmo.Cma_pyg.minimize, examples.benchmark_gtop_pygmo.De_pyg.minimize, MoDeOptimizer, nextX, pop_update, setPopsize, setX, tell.
int mode_optimizer::MoDeOptimizer::dim
Referenced by examples.damp.fitness.__call__, getDim, init, anpcp.ANPCP.init_tsp, MoDeOptimizer, modify, examples.siemens.Plant.next_product, nextX, examples.employee.problem.optimize, examples.employee.problem.optimize_mo, examples.damp.fitness.qd_fit, anpcp.ANPCP.random_x, anpcpc.ANPCPC.random_x, variation.
int mode_optimizer::MoDeOptimizer::nobj
Referenced by getNobj, init, MoDeOptimizer, pareto, pop_update.
int mode_optimizer::MoDeOptimizer::ncon
Referenced by getNcon, init, MoDeOptimizer, pareto.
double mode_optimizer::MoDeOptimizer::keep
double mode_optimizer::MoDeOptimizer::stopfitness
int mode_optimizer::MoDeOptimizer::iterations
Referenced by getIterations, MoDeOptimizer, nextX, pareto.
int mode_optimizer::MoDeOptimizer::n_evals
Referenced by MoDeOptimizer.
int mode_optimizer::MoDeOptimizer::stop
Referenced by getStop, MoDeOptimizer, tell.
double mode_optimizer::MoDeOptimizer::F0
Referenced by MoDeOptimizer, nextX.
double mode_optimizer::MoDeOptimizer::CR0
Referenced by MoDeOptimizer, nextX.
double mode_optimizer::MoDeOptimizer::F
Referenced by MoDeOptimizer, nextX.
double mode_optimizer::MoDeOptimizer::CR
Referenced by MoDeOptimizer, nextX.
double mode_optimizer::MoDeOptimizer::pro_c
Referenced by MoDeOptimizer, variation.
double mode_optimizer::MoDeOptimizer::dis_c
Referenced by MoDeOptimizer, variation.
double mode_optimizer::MoDeOptimizer::pro_m
Referenced by MoDeOptimizer, variation.
double mode_optimizer::MoDeOptimizer::dis_m
Referenced by MoDeOptimizer, variation.
pcg64* mode_optimizer::MoDeOptimizer::rs
Referenced by init, MoDeOptimizer, modify, nextX, variation, ~MoDeOptimizer.
mat mode_optimizer::MoDeOptimizer::popX
Referenced by ask, getPopulation, getX, init, nextX, pop_update, setX.
mat mode_optimizer::MoDeOptimizer::popY
Referenced by getY, init, is_dominated, pop_update, tell.
mat mode_optimizer::MoDeOptimizer::vX
Referenced by init, nextX, pop_update.
int mode_optimizer::MoDeOptimizer::vp
Referenced by init, nextX.
mat mode_optimizer::MoDeOptimizer::lastCon
Referenced by pareto.
vec mode_optimizer::MoDeOptimizer::lastEps
Referenced by pareto.
int mode_optimizer::MoDeOptimizer::next_size
Referenced by init.
std::vector<bool> mode_optimizer::MoDeOptimizer::vdone
Referenced by init.
int mode_optimizer::MoDeOptimizer::pos
Referenced by MoDeOptimizer.
bool mode_optimizer::MoDeOptimizer::nsga_update
Referenced by MoDeOptimizer, nextX, pop_update, tell.
double mode_optimizer::MoDeOptimizer::pareto_update
Referenced by MoDeOptimizer, nextX, tell.
double mode_optimizer::MoDeOptimizer::min_mutate
Referenced by MoDeOptimizer, modify.
double mode_optimizer::MoDeOptimizer::max_mutate
Referenced by MoDeOptimizer, modify.
bool* mode_optimizer::MoDeOptimizer::isInt
Referenced by MoDeOptimizer, modify.
mode_optimizer::MoDeOptimizer::MoDeOptimizer(long runid_, Fitness *fitfun_, int dim_, int nobj_, int ncon_, int seed_, int popsize_, double F_, double CR_, double pro_c_, double dis_c_, double pro_m_, double dis_m_, bool nsga_update_, double pareto_update_, double min_mutate_, double max_mutate_, bool *isInt_)
References CR, CR0, dim, dis_c, dis_m, F, F0, fitfun, init, isInt, iterations, max_mutate, min_mutate, n_evals, ncon, nobj, nsga_update, pareto_update, popsize, pos, pro_c, pro_m, rs, runid, stop.
mode_optimizer::MoDeOptimizer::~MoDeOptimizer()
References rs.
mat mode_optimizer::MoDeOptimizer::variation(const mat &x)
References dim, dis_c, dis_m, fitfun, pro_c, pro_m, rand01, rs, uniformVec.
Referenced by pop_update.
vec mode_optimizer::MoDeOptimizer::nextX(int p)
References CR, CR0, dim, F, F0, fitfun, iterations, modify, nsga_update, pareto_update, popsize, popX, rand01, randInt, rs, vp, vX.
Referenced by ask.
void mode_optimizer::MoDeOptimizer::modify(vec &x)
References dim, fitfun, isInt, max_mutate, min_mutate, rand01, rs.
Referenced by nextX.
vec mode_optimizer::MoDeOptimizer::crowd_dist(mat &y)
References sort_index, zeros.
Referenced by pop_update.
bool mode_optimizer::MoDeOptimizer::is_dominated(const vec &y, int p)
References popY.
Referenced by pareto_levels.
bool mode_optimizer::MoDeOptimizer::is_dominated(const mat &y, int i, int index)
vec mode_optimizer::MoDeOptimizer::pareto_levels(const mat &y)
References is_dominated, pareto, zeros.
Referenced by pareto.
vec mode_optimizer::MoDeOptimizer::objranks(mat objs)
References sort_index.
Referenced by pareto.
vec mode_optimizer::MoDeOptimizer::ranks(mat cons, vec eps)
References sort_index, zeros.
Referenced by pareto.
vec mode_optimizer::MoDeOptimizer::pareto(const mat &ys)
References iterations, lastCon, lastEps, ncon, nobj, objranks, pareto_levels, ranks, sort_index, zeros.
Referenced by pareto_levels, pop_update.
ivec mode_optimizer::MoDeOptimizer::random_int_vector(int size)
void mode_optimizer::MoDeOptimizer::pop_update()
References crowd_dist, nobj, nsga_update, pareto, popsize, popX, popY, sort_index, variation, vX.
Referenced by tell.
mat mode_optimizer::MoDeOptimizer::ask()
References nextX, popsize, popX.
void mode_optimizer::MoDeOptimizer::setX(mat xs)
References popsize, popX.
int mode_optimizer::MoDeOptimizer::tell(mat ys)
References pop_update, popsize, popY, stop.
Referenced by tell.
int mode_optimizer::MoDeOptimizer::tell(mat ys, bool nsga_update_, double pareto_update_)
References nsga_update, pareto_update, tell.
mat mode_optimizer::MoDeOptimizer::getPopulation()
References popsize, popX.
void mode_optimizer::MoDeOptimizer::init()
References constant, dim, fitfun, ncon, next_size, nobj, popsize, popX, popY, rs, vdone, vp, vX.
Referenced by MoDeOptimizer, setPopsize.
mat mode_optimizer::MoDeOptimizer::getX()
References popX.
mat mode_optimizer::MoDeOptimizer::getY()
References popY.
double mode_optimizer::MoDeOptimizer::getIterations()
References iterations.
double mode_optimizer::MoDeOptimizer::getStop()
References stop.
Fitness * mode_optimizer::MoDeOptimizer::getFitfun()
References fitfun.
int mode_optimizer::MoDeOptimizer::getDim()
References dim.
int mode_optimizer::MoDeOptimizer::getNobj()
References nobj.
int mode_optimizer::MoDeOptimizer::getNcon()
References ncon.
int mode_optimizer::MoDeOptimizer::getPopsize()
References popsize.
void mode_optimizer::MoDeOptimizer::setPopsize(int size)
References init, popsize.