differential_evolution::DeOptimizer
long differential_evolution::DeOptimizer::runid
Referenced by DeOptimizer.
Fitness* differential_evolution::DeOptimizer::fitfun
Referenced by DeOptimizer, do_optimize_delayed_update, doOptimize, getFitfun, next_improve, nextX, sample, sample_i.
int differential_evolution::DeOptimizer::popsize
Referenced by ask, askAll, DeOptimizer, do_optimize_delayed_update, doOptimize, getPopsize, init, examples.benchmark_gtop_pygmo.Cma_pyg.minimize, examples.benchmark_gtop_pygmo.De_pyg.minimize, nextX, tellAll.
int differential_evolution::DeOptimizer::dim
Referenced by examples.damp.fitness.__call__, DeOptimizer, doOptimize, getDim, init, anpcp.ANPCP.init_tsp, modify, examples.siemens.Plant.next_product, nextX, examples.employee.problem.optimize, examples.employee.problem.optimize_mo, examples.damp.fitness.qd_fit, anpcp.ANPCP.random_x, anpcpc.ANPCPC.random_x, sample.
int differential_evolution::DeOptimizer::maxEvaluations
Referenced by DeOptimizer, do_optimize_delayed_update, doOptimize.
double differential_evolution::DeOptimizer::keep
Referenced by DeOptimizer, doOptimize, tell.
double differential_evolution::DeOptimizer::stopfitness
Referenced by DeOptimizer, do_optimize_delayed_update, doOptimize, tell.
int differential_evolution::DeOptimizer::iterations
Referenced by DeOptimizer, do_optimize_delayed_update, doOptimize, getIterations, nextX, tell.
double differential_evolution::DeOptimizer::bestY
Referenced by DeOptimizer, do_optimize_delayed_update, doOptimize, getBestValue, examples.noisy_tsp.TSP.optimize_mo, tell.
vec differential_evolution::DeOptimizer::bestX
Referenced by doOptimize, getBestX, init, examples.noisy_tsp.TSP.optimize_mo, tell.
int differential_evolution::DeOptimizer::bestI
Referenced by ask, doOptimize, init, nextX, tell, update_mean.
int differential_evolution::DeOptimizer::stop
Referenced by DeOptimizer, do_optimize_delayed_update, doOptimize, getStop, tell, tellAll.
double differential_evolution::DeOptimizer::F0
Referenced by DeOptimizer, doOptimize, next_improve, nextX.
double differential_evolution::DeOptimizer::CR0
Referenced by DeOptimizer, doOptimize, nextX.
double differential_evolution::DeOptimizer::F
Referenced by DeOptimizer, doOptimize, nextX.
double differential_evolution::DeOptimizer::CR
Referenced by DeOptimizer, doOptimize, nextX.
pcg64* differential_evolution::DeOptimizer::rs
Referenced by DeOptimizer, rnd01, rndInt, sample, sample_i, ~DeOptimizer.
mat differential_evolution::DeOptimizer::popX
Referenced by ask, doOptimize, init, nextX, tell, update_mean.
mat differential_evolution::DeOptimizer::popX0
Referenced by init, tell.
mat differential_evolution::DeOptimizer::askedX
Referenced by askAll, getPopulation, init, tellAll.
ivec differential_evolution::DeOptimizer::askedP
Referenced by askAll, init, tellAll.
vec differential_evolution::DeOptimizer::popY
Referenced by doOptimize, init, tell.
vec differential_evolution::DeOptimizer::popIter
Referenced by doOptimize, init, tell.
queue<vec> differential_evolution::DeOptimizer::improvesX
Referenced by ask, tell.
queue<int> differential_evolution::DeOptimizer::improvesP
Referenced by ask, tell.
int differential_evolution::DeOptimizer::pos
Referenced by ask, DeOptimizer.
double differential_evolution::DeOptimizer::min_mutate
Referenced by DeOptimizer, modify.
double differential_evolution::DeOptimizer::max_mutate
Referenced by DeOptimizer, modify.
bool* differential_evolution::DeOptimizer::isInt
Referenced by DeOptimizer, modify.
bool differential_evolution::DeOptimizer::useNormal
Referenced by DeOptimizer, sample, sample_i, update_mean.
vec differential_evolution::DeOptimizer::sigma
Referenced by DeOptimizer, init, sample, sample_i, update_mean.
vec differential_evolution::DeOptimizer::mean
Referenced by DeOptimizer, init, sample, sample_i, update_mean.
vec differential_evolution::DeOptimizer::maxSigma
Referenced by init, update_mean.
vec differential_evolution::DeOptimizer::minSigma
Referenced by init, update_mean.
double differential_evolution::DeOptimizer::minSigmaVal
Referenced by DeOptimizer, init.
mat differential_evolution::DeOptimizer::meanHist
Referenced by init, update_mean.
int differential_evolution::DeOptimizer::meanHistIndex
Referenced by init, update_mean.
differential_evolution::DeOptimizer::DeOptimizer(long runid_, Fitness *fitfun_, int dim_, int seed_, int popsize_, int maxEvaluations_, double keep_, double stopfitness_, double F_, double CR_, double min_mutate_, double max_mutate_, bool *isInt_, const vec &guess_, const vec &inputSigma_, double minSigma_)
References bestY, CR, CR0, dim, F, F0, fitfun, init, isInt, iterations, keep, max_mutate, maxEvaluations, mean, min_mutate, minSigmaVal, popsize, pos, rs, runid, sigma, stop, stopfitness, useNormal.
differential_evolution::DeOptimizer::~DeOptimizer()
References rs.
double differential_evolution::DeOptimizer::rnd01()
References distr_01, rs.
Referenced by doOptimize, modify, nextX, tell.
int differential_evolution::DeOptimizer::rndInt(int max)
References distr_01, rs.
Referenced by doOptimize, nextX.
vec differential_evolution::DeOptimizer::sample()
References dim, fitfun, mean, normalVec, rs, sigma, useNormal.
Referenced by doOptimize, init, tell.
double differential_evolution::DeOptimizer::sample_i(int i)
References fitfun, mean, normreal, rs, sigma, useNormal.
Referenced by doOptimize, modify.
void differential_evolution::DeOptimizer::update_mean()
References bestI, maxSigma, mean, meanHist, meanHistIndex, minSigma, popX, sigma, useNormal.
Referenced by doOptimize, nextX.
vec differential_evolution::DeOptimizer::nextX(int p, const vec &xp, const vec &xb)
References bestI, CR, CR0, dim, F, F0, fitfun, iterations, modify, popsize, popX, rnd01, rndInt, update_mean.
Referenced by ask.
vec differential_evolution::DeOptimizer::next_improve(const vec &xb, const vec &x, const vec &xi)
References F0, fitfun, modify.
Referenced by doOptimize, tell.
void differential_evolution::DeOptimizer::modify(vec &x)
References dim, isInt, max_mutate, min_mutate, rnd01, sample_i.
Referenced by doOptimize, next_improve, nextX.
vec differential_evolution::DeOptimizer::ask(int &p)
References bestI, improvesP, improvesX, nextX, popsize, popX, pos.
Referenced by askAll, do_optimize_delayed_update.
int differential_evolution::DeOptimizer::tell(double y, const vec &x, int p)
References bestI, bestX, bestY, improvesP, improvesX, iterations, keep, next_improve, popIter, popX, popX0, popY, rnd01, sample, stop, stopfitness.
Referenced by do_optimize_delayed_update, tellAll.
mat differential_evolution::DeOptimizer::askAll()
References ask, askedP, askedX, popsize.
int differential_evolution::DeOptimizer::tellAll(vec &ys)
References askedP, askedX, popsize, stop, tell.
void differential_evolution::DeOptimizer::doOptimize()
References bestI, bestX, bestY, CR, CR0, dim, F, F0, fitfun, iterations, keep, maxEvaluations, modify, next_improve, popIter, popsize, popX, popY, rnd01, rndInt, sample, sample_i, stop, stopfitness, update_mean.
void differential_evolution::DeOptimizer::do_optimize_delayed_update(int workers)
References vec_id::_id, vec_id::_v, ask, bestY, evaluator::evaluate, fitfun, iterations, maxEvaluations, popsize, evaluator::result, stop, stopfitness, tell.
void differential_evolution::DeOptimizer::init()
References askedP, askedX, bestI, bestX, dim, maxSigma, mean, meanHist, meanHistIndex, minSigma, minSigmaVal, popIter, popsize, popX, popX0, popY, sample, sigma, zeros.
Referenced by DeOptimizer.
vec differential_evolution::DeOptimizer::getBestX()
References bestX.
double differential_evolution::DeOptimizer::getBestValue()
References bestY.
double differential_evolution::DeOptimizer::getIterations()
References iterations.
Fitness * differential_evolution::DeOptimizer::getFitfun()
References fitfun.
int differential_evolution::DeOptimizer::getDim()
References dim.
mat differential_evolution::DeOptimizer::getPopulation()
References askedX.
int differential_evolution::DeOptimizer::getStop()
References stop.
int differential_evolution::DeOptimizer::getPopsize()
References popsize.