CBiteOptDeep::CBiteOptWrap
CBiteOptDeep* CBiteOptDeep::CBiteOptWrap::Owner
Owner object.
Referenced by CBiteOptWrap, getMaxValues, getMinValues, optcost.
CBiteOptDeep::CBiteOptWrap::CBiteOptWrap(CBiteOptDeep *const aOwner)
References CBiteOptDeep::CBiteOptDeep, Owner.
virtual void CBiteOptDeep::CBiteOptWrap::getMinValues(double *const p) const
Virtual function that should fill minimal parameter value vector. p Minimal value vector.
References getMinValues, Owner.
Referenced by getMinValues.
virtual void CBiteOptDeep::CBiteOptWrap::getMaxValues(double *const p) const
Virtual function that should fill maximal parameter value vector. p Maximal value vector.
References getMaxValues, Owner.
Referenced by getMaxValues.
virtual double CBiteOptDeep::CBiteOptWrap::optcost(const double *const p)
Virtual function (objective function) that should calculate parameter vector's optimization cost. p Parameter vector to evaluate. Optimized cost.
References optcost, Owner.
Referenced by optcost.