CBiteSelBase
const int CBiteSelBase::SlotCount
The number of choice vectors in use.
Referenced by decr, reset, select.
int CBiteSelBase::Count
The number of choices in use.
Referenced by CBiteSelBase, getChoiceCount, reset.
int CBiteSelBase::SparseMul
Multiplier used to obtain an actual length of the choice vector. This multiplier replicates choices in the vector, increasing precision of the resulting PDF and its stability.
Referenced by reset.
int CBiteSelBase::CountSp
vector.
= Count * SparseMul. The actual length of the choice
Referenced by reset, select.
int CBiteSelBase::CountSp1
= CountSp - 1.
Referenced by decr, reset.
double CBiteSelBase::AccumCoeff
Slot score accumulator coefficient, depends on objective function's dimensions. Works as an "inertia" for the slot's score.
Referenced by decr, incr, reset.
double CBiteSelBase::SlotAccums[SlotCount][SlotCount]
Slot score accumulators.
Referenced by decr, incr, reset.
int* CBiteSelBase::Sels[SlotCount][SlotCount]
Choice vectors.
Referenced by decr, incr, reset, select.
int* CBiteSelBase::SelBuf
A singular buffer for Sels vectors.
Referenced by CBiteSelBase, reset, ~CBiteSelBase.
int CBiteSelBase::SelBufCapacity
Capacity of SelBuf.
Referenced by CBiteSelBase, reset.
int CBiteSelBase::Sel
select() function calls.
The latest selected choice. Available only after the
Referenced by decr, getSel, incr, select.
int CBiteSelBase::Selp
The index of the choice in the Sels vector.
Referenced by decr, incr, select.
int CBiteSelBase::Slot
The current Sels vector, depending on incr/decr.
Referenced by decr, incr, reset, select.
bool CBiteSelBase::IsSelected
"True" if selection was recently made.
Referenced by getIsSelected, reset, select, unsetIsSelected.
CBiteSelBase::CBiteSelBase(const int aCount)
Constructor. Count The number of possible choices, greater than 1.
References Count, SelBuf, SelBufCapacity.
Referenced by CBiteSel< tCount >::CBiteSel.
CBiteSelBase::~CBiteSelBase()
References SelBuf.
void CBiteSelBase::reset(CBiteRnd &rnd, const int ParamCount)
This function resets *this object, should be called before calling other functions, including after object's construction. rnd PRNG object. ParamCount The number of dimensions being optimized.
References AccumCoeff, Count, CountSp, CountSp1, CBiteRnd::getInt, IsSelected, SelBuf, SelBufCapacity, select, Sels, Slot, SlotAccums, SlotCount, SparseMul.
Referenced by examples.siemens.Plant.simulate.
int CBiteSelBase::getChoiceCount() const
An auxiliary function that returns choice count.
References Count.
void CBiteSelBase::incr(CBiteRnd &rnd, const double v=1.0)
This function should be called when a certain choice is successful. This function should only be called after a prior select() calls. rnd PRNG object. May not be used. v Selection increment value (success score), [0; 1].
References AccumCoeff, Sel, Selp, Sels, Slot, SlotAccums.
void CBiteSelBase::decr(CBiteRnd &rnd)
This function should be called when a certain choice is a failure. This function should only be called after a prior select() calls. rnd PRNG object. May not be used.
References AccumCoeff, CountSp1, Sel, Selp, Sels, Slot, SlotAccums, SlotCount.
int CBiteSelBase::select(CBiteRnd &rnd)
Function produces a random choice index based on the current *this object's state. Note that "select" functions can only be called once for a given *this object during the optimize() function call. rnd PRNG object.
References CountSp, CBiteRnd::getPowInt, IsSelected, Sel, Selp, Sels, Slot, SlotCount.
Referenced by reset.
int CBiteSelBase::getSel() const
Function returns the latest made choice index.
References Sel.
void CBiteSelBase::unsetIsSelected()
Function sets IsSelected value to "false".
References IsSelected.
bool CBiteSelBase::getIsSelected() const
Function returns "true" if the selection was made since the recent increment or decrement.
References IsSelected.