evaluator
Fitness* evaluator::_fit
Referenced by evaluator, execute.
int evaluator::_nobj
Referenced by evaluator, execute.
int evaluator::_workers
Referenced by evaluator, examples.maxcut.fcmaes_Optimizer.minimize.
bool evaluator::_stop
Referenced by evaluator, execute, join.
blocking_queue<vec_id*>* evaluator::_requests
Referenced by evaluate, evaluator, execute, join, ~evaluator.
blocking_queue<vec_id*>* evaluator::_evaled
Referenced by evaluator, execute, result, ~evaluator.
std::vector<evaluator_job> evaluator::_jobs
Referenced by evaluator, join.
time_point<Clock> evaluator::_t0
Referenced by quantumcomm.constellation_udp.construct_walkers, evaluator, examples.solo_mgar_udp.solo_mgar_udp.get_bounds.
evaluator::evaluator(Fitness *fit, int nobj, int workers)
References _evaled, _fit, _jobs, _nobj, _requests, _stop, _t0, _workers.
Referenced by evaluator::evaluator_job::evaluator_job.
evaluator::~evaluator()
References _evaled, _requests, join.
void evaluator::evaluate(vec &x, int id)
References _requests.
Referenced by acmaes::AcmaesOptimizer::do_optimize_delayed_update, differential_evolution::DeOptimizer::do_optimize_delayed_update.
vec_id * evaluator::result()
References _evaled.
Referenced by acmaes::AcmaesOptimizer::do_optimize_delayed_update, differential_evolution::DeOptimizer::do_optimize_delayed_update.
void evaluator::execute(int thread_id)
References _evaled, _fit, _nobj, _requests, _stop, vec_id::_v, constant.
Referenced by evaluator::evaluator_job::evaluator_job.
void evaluator::join()
References _jobs, _requests, _stop.
Referenced by ~evaluator.