dual_annealing::DARunner
int dual_annealing::DARunner::MAX_REINIT_COUNT
double dual_annealing::DARunner::temperature_start
Referenced by search.
double dual_annealing::DARunner::qv
Referenced by DARunner, search.
double dual_annealing::DARunner::qa
Referenced by DARunner.
bool dual_annealing::DARunner::use_local_search
Referenced by DARunner, search.
double dual_annealing::DARunner::maxsteps
Referenced by search.
double dual_annealing::DARunner::temperature_restart
Referenced by search.
Fitness* dual_annealing::DARunner::owf
Referenced by DARunner, search.
pcg64* dual_annealing::DARunner::rs
Referenced by DARunner, search, ~DARunner.
EnergyState* dual_annealing::DARunner::es
Referenced by bestX, bestY, DARunner, search, ~DARunner.
StrategyChain* dual_annealing::DARunner::sc
Referenced by DARunner, search, ~DARunner.
VisitingDistribution* dual_annealing::DARunner::vd
Referenced by DARunner, ~DARunner.
int dual_annealing::DARunner::iter
Referenced by search.
dual_annealing::DARunner::DARunner(Fitness *fun_, vec &x0_, long seed_, bool use_local_search_)
References es, owf, qa, qv, rs, sc, dual_annealing::sizeeexc, use_local_search, vd.
dual_annealing::DARunner::~DARunner()
References es, rs, sc, vd.
void dual_annealing::DARunner::search()
References dual_annealing::emptyVec, es, iter, maxsteps, owf, qv, rs, sc, temperature_restart, temperature_start, use_local_search.
Referenced by dual_annealing::minimize.
vec dual_annealing::DARunner::bestX()
References es.
Referenced by dual_annealing::minimize.
double dual_annealing::DARunner::bestY()
References es.
Referenced by dual_annealing::minimize.