pgpe::PGPEOptimizer
long pgpe::PGPEOptimizer::runid
Referenced by PGPEOptimizer.
Fitness* pgpe::PGPEOptimizer::fitfun
Referenced by ask_decode, getFitfun, PGPEOptimizer.
ADAM* pgpe::PGPEOptimizer::optimizer
Referenced by PGPEOptimizer, tell, ~PGPEOptimizer.
int pgpe::PGPEOptimizer::popsize
Referenced by ask, ask_decode, getPopsize, init, examples.benchmark_gtop_pygmo.Cma_pyg.minimize, examples.benchmark_gtop_pygmo.De_pyg.minimize, PGPEOptimizer, tell.
int pgpe::PGPEOptimizer::dim
Referenced by examples.damp.fitness.__call__, ask, getDim, init, anpcp.ANPCP.init_tsp, examples.siemens.Plant.next_product, examples.employee.problem.optimize, examples.employee.problem.optimize_mo, PGPEOptimizer, examples.damp.fitness.qd_fit, anpcp.ANPCP.random_x, anpcpc.ANPCPC.random_x.
int pgpe::PGPEOptimizer::maxEvaluations
Referenced by PGPEOptimizer.
double pgpe::PGPEOptimizer::keep
double pgpe::PGPEOptimizer::stopfitness
Referenced by PGPEOptimizer, tell.
int pgpe::PGPEOptimizer::iterations
Referenced by getIterations, PGPEOptimizer, tell.
double pgpe::PGPEOptimizer::bestY
Referenced by getBestValue, examples.noisy_tsp.TSP.optimize_mo, PGPEOptimizer, tell.
vec pgpe::PGPEOptimizer::bestX
Referenced by getBestX, examples.noisy_tsp.TSP.optimize_mo, tell.
int pgpe::PGPEOptimizer::stop
Referenced by getStop, PGPEOptimizer, tell.
pcg64* pgpe::PGPEOptimizer::rs
Referenced by ask, PGPEOptimizer, ~PGPEOptimizer.
mat pgpe::PGPEOptimizer::popX
Referenced by ask_decode, getPopulation, init, tell.
mat pgpe::PGPEOptimizer::scaled_noises
Referenced by ask, compute_reinforce_update, tell.
vec pgpe::PGPEOptimizer::popY
Referenced by init, tell.
vec pgpe::PGPEOptimizer::center
Referenced by ask, ask, ask_decode, PGPEOptimizer, tell.
vec pgpe::PGPEOptimizer::stdev
Referenced by ask, ask, ask_decode, compute_reinforce_update, PGPEOptimizer, tell, update_stdev.
vec pgpe::PGPEOptimizer::grad_center
Referenced by compute_reinforce_update, tell.
vec pgpe::PGPEOptimizer::grad_stdev
Referenced by compute_reinforce_update, tell.
bool pgpe::PGPEOptimizer::use_ranking
Referenced by PGPEOptimizer, process_scores.
int pgpe::PGPEOptimizer::lr_decay_steps
Referenced by PGPEOptimizer, tell.
double pgpe::PGPEOptimizer::center_learning_rate
double pgpe::PGPEOptimizer::stdev_learning_rate
Referenced by PGPEOptimizer, tell.
double pgpe::PGPEOptimizer::stdev_max_change
Referenced by PGPEOptimizer, tell.
pgpe::PGPEOptimizer::PGPEOptimizer(long runid_, Fitness *fitfun_, int dim_, int seed_, int popsize_, const vec &guess_, const vec &inputSigma_, int maxEvaluations_, double stopfitness_, int lr_decay_steps_, bool use_ranking_, double center_learning_rate_, double stdev_learning_rate_, double stdev_max_change_, double b1_, double b2_, double eps_, double decay_coef_)
References bestY, center, dim, fitfun, init, iterations, lr_decay_steps, maxEvaluations, optimizer, popsize, rs, runid, stdev, stdev_learning_rate, stdev_max_change, stop, stopfitness, use_ranking.
pgpe::PGPEOptimizer::~PGPEOptimizer()
References optimizer, rs.
vec pgpe::PGPEOptimizer::process_scores(const vec &ys)
References sort_index, use_ranking.
Referenced by tell.
void pgpe::PGPEOptimizer::compute_reinforce_update(const vec &fitness_scores, const mat &scaled_noises, const vec &stdev)
References constant, grad_center, grad_stdev, scaled_noises, stdev.
Referenced by tell.
vec pgpe::PGPEOptimizer::update_stdev(const vec &stdev, double lr, const vec &grad, double max_change)
References stdev.
Referenced by tell.
mat pgpe::PGPEOptimizer::ask(const vec &stdev, const vec &center)
References center, dim, normal, popsize, rs, scaled_noises, stdev.
mat pgpe::PGPEOptimizer::ask()
References ask, center, stdev.
Referenced by ask, ask_decode.
void pgpe::PGPEOptimizer::init()
References dim, popsize, popX, popY.
Referenced by PGPEOptimizer.
mat pgpe::PGPEOptimizer::ask_decode()
References ask, center, fitfun, popsize, popX, stdev.
int pgpe::PGPEOptimizer::tell(vec ys)
References bestX, bestY, center, compute_reinforce_update, grad_center, grad_stdev, iterations, lr_decay_steps, optimizer, popsize, popX, popY, process_scores, scaled_noises, stdev, stdev_learning_rate, stdev_max_change, stop, stopfitness, update_stdev.
mat pgpe::PGPEOptimizer::getPopulation()
References popX.
vec pgpe::PGPEOptimizer::getBestX()
References bestX.
double pgpe::PGPEOptimizer::getBestValue()
References bestY.
double pgpe::PGPEOptimizer::getIterations()
References iterations.
double pgpe::PGPEOptimizer::getStop()
References stop.
Fitness * pgpe::PGPEOptimizer::getFitfun()
References fitfun.
int pgpe::PGPEOptimizer::getDim()
References dim.
int pgpe::PGPEOptimizer::getPopsize()
References popsize.