daoptimizer.cpp
typedef Eigen::Matrix<double, Eigen::Dynamic, 1> vec
typedef Eigen::Matrix<int, Eigen::Dynamic, 1> ivec
typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mat
typedef double(* dual_annealing::callback_type) (int, const double *))(int, const double *)
uniform_real_distribution dual_annealing::distr_01
Referenced by dual_annealing::StrategyChain::accept_reject, dual_annealing::StrategyChain::local_search, dual_annealing::uniformVec, dual_annealing::VisitingDistribution::visiting.
normal_distribution dual_annealing::gauss_01
Referenced by dual_annealing::normalVec.
vec dual_annealing::emptyVec
Referenced by dual_annealing::DARunner::search.
dual_annealing::nanexception dual_annealing::naneexc
Referenced by dual_annealing::EnergyState::reset.
const double dual_annealing::BIG_VALUE
Referenced by dual_annealing::EnergyState::reset.
dual_annealing::sizeexception dual_annealing::sizeeexc
Referenced by dual_annealing::DARunner::DARunner.
static vec dual_annealing::zeros(int n)
Referenced by optimizeDA_C.
static Eigen::MatrixXd dual_annealing::normalVec(int dim, pcg64 &rs)
References dual_annealing::gauss_01.
Referenced by dual_annealing::EnergyState::reset, dual_annealing::VisitingDistribution::visit_fn.
static Eigen::MatrixXd dual_annealing::uniformVec(int dim, pcg64 &rs)
References dual_annealing::distr_01.
Referenced by dual_annealing::EnergyState::reset.
static vec dual_annealing::logv(vec v)
Referenced by dual_annealing::VisitingDistribution::visit_fn.
static vec dual_annealing::expv(vec v)
Referenced by dual_annealing::VisitingDistribution::visit_fn.
double dual_annealing::minLBFGS(Fitness *fitfun, vec &X0_, int maxIterations)
References LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize.
Referenced by dual_annealing::Fitness::local_search.
double dual_annealing::minimize(Fitness *fun, vec &x0, long seed, bool use_local_search, vec &X)
References dual_annealing::DARunner::bestX, dual_annealing::DARunner::bestY, dual_annealing::DARunner::search.
Referenced by optimizeDA_C.
void optimizeDA_C(long runid, callback_type func, int dim, int seed, double *init, double *lower, double *upper, int maxEvals, bool use_local_search, double *res)
References dual_annealing::Fitness::decode, dual_annealing::Fitness::encode, dual_annealing::Fitness::getEvaluations, dual_annealing::minimize, dual_annealing::zeros.