evaluator.h
EIGEN_VECTORIZE_SSE2
using Clock = std::chrono::steady_clock
typedef Eigen::Matrix<double, Eigen::Dynamic, 1> vec
typedef Eigen::Matrix<int, Eigen::Dynamic, 1> ivec
typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mat
typedef Eigen::Matrix<int, Eigen::Dynamic, Eigen::Dynamic> imat
typedef bool(* callback_type) (int, const double *, double *))(int, const double *, double *)
typedef void(* callback_parallel) (int, int, double *, double *))(int, int, double *, double *)
std::uniform_real_distribution distr_01
Referenced by rand01, randInt, differential_evolution::DeOptimizer::rnd01, differential_evolution::DeOptimizer::rndInt, Fitness::sample_i, Fitness::sample_i, uniform, uniformVec.
std::normal_distribution gauss_01
Referenced by normal, normalVec, normreal.
static bool noop_callback(int popsize, const double *x, double *y)
Referenced by initACMA_C, initCRFMNES_C, initDE_C, initMODE_C, initPGPE_C, optimizeCRFMNES_C, optimizePGPE_C.
static void noop_callback_par(int popsize, int dim, double *x, double *y)
Referenced by initACMA_C, initCRFMNES_C, initDE_C, initMODE_C, initPGPE_C, optimizeBite_C, optimizeDE_C.
static Eigen::MatrixXd normal(int dx, int dy, pcg64 &rs)
References gauss_01.
Referenced by fcmaes.de.DE._sample, fcmaes.mode.MODE._sample, crmfnes::CrfmnesOptimizer::ask, pgpe::PGPEOptimizer::ask, acmaes::AcmaesOptimizer::ask_all, examples.rover.RoverDomain.set_params, acmaes::AcmaesOptimizer::tell.
static Eigen::MatrixXd normalVec(int dim, pcg64 &rs)
References gauss_01.
Referenced by acmaes::AcmaesOptimizer::ask, crmfnes::CrfmnesOptimizer::CrfmnesOptimizer, normalVec, differential_evolution::DeOptimizer::sample.
static Eigen::MatrixXd uniform(int dx, int dy, pcg64 &rs)
References distr_01.
Referenced by fcmaes.de.DE._modifier, fcmaes.mode.MODE._modifier, fcmaes.pygmoretry._retry_loop, fcmaes.de.DE._sample, fcmaes.mode.MODE._sample, fcmaes.advretry.Store.crossover, fcmaes.advretry.Store.limits.
static Eigen::MatrixXd uniformVec(int dim, pcg64 &rs)
References distr_01.
Referenced by Fitness::sample, Fitness::sample, mode_optimizer::MoDeOptimizer::variation.
static double rand01(pcg64 &rs)
References distr_01.
Referenced by mode_optimizer::MoDeOptimizer::modify, mode_optimizer::MoDeOptimizer::nextX, mode_optimizer::MoDeOptimizer::variation.
static int randInt(pcg64 &rs, int max)
References distr_01.
Referenced by mode_optimizer::MoDeOptimizer::nextX.
static double normreal(pcg64 &rs, double mu, double sdev)
References gauss_01.
Referenced by differential_evolution::DeOptimizer::sample_i.
static vec normalVec(const vec &mean, const vec &sdev, int dim, pcg64 &rs)
References normalVec.
static vec zeros(int n)
Referenced by acmaes::AcmaesOptimizer::AcmaesOptimizer, pgpe::ADAM::ADAM, crmfnes::CrfmnesOptimizer::CrfmnesOptimizer, mode_optimizer::MoDeOptimizer::crowd_dist, differential_evolution::DeOptimizer::init, mode_optimizer::MoDeOptimizer::pareto, mode_optimizer::MoDeOptimizer::pareto_levels, mode_optimizer::MoDeOptimizer::ranks, crmfnes::CrfmnesOptimizer::tell, Fitness::violations.
static mat zeros(int n, int m)
static vec constant(int n, double val)
Referenced by pgpe::ADAM::ADAM, pgpe::PGPEOptimizer::compute_reinforce_update, crmfnes::CrfmnesOptimizer::CrfmnesOptimizer, evaluator::execute, mode_optimizer::MoDeOptimizer::init, crmfnes::CrfmnesOptimizer::tell, pgpe::ADAM::update.
static mat constant(int n, int m, double val)
static bool compareIndexVal(IndexVal i1, IndexVal i2)
References IndexVal::val.
Referenced by sort_index.
static ivec sort_index(const vec &x)
References compareIndexVal, IndexVal::index, IndexVal::val.
Referenced by mode_optimizer::MoDeOptimizer::crowd_dist, mode_optimizer::MoDeOptimizer::objranks, mode_optimizer::MoDeOptimizer::pareto, mode_optimizer::MoDeOptimizer::pop_update, pgpe::PGPEOptimizer::process_scores, mode_optimizer::MoDeOptimizer::ranks, crmfnes::CrfmnesOptimizer::sort_indices_by, acmaes::AcmaesOptimizer::updateCMA, acmaes::AcmaesOptimizer::updateCovariance.
static int index_min(vec &v)