house.py
examples::house.stdout
examples::house.format
examples::house.level
examples::house.train_dataset
examples::house.test_dataset
list examples::house.categorical_features
list examples::house::every_column_except_y
list examples::house::every_column_non_categorical
examples::house.numeric_feats
list examples::house.features_with_nan
examples::house.model
examples::house.weighted_features
examples::house.ordered_features
examples::house.most_relevant_features
examples::house.axis
examples::house.inplace
examples::house.train_x
examples::house.train_y
bool examples::house.grid_search
bool examples::house.hyperopt
bool examples::house.bayesian
bool examples::house.evolutionary
dict examples::house.parameters_for_testing
examples::house.xgb_model
examples::house.gsearch
list examples::house.xgb_space
examples::house.best
list examples::house.bds
examples::house.optimizer
examples::house.max_iter
examples::house.y_bo
examples::house.bounds
examples::house.problem
examples::house.ret
examples.house.ConverNaNToNAString(data, columnList)
References examples.house.ConverNaNToNAString.
Referenced by examples.house.ConverNaNToNAString.
examples.house.cv_score(X)
Referenced by examples.house.obj_f, examples.house.obj_fmin.
examples.house.obj_f(X)
References examples.house.cv_score.
examples.house.obj_fmin(X)
References examples.house.cv_score.