mapelites.py
fcmaes::mapelites.rng
Archive fcmaes.mapelites.optimize_map_elites(Callable[[ArrayLike], Tuple[float, np.ndarray]] qd_fitness, Bounds bounds, Bounds qd_bounds, Optional[int] niche_num=4000, Optional[int] samples_per_niche=20, Optional[int] workers=mp.cpu_count(), Optional[int] iterations=100, Optional[Archive] archive=None, Optional[Dict] me_params={}, Optional[Dict] cma_params={}, Optional[bool] use_stats=False)
Optimizes a map-elites evolutionary algorithm to find diverse and high-performing solutions by distributing samples into niches, iteratively evolving them, and maintaining an archive to store the found solutions.
This function leverages a map-elites approach to optimize solutions across a given feature space or behavioral space defined by the qd_bounds parameter. The objective of the optimization is to populate an archive with solutions that exhibit high fitness while ensuring diversity in behavior across the space. The archive is continuously updated and sorted during the iterations to reflect the best solutions in each niche. The performance is monitored throughout the optimization process. qd_fitness (Callable[[ArrayLike], Tuple[float, np.ndarray]]): The quantitative fitness function used to evaluate the solutions. It must return a tuple containing the fitness score and the corresponding feature descriptor/behavior representation. bounds Represents the variable bounds for the optimization space. qd_bounds Defines the range of the quality-diversity feature/behavioral space. niche_num The total number of niches in the archive. Determines how the solutions will be distributed across the feature space. Defaults to 4000. samples_per_niche The number of samples generated per niche during initialization. Defaults to 20. workers Number of CPU workers/threads to parallelize the process. Defaults to the number of CPUs available. iterations The total number of iterations to evolve the archive. Defaults to 100. archive Pre-existing archive object for storing solutions. If None, a new archive is initialized. Defaults to None. me_params Additional hyperparameters specific to the map-elites algorithm. Defaults to an empty dictionary. cma_params Hyperparameters specific to the CMA-ES algorithm used for evolutionary strategies. Defaults to an empty dictionary. use_stats Flag to determine whether statistical data should be collected and maintained in the archive. Defaults to False. Archive The final archive containing diverse high-performing solutions distributed across the quality-diversity space.
References fcmaes.mapelites.optimize_map_elites_.
Archive fcmaes.mapelites.empty_archive(int dim, Bounds qd_bounds, int niche_num, int samples_per_niche, Optional[bool] use_stats=False)
Creates and initializes an archive for quality diversity (QD) experiments.
This function creates an Archive object with the specified dimensions, bounding box, number of niches, and optionally enables statistics collection. It also initializes the niches in the archive with a specified number of samples per niche. dim Dimensionality of the search/grid space for the archive. qd_bounds Bounds specifying the range for niche space coordinates. niche_num Number of niches to be created in the archive. samples_per_niche Number of samples to initialize in each niche. use_stats (Optional[bool], optional): If True, statistics collection will be enabled in the archive. Defaults to False. Archive The initialized archive object for QD experiments.
fcmaes.mapelites.set_KDTree(Archive archive, Optional[np.ndarray] centers=None, Optional[int] niche_num=None, Optional[Bounds] qd_bounds=None, Optional[int] samples_per_niche=100)
Sets up a KDTree for the given archive using specified or default parameters.
This function initializes a KDTree structure with the given or generated centers, enabling efficient spatial searches within the archive. If the centers are not provided, they will be generated using the get_centers_ function based on the number of niches, dimensionality of the bounds, and the number of samples per niche. This KDTree is essential for spatial partitioning and querying in the archive. archive The archive object for which the KDTree will be set up. centers Coordinates of the centers to construct the KDTree. If None, they will be generated automatically. niche_num The number of niches used to determine the grid of centers if centers is not provided. qd_bounds The bounds within which the niches lie. samples_per_niche The number of sample centers per niche to generate when centers is not provided. Defaults to 100.
References fcmaes.mapelites.get_centers_.
Referenced by fcmaes.mapelites.Archive.load.
Archive fcmaes.mapelites.load_archive(str name, Bounds bounds, Bounds qd_bounds, Optional[int] niche_num=10000, Optional[bool] use_stats=False)
Loads an archive based on the provided parameters.
This function creates and configures an Archive instance using the specified parameters. It initializes the Archive with bounds, QD bounds, niche number, and optional usage of statistics. After initialization, it loads the archive data from the provided file name. name The file name from which to load the archive. bounds The lower and upper bounds for the archive's dimensionality. qd_bounds The bounds specific to the QD optimization process. niche_num The number of niches in the archive. Defaults to 10000. use_stats Flag to indicate whether statistics should be used. Defaults to False. Archive An Archive instance loaded with the specified configurations and data.
fcmaes.mapelites.optimize_map_elites_(archive, fitness, bounds, workers, me_params, cma_params)
Optimize a solution using Map-Elites algorithm via multi-processing.
This function orchestrates the execution of the Map-Elites optimization algorithm over multiple processes. Each process operates independently with its own random generator to explore the solution space. It uses CMA-ES to update solutions iteratively. The provided parameters configure the optimization behavior, such as the solution archive, fitness evaluation function, search bounds, and process settings specific to Map-Elites and CMA-ES. archive A data structure to store the solutions found during the optimization process and their corresponding evaluation. fitness A callable function that evaluates the quality of a solution. bounds A sequence of tuples defining the lower and upper bounds for each decision variable. workers An integer specifying the number of parallel processes to run during optimization. me_params A dictionary or configuration object with parameters for the Map-Elites algorithm. cma_params A dictionary or configuration object with parameters for the Covariance Matrix Adaptation Evolution Strategy (CMA-ES).
Referenced by fcmaes.mapelites.optimize_map_elites.
fcmaes.mapelites.run_map_elites_(archive, fitness, bounds, rg, me_params, cma_params)
Runs the MAP-Elites algorithm with optional SBX (Simulated Binary Crossover) or iso+line variation, followed by CMA-ES optimization.
The algorithm iteratively updates the archive with new solutions, balancing exploration and exploitation over the specified number of generations. archive An archive object for storing solutions, descriptors, and their fitness values, supporting niche identification and updating mechanisms. fitness Callable that computes the fitness and descriptor of a given solution. bounds Bounds object holding the lower and upper bounds for the solutions during variation and optimization. rg A random generator instance used for stochastic operations within the algorithm. me_params Dictionary containing tunable MAP-Elites parameters with keys such as 'generations', 'chunk_size', 'use_sbx', 'dis_c', 'dis_m', 'iso_sigma', and 'line_sigma'. cma_params Dictionary containing CMA-ES-specific parameters such as 'cma_generations'.
References fcmaes.mapelites.iso_dd_, fcmaes.mapelites.optimize_cma_, fcmaes.mapelites.variation_.
fcmaes.mapelites.optimize_cma_(archive, fitness, bounds, rg, cma_params)
Optimizes a solution using the Covariance Matrix Adaptation Evolution Strategy (CMA-ES).
The function utilizes the process of evolutionary optimization based on objective fitness, adaptive step size, and population-based approach. It leverages a provided archive to introduce variations in the space of potential solutions. archive An instance of a solution archive storing previously evaluated solutions and assisting in generating new candidate solutions. fitness A callable fitness function to evaluate the quality of solutions. bounds The bounds or constraints of the solution space to limit candidate solutions. rg A random generator instance used to introduce stochasticity in optimization steps. cma_params A dictionary containing configuration parameters for the CMA-ES optimizer, such as population size, sigma (step size), maximum iterations, and other hyperparameters. ValueError If parameters in cma_params are invalid (e.g., negative population size).
References fcmaes.mapelites.update_archive.
Referenced by fcmaes.mapelites.run_map_elites_.
fcmaes.mapelites.update_archive(Archive archive, np.ndarray xs, Optional[Callable[[ArrayLike], Tuple[float, np.ndarray]]] fitness=None, Optional[ArrayLike] yds=None)
Evaluates a population, updates the archive with new solutions, and determines rankings.
This function processes a set of solutions and their associated descriptions or fitness evaluations. The solutions are compared against an archive to determine and store better solutions. It prioritizes updates to empty niches in the archive and normalizes improvements for comparisons. The function finally returns the improvement values and the real fitness values for the solutions. archive The archive object where solutions and corresponding fitness data are stored. xs A set of solutions to be evaluated and compared against the archive. fitness (Optional[Callable[[ArrayLike], Tuple[float, np.ndarray]]]): A callable function that evaluates a solution and returns its fitness value and description. yds Precomputed fitness values and descriptions, if available. Tuple[np.ndarray, np.ndarray]: A tuple containing: Improvement values compared to archive elite solutions. The real fitness values evaluated for the given solutions. ValueError If `ys` or `yds` contain invalid or mismatched content.
Referenced by fcmaes.mapelites.optimize_cma_.
fcmaes.mapelites.get_grid_indices(ds, capacity, lb, ub)
Computes and returns grid indices for a dataset based on the provided grid capacity, lower, and upper bounds.
Each point in the dataset is normalized and then converted into a grid index using the specified parameters. ds Input dataset (2D numpy array) where each row is a point in a multi-dimensional space. capacity Total number of grid cells (capacity of the grid). lb Lower bounds of the dataset in each dimension. ub Upper bounds of the dataset in each dimension. np An array of grid indices, where each index corresponds to a point in the input dataset.
Referenced by fcmaes.mapelites.Archive.index_of_niches.
fcmaes.mapelites.variation_(pop, lower, upper, rg, dis_c=20, dis_m=20)
Referenced by fcmaes.mapelites.run_map_elites_.
fcmaes.mapelites.iso_dd_(x1, x2, lower, upper, rg, iso_sigma=0.01, line_sigma=0.2)
Generates isotropic deviation data within specified bounds.
This function creates a variation of the input data x1 influenced by Gaussian noise parameters for isotropic and line deviations. The result is clipped to remain within the range defined by the lower and upper bounds. x1 The primary input array for generating isotropic deviation data. x2 The secondary input array influencing line deviation calculation. lower The lower bound for clipping the resulting data. upper The upper bound for clipping the resulting data. rg Random generator object used for generating Gaussian noise. iso_sigma Standard deviation of the isotropic Gaussian noise. Defaults to 0.01. line_sigma Standard deviation of the line Gaussian noise. Defaults to 0.2. ndarray The processed array with isotropic and line deviations applied and bounded by the given limits.
Referenced by fcmaes.mapelites.run_map_elites_.
fcmaes.mapelites.get_centers_(niche_num, dim, samples_per_niche)
Determines and returns the centers of niches in a defined space using k-means clustering.
If the data is cached, it loads the cached centers for faster access. Otherwise, it computes the centers by applying k-means clustering on randomly generated samples and caches the result for future use. niche_num Number of niches or clusters to determine centers for. dim Dimensionality of the space where the niches are located. samples_per_niche Number of samples used per niche to compute the centers. numpy An array representing the determined centers of the niches.
Referenced by fcmaes.mapelites.set_KDTree.