fcmaes::retry
dict fcmaes::retry.dtype_map
OptimizeResult fcmaes.retry.minimize(Callable[[ArrayLike], float] fun, Bounds bounds, Optional[float] value_limit=np.inf, Optional[int] num_retries=1024, Optional[int] workers=mp.cpu_count(), Optional[int] popsize=31, Optional[int] max_evaluations=50000, Optional[int] capacity=500, Optional[float] stop_fitness=-np.inf, Optional[Optimizer] optimizer=None, Optional[int] statistic_num=0)
Minimizes a given objective function using the specified optimizer and stores the progress.
This function attempts to find the minimum value of a given function within the bounds provided. It incorporates retry logic to handle multiple optimization attempts in case of failure or suboptimal results. The optimization process can also operate in a multiprocess environment with a configurable number of workers. Additionally, progress data is stored to analyze statistical results throughout the optimization. fun The objective function to minimize. The function must accept an array-like input and return a scalar float as the function value. bounds Bounds for the input variables of the objective function. Defines the acceptable search space during optimization. value_limit Upper limit for the acceptable function value. Defaults to infinity. After reaching this limit, retries are triggered if configured. num_retries Number of times the optimization process should be retried upon failure or suboptimal results. Defaults to 1024. workers The number of parallel workers to use for optimization. Defaults to the number of CPU cores available. popsize Population size for the optimization process. Determines the number of potential solutions considered at each iteration. max_evaluations The maximum number of evaluations allowed in the optimization process. This is a hard limit on computational effort. capacity The storage capacity for retaining past evaluation results or progress data. Used for analyzing statistics or performance. stop_fitness The target fitness value for stopping the optimization. When a result meets or exceeds this fitness value, the process terminates. Defaults to negative infinity. optimizer An optimization algorithm instance to drive the optimization process. If not provided, a default optimizer is created based on de_cma. statistic_num The statistical metric number to associate with the optimization data. Used for tracking or analyzing statistical trends. OptimizeResult The result of the optimization process, including details about the optimal solution, number of function evaluations, and success status.
Referenced by quantumcomm.reduce.
OptimizeResult fcmaes.retry.retry(Store store, Callable optimize, int num_retries, Optional[float] value_limit=np.inf, Optional[int] workers=mp.cpu_count(), Optional[float] stop_fitness=-np.inf)
Retries optimization multiple times using the specified number of worker processes.
Each worker conducts optimization in parallel and contributes to the shared results store. After all workers complete their tasks, the stored results are sorted, persisted, and the best result is returned. store A shared result store object that collects optimization results from all workers. optimize A callable function that performs the optimization for a single run. num_retries The number of retries/iterations each worker should perform. value_limit The upper limit for objective values to consider valid. Defaults to positive infinity. workers The number of worker processes to spawn for parallel optimization. Defaults to the number of CPU cores available. stop_fitness The fitness value at which the optimization can early stop. Defaults to negative infinity. OptimizeResult An object containing the best solution found, its objective value, number of function evaluations, and a success status.
OptimizeResult fcmaes.retry.minimize_plot(str name, Optimizer optimizer, Callable[[ArrayLike], float] fun, Bounds bounds, Optional[float] value_limit=np.inf, Optional[float] plot_limit=np.inf, Optional[int] num_retries=1024, Optional[int] workers=mp.cpu_count(), Optional[float] stop_fitness=-np.inf, Optional[int] statistic_num=5000)
Minimizes an optimization problem and plots the improvement process while storing results.
name A string serving as the descriptive name or title for the optimization process. optimizer An instance of the Optimizer class used for carrying out the optimization. fun A callable that represents the objective function to minimize, which takes an array-like input and returns a float value. bounds An instance of the Bounds class specifying the valid range for the optimization. value_limit Optional float indicating the upper limit for significant improvements. Defaults to positive infinity. plot_limit Optional float representing the limit for including improvements in the plot. Defaults to positive infinity. num_retries Optional integer specifying the maximum number of retries for the optimization process. Defaults to 1024. workers Optional integer indicating the number of multiprocessing workers to run the optimization. Defaults to the number of available CPU cores. stop_fitness Optional float defining the fitness value at which to stop the optimization early if achieved. Defaults to negative infinity. statistic_num Optional integer indicating the number of most recent statistics to retain in memory. Defaults to 5000. OptimizeResult The result object generated by the optimizer containing information on the solution, including the best parameters found and associated fitness value.
References fcmaes.retry.plot.
fcmaes.retry.plot(ArrayLike front, str fname, Optional[bool] interp=True, Optional[str] label=r '$\chi$', Optional[str] xlabel=r ' $f_1$', Optional[str] ylabel=r ' $f_2$', Optional[str] zlabel=r ' $f_3$', Optional[bool] plot3d=False, s=1, dpi=300)
Plots a given front using either 2D or 3D visualization, with options for interpolation and customization of the appearance and labels.
If the input front has one or more objectives, it chooses the appropriate plotting method based on dimensionality, adds interpolated lines if specified, and saves the resulting figure to a file. front Array-like structure representing the input data points. Each row corresponds to a point, and each column represents a dimension (objective value). fname str. Path and name of the file where the plot will be saved. interp Optional[bool]. Enables interpolation to smooth the 2D plot lines. Default is True. label Optional[str]. Label for the data points on the plot. Default is r'$\chi$'. xlabel Optional[str]. Label for the x-axis. Default is r'$f_1$'. ylabel Optional[str]. Label for the y-axis. Default is r'$f_2$'. zlabel Optional[str]. Label for the z-axis. Used only for 3D plots. Default is r'$f_3$'. plot3d Optional[bool]. If True and the front has 3 dimensions, generates a 3D scatter plot. Default is False. s Plot marker size for scatter points. Default is 1. dpi Resolution of the saved plot in dots per inch. Default is 300.
References fcmaes.retry.plot, fcmaes.retry.plot3.
Referenced by fcmaes.retry.minimize_plot, fcmaes.retry.plot.
fcmaes.retry.plot3(ArrayLike front, str fname, Optional[str] label=r '$\chi$', Optional[str] xlabel=r ' $f_1$', Optional[str] ylabel=r ' $f_2$', Optional[str] zlabel=r ' $f_3$')
Creates and saves a 3D scatter plot from given data.
This function generates a 3D scatter plot with labeled axes using the data provided in a 2D array-like object. The plot is saved to the specified file with high resolution. The labels for each axis and the plot can be customized. front A 2D array-like object containing the data points to plot. It should have exactly three columns corresponding to the x, y, and z coordinates. fname The file name where the generated plot should be saved. label The label for the scatter plot. Defaults to r'$\chi$'. xlabel The label for the x-axis. Defaults to r'$f_1$'. ylabel The label for the y-axis. Defaults to r'$f_2$'. zlabel The label for the z-axis. Defaults to r'$f_3$'.
Referenced by fcmaes.retry.plot.
fcmaes.retry._retry_loop(pid, rgs, store, optimize, num_retries, value_limit, stop_fitness=-np.inf)
fcmaes.retry._convertBounds(bounds)
Convert bounds to a pair of arrays representing lower and upper limits.
This function processes the given bounds and converts them into two arrays that represent the lower and upper bounds, respectively. The bounds argument must either be an instance of the Bounds class or a sequence of real valued (min, max) pairs for each variable. ValueError If `bounds` is None. ValueError If `bounds` is not an instance of `Bounds` or a valid sequence of (min, max) pairs. ValueError If size or values within the `bounds` are not finite real values. bounds The bounds to process, either as an instance of the Bounds class or a sequence of real valued (min, max) pairs for each variable. Tuple[np.ndarray, np.ndarray]: A tuple containing two arrays. The first array represents the lower limits, and the second represents the upper limits.