gtoc12
gtoc12.stdout
gtoc12.format
gtoc12.level
int gtoc12.MIN_MJD
int gtoc12.MAX_MJD
gtoc12.max_evals
gtoc12.num_restarts
gtoc12._mined(asteroids, epochs)
Referenced by optimize.
gtoc12._reduce(ast_num, ast_used, sequence0)
Referenced by optimize.
gtoc12._transfer(a2, epoch_min, transfers, idx)
Referenced by gtoc12.Transfers.get_transfer.
gtoc12.optimize(fname, max_evals=200000, num_restarts=32, seq=None)
References _mined, _reduce.
Referenced by check_solutions.
gtoc12.check_solutions()
References check_solutions, optimize.
Referenced by check_solutions.