examples::tdesign
examples::tdesign.stdout
examples::tdesign.format
examples::tdesign.level
examples::tdesign.legacy
examples::tdesign.N
examples::tdesign.l_max
examples::tdesign.max_evals
examples.tdesign.cartesian_to_spherical(points)
Referenced by examples.tdesign.optimize_weighted.
examples.tdesign.spherical_to_cartesian(theta, phi)
Referenced by examples.tdesign.visualize_points.
examples.tdesign.x_to_points(x)
Referenced by examples.tdesign.optimize_weighted, examples.tdesign.show_results.
examples.tdesign.normalize_weights_to_average_one(weights)
Referenced by examples.tdesign.visualize_points, examples.tdesign.weighted_spherical_harmonics.
examples.tdesign.fibonacci_sphere(N)
Referenced by examples.tdesign.optimize_weighted.
examples.tdesign.real_spherical_harmonics(l_max, theta, phi)
Compute fully normalized real spherical harmonics up to degree l_max using scipy.special.lpmv.
The real spherical harmonics are defined by: For m = 0: Y_{l,0}(\theta,phi) = N_{l0} * P_l^0(cos(theta)) For m > 0: Y_{l,m}(\theta,phi) = sqrt(2)*N_{lm} * P_l^m(cos(theta)) * cos(m*phi) Y_{l,-m}(\theta,phi)= sqrt(2)*N_{lm} * P_l^m(cos(theta)) * sin(m*phi) where the normalization factor is: N_{lm} = (-1)^m * sqrt((2*l+1)/(4*pi) * (l-m)!/(l+m)!) Parametersl_max int Maximum degree of spherical harmonics. theta array_like Polar angles (in radians), shape (N,). phi array_like Azimuthal angles (in radians), shape (N,). ReturnsY dict A dictionary with keys (l, m) where l = 0,...,l_max and m = -l,...,l. Each entry is a NumPy array of shape (N,) containing the value of the corresponding spherical harmonic.
Referenced by examples.tdesign.symmetry, examples.tdesign.weighted_spherical_harmonics.
examples.tdesign.weighted_spherical_harmonics(l_max, theta, phi, weights)
Given l_max: maximum spherical-harmonic degree, theta, phi: arrays of length N with the spherical angles of your points, weights: array of length N with the corresponding weights w_i, compute the 'integral' (weighted sum) of each spherical harmonic: I[l,m] = sum_i( w_i * Y_{l,m}(theta_i, phi_i) ). Returns a dict integrals[(l,m)] = floating-point result.
References examples.tdesign.normalize_weights_to_average_one, examples.tdesign.real_spherical_harmonics.
Referenced by examples.tdesign.symmetry.
examples.tdesign.symmetry_error(Y, N, l_max)
For each degree l from 0 to l_max, compute the sum over m of the square of the (pointwise) sums of the spherical harmonic values.
Then multiply by 4*pi/(N^2). ParametersY dict mapping (l, m) -> array of shape (N,) N int, number of points l_max maximum degree s numpy array of shape (l_max+1,)
Referenced by examples.tdesign.symmetry.
examples.tdesign.symmetry(pts, l_max, weights=None)
Compute a symmetry measure for a set of points.
pts has 2 columns, it is assumed to be [theta, phi]; An array of length l_max+1.
References examples.tdesign.real_spherical_harmonics, examples.tdesign.symmetry_error, examples.tdesign.weighted_spherical_harmonics.
Referenced by examples.tdesign.t_design_error, examples.tdesign.visualize_points.
examples.tdesign.t_design_error(points, l_max, weights=None)
References examples.tdesign.symmetry.
Referenced by examples.tdesign.optimize_weighted.
examples.tdesign.visualize_points(points, l_max, weights=None)
Visualize points on the unit sphere.
Each point in 'points' should be a tuple: (theta, phi) or -(theta,phi,weight) where theta is in [0, pi] and phi is in [0, 2*pi]. If weight is not provided, all points are assumed to have equal weight. autotoc_md30Parameters points list or array-like A list of points in spherical coordinates.
References examples.tdesign.normalize_weights_to_average_one, examples.tdesign.spherical_to_cartesian, examples.tdesign.symmetry.
Referenced by examples.tdesign.optimize_weighted, examples.tdesign.show_results.
examples.tdesign.optimize_weighted(N, l_max, workers=20, max_evals=150000, max_iters=1)
References examples.tdesign.cartesian_to_spherical, examples.tdesign.fibonacci_sphere, examples.tdesign.t_design_error, examples.tdesign.visualize_points, examples.tdesign.x_to_points.
examples.tdesign.show_results(N, l_max)
References examples.tdesign.visualize_points, examples.tdesign.x_to_points.