fcmaes::evaluator
int fcmaes::evaluator.pipe_limit
fcmaes::evaluator.basepath
fcmaes::evaluator.libcmalib
fcmaes::evaluator.mo_call_back_type
fcmaes::evaluator.call_back_type
fcmaes::evaluator.call_back_par
fcmaes.evaluator.is_log_level_active(level)
Determines if the specified log level is currently active.
This function checks whether the provided logging level is active by iterating through the logger handlers and comparing their level settings. level The logging level to check. bool True if the specified logging level is active, otherwise False.
Referenced by fcmaes.evaluator.is_debug_active, fcmaes.evaluator.is_trace_active.
fcmaes.evaluator.is_debug_active()
Determines if the debug log level is currently active.
This function checks whether the "DEBUG" log level is active by invoking the is_log_level_active function with the "DEBUG" string as an argument. It is useful for determining if debug-level logging is enabled in the application. bool True if the "DEBUG" log level is active, False otherwise.
References fcmaes.evaluator.is_log_level_active.
fcmaes.evaluator.is_trace_active()
Checks if the TRACE log level is currently active.
This function determines whether the TRACE level of logging is enabled, typically indicating if detailed debug information should be logged. bool True if the TRACE log level is active, False otherwise.
References fcmaes.evaluator.is_log_level_active.
fcmaes.evaluator.eval_parallel(ArrayLike xs, Evaluator evaluator)
Evaluates a set of inputs in parallel using a provided evaluator function.
This function processes a sequence of elements in chunks, using a custom evaluator. It supports efficiently evaluating large data by dividing the inputs into smaller segments and processing them iteratively in a pipeline. xs Array-like collection of inputs to be evaluated. evaluator An evaluator callable or function responsible for computing the results of the inputs provided. np Array containing the evaluation results corresponding to the input elements.
References fcmaes.evaluator._eval_parallel_segment.
Referenced by fcmaes.evaluator.parallel.__call__.
fcmaes.evaluator.eval_parallel_mo(ArrayLike xs, Evaluator evaluator, int nobj)
Evaluates a population of solutions in parallel for a multi-objective optimization problem.
This function takes a population of solutions and evaluates them in parallel to compute objective values. It is designed to handle large populations by dividing them into segments and processing each segment iteratively. The computed objective values are returned in a 2-dimensional array. xs The input population of solutions to evaluate. Each solution should be represented as an array-like structure. evaluator The evaluator object that computes objective values for the given solutions. nobj The number of objectives being evaluated. np A 2-dimensional array where each row corresponds to the computed objective values of a solution in the input population.
References fcmaes.evaluator._eval_parallel_segment.
Referenced by fcmaes.evaluator.parallel_mo.__call__.
fcmaes.evaluator._eval_parallel_segment(xs, ys, i0, i1, evaluator)
Evaluates a segment of data in parallel by sending and receiving data through a pipe.
This function processes a segment of input data specified by the indices i0 and i1 using the evaluator's pipeline. It sends values from the input xs to the evaluator, and receives processed results to update the output ys. xs A sequence of input data to be evaluated. ys A sequence to store the results after evaluation. i0 The starting index of the segment to be processed (inclusive). i1 The ending index of the segment to be processed (exclusive). evaluator An object with a communication pipe for parallel processing. The updated ys sequence containing the evaluated results.
Referenced by fcmaes.evaluator.eval_parallel, fcmaes.evaluator.eval_parallel_mo.
fcmaes.evaluator._evaluate(fun, pipe, read_mutex, write_mutex)
Execute a given function on inputs received from a communication pipe in a thread-safe manner and send results back through the pipe.
Handles potential exceptions during function execution and ensures proper synchronization using the provided mutex locks. fun Function to be executed on input data received from the pipe. pipe (Tuple[Connection, Connection]): A pair of connection objects for inter-process communication, used for receiving inputs and sending results. read_mutex A threading lock ensuring safe reading from the input pipe. write_mutex A threading lock ensuring safe writing to the output pipe.
fcmaes.evaluator._check_bounds(bounds, guess, rg)
Checks and processes bounds, guesses, and random generator inputs for optimization.
This function ensures that either bounds or guesses are properly defined, as they are necessary to perform any optimization task. If bounds is not provided, but guess is, it returns a processed version of the guess. If bounds is provided but guess is absent, it generates a random guess within the bounds using the provided random generator. Ultimately, it arranges and returns bounds and guesses as numpy arrays. bounds Object containing lower (lb) and upper (ub) bounds. Can be None if guess is provided directly. guess Initial guess of the parameters. Can be None if bounds are provided. rg A random number generator instance used to generate guesses when they are not explicitly provided. Tuple containing: Lower bounds array (numpy.ndarray) or None if bounds are not provided. Upper bounds array (numpy.ndarray) or None if bounds are not provided. Guess array (numpy.ndarray) processed from the provided inputs. ValueError If both bounds and guess are None.
fcmaes.evaluator._get_bounds(dim, bounds, guess, rg)
Configures and validates bounds, initial guesses, and dimensionality for a process.
This function processes and ensures the compatibility of dimensionality, bounds, and guesses for an optimization or computational routine. It also generates default values where absent, ensuring all return values align with the given inputs. dim Dimensionality of the problem. bounds The lower and upper bounds for each dimension. guess Initial guess for the optimization variable(s). rg Random number generator used for generating uniformly distributed guesses if guess is not provided. Tuple[Optional[np.ndarray], Optional[np.ndarray], np.ndarray]: A tuple containing the processed lower bounds, upper bounds, and initial guess. Returns (None, None, guess) when bounds is not specified.
fcmaes.evaluator.serial(fun)
Creates a function that applies a given function to each element in a list.
This decorator takes a function as input and returns a new function. The returned function, when called with a list of elements, applies the input function to each element in the list sequentially. If the input function fails for an element, the resulting behavior is handled by an internal mechanism. fun The function to be applied to each element in a list. A new function that takes a list of elements and applies 'fun' to each element, returning a list of results.
References fcmaes.evaluator._tryfun.
fcmaes.evaluator._func_serial(fun, num, pid, xs, ys)
Applies a function to elements of a list in a serial manner based on a processing strategy using process ID and total number of processes.
This function modifies the ys list in place, applying the fun function to elements in xs at specific indices determined by the process ID (pid) and total number of processes (num). It ensures elements are processed in a distributed order across processes. fun Callable function to apply to elements of the input list. num int. Total number of processes. pid int. Process ID, indicating the current process index starting at 0. xs list. Input list of elements to process. ys list. Output list where results are stored at corresponding indices.
References fcmaes.evaluator._tryfun.
fcmaes.evaluator._tryfun(fun, x)
Attempts to evaluate the specified function with a given input and handle errors gracefully.
If the result is a finite value, it is returned. Otherwise, or if the evaluation raises an exception, the maximum floating-point value is returned. fun A callable that represents the function to be evaluated. x The input value passed to the function for evaluation. The result of the function evaluation if it produces a finite value. Otherwise, returns the maximum floating-point value.
Referenced by fcmaes.evaluator._func_serial, fcmaes.evaluator.serial.