fcmaes::journal
fcmaes.journal.message_to_json(message)
Converts a given message object to its JSON representation.
This function serializes a message object based on its type. If the message type is Trial_param, its distribution field is serialized as a JSON string before converting the entire object to JSON format. For other message types, the object is directly converted to JSON format. message The message object to be serialized to JSON. str A JSON string representation of the message.
Referenced by fcmaes.journal.study_start, fcmaes.journal.trial_param, fcmaes.journal.trial_start, fcmaes.journal.trial_value.
fcmaes.journal.distribution(low, high)
Generates a JSON representation of a float distribution within a specified range.
The function creates a JSON object representing a uniform float distribution with specified lower and upper bounds. The resulting JSON is parsed and returned as a Python dictionary. low The lower bound of the distribution range. high The upper bound of the distribution range. dict A dictionary representation of the float distribution.
Referenced by fcmaes.journal.trial_param.
fcmaes.journal.study_start(worker_id, study_name, dir)
Creates and returns a JSON representation of a study start message.
This function builds a study start message using provided worker identification, study name, and study directions. If the dir parameter is scalar, it is converted into a list; otherwise, it is used as is. The message is then serialized into a JSON string for further communication or processing. worker_id Unique identifier for the worker initiating the study. study_name Name of the study being started. dir (Union[str, List[str]]): Direction(s) for the study. Can be a single direction (string) or a list of directions. str JSON-encoded representation of the constructed study start message.
References fcmaes.journal.message_to_json.
Referenced by fcmaes.journal.Journal.study.
fcmaes.journal.trial_param(worker_id, trial_id, param_name, param_value_internal, low, high)
Generates a JSON message containing trial parameter details.
This function creates a message using the given trial parameters and returns its JSON representation. The message contains information such as worker ID, trial ID, parameter name, internal parameter value, and the specified distribution range. worker_id The unique identifier for the worker. trial_id The unique identifier for the trial. param_name The name of the parameter. param_value_internal The internal value of the parameter to be passed. low The lower bound of the parameter's range. high The upper bound of the parameter's range. str A JSON-formatted string with the details of the trial parameter.
References fcmaes.journal.distribution, fcmaes.journal.message_to_json.
Referenced by fcmaes.journal.Journal.param, fcmaes.journal.journal_wrapper.store_x.
fcmaes.journal.trial_start(worker_id, study_id)
Starts a trial by recording the worker ID, study ID, and the current timestamp, and generates a JSON message representation of the trial start event.
worker_id Unique identifier for the worker initiating the trial. study_id Unique identifier for the study related to the trial. str JSON representation of the trial start event.
References fcmaes.journal.message_to_json.
Referenced by fcmaes.journal.journal_wrapper.store_start, fcmaes.journal.Journal.trial.
fcmaes.journal.trial_value(worker_id, trial_id, y)
Creates and returns a JSON representation of a trial value message.
The function generates a message object for a specific trial and worker, incorporating information about the trial's state, its values, and a timestamp indicating when the operation was completed. It converts the message to a JSON format before returning. worker_id Identifier for the worker responsible for the trial. trial_id Identifier for the specific trial whose value is being processed. y (Union[float, list[float]]): Numeric value(s) associated with the trial. This can be a scalar value or a list of values. str JSON string representation of the trial value message.
References fcmaes.journal.message_to_json.
Referenced by fcmaes.journal.journal_wrapper.store_y, fcmaes.journal.Journal.value.