examples::yahpo
examples::yahpo.stdout
examples::yahpo.format
examples::yahpo.level
examples.yahpo.opt_ranger_hardware(task_id, max_evals=100000)
References examples.yahpo.evaluate_ranger_, examples.yahpo.plot.
Referenced by examples.yahpo.plot.
examples.yahpo.opt_ranger_interpretability(task_id, max_evals=100000)
References examples.yahpo.evaluate_ranger_, examples.yahpo.plot.
Referenced by examples.yahpo.plot.
examples.yahpo.opt_xgboost(task_id, max_evals=100000)
References examples.yahpo.evaluate_xgboost_, examples.yahpo.plot.
Referenced by examples.yahpo.plot.
examples.yahpo.evaluate_ranger_(x, features, params, bench, task_id, lower, upper, trafo=True)
References examples.yahpo.retrafo_.
Referenced by examples.yahpo.opt_ranger_hardware, examples.yahpo.opt_ranger_interpretability.
examples.yahpo.evaluate_xgboost_(x, features, params, bench, task_id, lower, upper, trafo=True)
References examples.yahpo.retrafo_.
Referenced by examples.yahpo.opt_xgboost.
examples.yahpo.retrafo_(z, lower, upper)
Referenced by examples.yahpo.evaluate_ranger_, examples.yahpo.evaluate_xgboost_.
examples.yahpo.plot3d(ys, name, xlabel='', ylabel='', zlabel='')
Referenced by examples.yahpo.plot.
examples.yahpo.plot(archive, name)
References examples.yahpo.opt_ranger_hardware, examples.yahpo.opt_ranger_interpretability, examples.yahpo.opt_xgboost, examples.yahpo.plot3d.
Referenced by examples.yahpo.opt_ranger_hardware, examples.yahpo.opt_ranger_interpretability, examples.yahpo.opt_xgboost.