examples::crypto
examples::crypto.stdout
examples::crypto.format
Referenced by examples.crypto.fitness.fun.
examples::crypto.level
float examples::crypto.START_CASH
examples::crypto.bounds
int examples::crypto.ddim
examples::crypto.qd_bounds
int examples::crypto.niche_num
list examples::crypto.tickers
str examples::crypto.start
str examples::crypto.end
examples.crypto.get_history(ticker, start, end)
examples.crypto.get_ema(prices, period)
Referenced by examples.crypto.simulate.
examples.crypto.get_sma(prices, period)
Referenced by examples.crypto.simulate.
examples.crypto.buy_all(cash, num_coins, price, date, logs)
Referenced by examples.crypto.hodl, examples.crypto.strategy.
examples.crypto.sell_all(cash, num_coins, price, date, logs)
Referenced by examples.crypto.hodl, examples.crypto.strategy.
examples.crypto.hodl(close, start_cash)
References examples.crypto.buy_all, examples.crypto.sell_all.
Referenced by examples.crypto.strategy.
examples.crypto.strategy(close, start_cash, ema, sma, wait_buy, wait_sell, dates)
References examples.crypto.buy_all, examples.crypto.hodl, examples.crypto.sell_all.
Referenced by examples.crypto.simulate.
examples.crypto.simulate(prices, ema_period, sma_period, wait_buy, wait_sell, dates=None)
References examples.crypto.get_ema, examples.crypto.get_sma, examples.crypto.strategy.
Referenced by examples.crypto.fitness.fun, examples.crypto.fitness.get_trades.
examples.crypto.optimize(tickers, start, end)
examples.crypto.optimize_mo(tickers, start, end, nsga_update=True)
examples.crypto.bar(tickers, start, end)
examples.crypto.optimize_nd(tickers, start, end)