dual_annealing
typedef double(* dual_annealing::callback_type) (int, const double *))(int, const double *)
uniform_real_distribution dual_annealing::distr_01
Referenced by dual_annealing::StrategyChain::accept_reject, dual_annealing::StrategyChain::local_search, uniformVec, dual_annealing::VisitingDistribution::visiting.
normal_distribution dual_annealing::gauss_01
Referenced by normalVec.
vec dual_annealing::emptyVec
Referenced by dual_annealing::DARunner::search.
dual_annealing::nanexception dual_annealing::naneexc
Referenced by dual_annealing::EnergyState::reset.
const double dual_annealing::BIG_VALUE
Referenced by dual_annealing::EnergyState::reset.
dual_annealing::sizeexception dual_annealing::sizeeexc
Referenced by dual_annealing::DARunner::DARunner.
static vec dual_annealing::zeros(int n)
Referenced by optimizeDA_C.
static Eigen::MatrixXd dual_annealing::normalVec(int dim, pcg64 &rs)
References gauss_01.
Referenced by dual_annealing::EnergyState::reset, dual_annealing::VisitingDistribution::visit_fn.
static Eigen::MatrixXd dual_annealing::uniformVec(int dim, pcg64 &rs)
References distr_01.
Referenced by dual_annealing::EnergyState::reset.
static vec dual_annealing::logv(vec v)
Referenced by dual_annealing::VisitingDistribution::visit_fn.
static vec dual_annealing::expv(vec v)
Referenced by dual_annealing::VisitingDistribution::visit_fn.
double dual_annealing::minLBFGS(Fitness *fitfun, vec &X0_, int maxIterations)
References LBFGSpp::LBFGSBSolver< Scalar, LineSearch >::minimize.
Referenced by dual_annealing::Fitness::local_search.
double dual_annealing::minimize(Fitness *fun, vec &x0, long seed, bool use_local_search, vec &X)
References dual_annealing::DARunner::bestX, dual_annealing::DARunner::bestY, dual_annealing::DARunner::search.
Referenced by optimizeDA_C.