examples::elitescass2
examples::elitescass2.stdout
examples::elitescass2.format
examples::elitescass2.level
int examples::elitescass2.niche_num
examples.elitescass2.plot3d(ys, name, xlabel='', ylabel='', zlabel='')
Referenced by examples.elitescass2.plot_archive.
examples.elitescass2.plot_archive(archive, max_dv=20)
References examples.elitescass2.plot3d.
Referenced by examples.elitescass2.plot, examples.elitescass2.run_diversifier, examples.elitescass2.run_map_elites.
examples.elitescass2.tof(x)
Referenced by examples.elitescass2.Cassini2_me.descriptors, examples.elitescass2.Cassini2_me.qd_fitness.
examples.elitescass2.launch(x)
Referenced by examples.elitescass2.Cassini2_me.descriptors, examples.elitescass2.Cassini2_me.qd_fitness.
examples.elitescass2.cma_elite(problem, archive, num=300)
applies CMA-ES to the best num niches
examples.elitescass2.plot(name)
References examples.elitescass2.plot_archive.
examples.elitescass2.run_diversifier()
References examples.elitescass2.plot_archive.
Referenced by examples.elitescass2.run_map_elites.
examples.elitescass2.run_map_elites()
References examples.elitescass2.plot_archive, examples.elitescass2.run_diversifier.