examples::routing
examples::routing.stdout
examples::routing.format
examples::routing.level
str examples::routing.filename
int examples::routing.capacity
int examples::routing.popsize
int examples::routing.max_evaluations
examples.routing.fitness_(seq, distance, demands, capacity)
Referenced by examples.routing.Routing.fitness, examples.routing.Routing.fitness_capacity, examples.routing.Routing.fitness_so.
examples.routing.parse(filename)
examples.routing.optimize(filename, capacity, popsize, max_evaluations)
examples.routing.optimize_capacity(filename, popsize, max_evaluations, num_retries=640)
examples.routing.optimize_so(filename, capacity, opt, num_retries=320)
examples.routing.dump(filename, capacity, seq)