fcmaes::moretry
Tuple[np.ndarray, np.ndarray] fcmaes.moretry.minimize(Callable[[ArrayLike], float] fun, Bounds bounds, Bounds weight_bounds, Optional[int] ncon=0, Optional[float] value_exp=2.0, Optional[ArrayLike] value_limits=None, Optional[int] num_retries=1024, Optional[int] workers=mp.cpu_count(), Optional[int] popsize=31, Optional[int] max_evaluations=50000, Optional[int] capacity=None, Optional[Optimizer] optimizer=None, Optional[int] statistic_num=0, Optional[str] plot_name=None)
Minimization of a multi objective function of one or more variables using parallel optimization retry.
Parametersfun callable The objective function to be minimized. fun(x) -> float where x is an 1-D array with shape (n,) bounds sequence or Bounds, optional Bounds on variables. There are two ways to specify the bounds: Instance of the scipy.Bounds class. Sequence of (min, max) pairs for each element in x. None is used to specify no bound. weight_bounds Bounds, optional Bounds on objective weights. ncon int, optional number of constraints value_exp float, optional exponent applied to the objective values for the weighted sum. value_limits sequence of floats, optional Upper limit for optimized objective values to be stored. num_retries int, optional Number of optimization retries. workers int, optional number of parallel processes used. Default is mp.cpu_count() popsize=int,optional CMA-ES population size used for all CMA-ES runs. Not used for differential evolution. Ignored if parameter optimizer is defined. max_evaluations int, optional Forced termination of all optimization runs after max_evaluations function evaluations. Only used if optimizer is undefined, otherwise this setting is defined in the optimizer. capacity int, optional capacity of the evaluation store. optimizer optimizer.Optimizer, optional optimizer to use. Default is a sequence of differential evolution and CMA-ES. plot_name plot_name, optional if defined the pareto front is plotted during the optimization to monitor progress Returnsxs, ys: list of argument vectors and corresponding value vectors of the optimization results.
References fcmaes.moretry.mo_retry.
Referenced by fcmaes.moretry.minimize_plot.
fcmaes.moretry.mo_retry(Callable[[ArrayLike], float] fun, Bounds weight_bounds, int ncon, float y_exp, store, Callable optimize, int num_retries, ArrayLike value_limits, Optional[int] workers=mp.cpu_count())
Executes a multi-objective optimization with retry functionality by distributing work across multiple processes.
This function performs optimization by spawning multiple processes, each executing a retry loop targeting a specific optimizer and constraints. The retries ensure robustness against failures or subpar outcomes in individual optimization attempts across the workers. fun (Callable[[ArrayLike], float]): The objective function to optimize. It must accept an input vector and return a scalar cost or objective value. weight_bounds Bounds for the weights, defining constraints on the optimization variables. ncon Number of constraints to enforce during the optimization process. y_exp The expected value used as a threshold or benchmark for optimization outcomes. store An object for storing and managing results during optimization. Must support sort and dump methods, among others. optimize Optimization function or solver to be used within the retry loop. It must be callable and compatible with the function and constraints provided. num_retries The number of retries per process, ensuring multiple attempts for robust optimization results. value_limits Array-like structure specifying the acceptable limits for values during optimization. workers Number of processes to spawn for parallel optimization. Defaults to the total available CPU count. xs_view A view or representation of the sorted results stored in the store after the optimization process is complete.
Referenced by fcmaes.moretry.minimize.
fcmaes.moretry._retry_loop(pid, rgs, fun, weight_bounds, ncon, y_exp, store, optimize, num_retries, value_limits)
Executes a retry loop strategy for multi-objective optimization.
This process includes generating random weights, scaling them to match constraints, optimizing the given function, and storing the results if they meet specific criteria. Additionally, it may generate and save plots of results for visualization. pid Process ID to identify and manage the random state specific to the process. rgs List of random number generators associated with each process. fun The function to be optimized in the retry loop. weight_bounds The lower and upper bounds for the weights used for scaling in the optimization process. ncon The number of constraints to account for during the optimization process. y_exp Exponent used to adjust the scaling of weights in the optimization process. store Instance of a class responsible for managing optimization results and storing data. optimize Optimization function that evaluates the objective or constraints based on inputs. num_retries The number of retries allowed for achieving a successful optimization result. value_limits Optional limits enforced on the objective values from the optimization results. If None, no objective value constraints are applied.
References fcmaes.moretry._avg_exp, fcmaes.moretry.plot.
fcmaes.moretry.pareto(np.ndarray xs, np.ndarray ys)
Filter and sort elements based on Pareto efficiency.
This function calculates the Pareto front for the provided arrays, xs and ys. The Pareto front contains elements that are not dominated by any other element in the dataset. The function returns the filtered and sorted elements that belong to the Pareto front sorted by the values in the associated ys array. xs A NumPy array representing the input data values. The xs array contains the attributes aligned with ys. ys A NumPy array indicating the criteria or objectives that the Pareto efficiency is calculated upon. A tuple containing two NumPy arrays: A filtered and sorted array of elements from xs corresponding to the Pareto front. A filtered and sorted array of elements from ys corresponding to the Pareto front.
References fcmaes.moretry._pareto.
Referenced by fcmaes.moretry.adv_minimize_plot, fcmaes.moretry.plot.
fcmaes.moretry.minimize_plot(str name, Optimizer optimizer, Callable[[ArrayLike], float] fun, Bounds bounds, weight_bounds, Optional[int] ncon=0, Optional[ArrayLike] value_limits=None, Optional[int] num_retries=1024, Optional[float] exp=2.0, Optional[int] workers=mp.cpu_count(), statistic_num=0, plot_name=None)
Minimizes a given function using a specified optimizer and plots the results.
This function performs optimization on a target function within the specified bounds and additional constraints. The results of the optimization, including inputs and outputs, are saved to a compressed file, and a plot is generated to visualize the optimization results. name The base name for the output files and plots. optimizer The optimization algorithm to be used. fun (Callable[[ArrayLike], float]): The target function to minimize. bounds The bounds within which the optimization is performed. weight_bounds Constraints on weight values for optimization. ncon The number of constraints in optimization. Defaults to 0. value_limits Limits for input values in the optimization process. Defaults to None. num_retries Number of retries for optimization in case of failure or randomness. Defaults to 1024. exp Exponent for value weighting during optimization. Defaults to 2.0. workers Number of parallel workers used during optimization. Defaults to the number of CPU cores available. statistic_num Statistical parameter to control optimization behavior. plot_name Custom name for the output plot.
References fcmaes.moretry.minimize, fcmaes.moretry.plot.
fcmaes.moretry.plot(name, ncon, xs, ys, eps=1E-2, all=True, interp=False, plot3d=False)
Plots the feasible solution space and Pareto front for a given set of data points.
This function processes data points and constraints to determine the feasible region and subsequently calculates the Pareto-optimal front. It can also generate visualizations of all solutions and the Pareto front if required. name The name for the visualization files. ncon The number of constraint functions. xs A collection of decision variable values. ys A collection of corresponding objective function values. eps Tolerance value for feasibility conditions. Default is 1E-2. all Flag to indicate if plotting all solutions is required. Default is True. interp Flag to determine if interpolation is applied to the Pareto front plot. Default is False. plot3d Flag indicating whether to create a 3D Pareto front plot. Default is False. Exception If an error occurs during computation or plotting.
References fcmaes.moretry.pareto.
Referenced by fcmaes.moretry._retry_loop, fcmaes.moretry.minimize_plot.
fcmaes.moretry.adv_minimize_plot(str name, Optimizer optimizer, Callable[[ArrayLike], float] fun, Optional[Bounds] bounds, Optional[float] value_limit=np.inf, Optional[int] num_retries=1024, Optional[int] statistic_num=0)
Minimizes a given function using the provided optimizer, retries for better results, plots the outcomes, and saves the results.
This function performs a smart optimization by leveraging retry strategies to achieve better outcomes. It evaluates the function over all inputs after optimization, generates convergence plots, and computes a Pareto front, saving the associated data and visuals. name The base name for the output files generated during the optimization process. optimizer The optimization algorithm to be used for minimizing the function. fun (Callable[[ArrayLike], float]): The objective function to minimize. It should accept an input array-like variable and return a float score. bounds Bounds for the optimization process. Defines the variable limits for the optimization. value_limit A threshold to terminate the optimization early when the function's value is below this limit. Default is infinity. num_retries The number of retries for optimization to improve results when the process fails or is suboptimal. Default is 1024. statistic_num A statistic counter for internal use during optimizationorretries.Defaultis0.
References fcmaes.moretry.pareto.
fcmaes.moretry._avg_exp(y, y_exp)
Calculates the generalized mean (also known as the power mean) of a list of numbers.
This function computes a weighted generalized mean of a list of numbers y using the specified exponent y_exp. The calculation involves summing the power of each element in the list to the given exponent and then applying the inverse of the same exponent to the resulting sum. y List or iterable of numbers for which the generalized mean will be calculated. y_exp Exponent parameter to control the type of mean (e.g., arithmetic, geometric). Weighted generalized mean computed from the input list based on the provided exponent.
Referenced by fcmaes.moretry._retry_loop, fcmaes.moretry.mo_wrapper.eval.
fcmaes.moretry._pareto_values(ys)
Determines the Pareto-optimal solutions from a given set of objective values.
The function processes a given 2D array of objective values and identifies the Pareto-optimal points among them. Pareto-optimal solutions are those that cannot be dominated by any other solutions in all objectives. ys A 2D array where each row represents a solution, and each column corresponds to an objective. numpy A 2D array containing only the Pareto-optimal solutions from the input.
fcmaes.moretry._pareto(ys)
Identifies the Pareto-optimal points from the given set of points.
Pareto-optimal points are those for which no other point dominates them. A point dominates another if it is less than or equal to the other point in all dimensions and strictly less in at least one dimension. This function removes dominated points from the dataset iteratively. ys A 2D array where each row represents a point in a multidimensional space, and each column corresponds to a dimension. np An array of indices representing the Pareto-optimal points in the provided dataset.
Referenced by fcmaes.moretry.pareto.