examples::cassini_minlp
examples::cassini_minlp.stdout
examples::cassini_minlp.format
examples::cassini_minlp.level
examples.cassini_minlp.test_optimizer(opt, problem, num_retries=120000, num=100, value_limit=10.0)
examples.cassini_minlp.sequences()
Referenced by examples.cassini_minlp.test_multiretry.
examples.cassini_minlp.test_multiretry(retries_inc=128, keep=0.7, optimizer=de_cma(1500), repeat=50)
References examples.cassini_minlp.sequences.
Referenced by examples.cassini_minlp.main.
examples.cassini_minlp.main()
References examples.cassini_minlp.main, examples.cassini_minlp.test_multiretry.
Referenced by examples.cassini_minlp.main.