fcmaes::mode
Tuple[np.ndarray, np.ndarray] fcmaes.mode.minimize(Callable[[ArrayLike], ArrayLike] mofun, int nobj, int ncon, Bounds bounds, Optional[np.ndarray] guess=None, Optional[int] popsize=64, Optional[int] max_evaluations=100000, Optional[int] workers=1, Optional[float] f=0.5, Optional[float] cr=0.9, Optional[float] pro_c=0.5, Optional[float] dis_c=15.0, Optional[float] pro_m=0.9, Optional[float] dis_m=20.0, Optional[bool] nsga_update=True, Optional[int] pareto_update=0, Optional[ArrayLike] ints=None, Callable modifier=None, Optional[float] min_mutate=0.1, Optional[float] max_mutate=0.5, Optional[Generator] rg=Generator(PCG64DXSM()), Optional[store] store=None)
Minimizes a multi-objective function subject to constraints and bounds using evolutionary algorithms.
The function supports parallel computation and allows various configurations to modify the optimization process. mofun (Callable[[ArrayLike], ArrayLike]): A callable representing the multi-objective function to minimize. It must take an array-like input and return an array-like output. nobj The number of objective functions. ncon The number of constraints. bounds The bounds for the decision variables. guess Initial guess for the population. If not provided, a random guess will be generated. popsize The size of the population for the evolutionary algorithm. max_evaluations The maximum number of allowable function evaluations during the optimization process. workers The number of workers to use for parallel computation. A value of 1 indicates serial computation. f Differential evolution scale factor. cr Differential evolution crossover probability. pro_c Crossover probability for simulated binary crossover (SBX). dis_c Distribution index for simulated binary crossover (SBX). pro_m Mutation probability for polynomial mutation. dis_m Distribution index for polynomial mutation. nsga_update Flag to enable or disable NSGA-II style updates. pareto_update The frequency of Pareto front updates. ints Specific indices of decision variables that are treated as integers. modifier A callable that modifies the process of variable updates. This can be used to apply additional constraints or actions during the optimization process. min_mutate Minimum mutation factor for decision variables. max_mutate Maximum mutation factor for decision variables. rg An instance of random number generator to ensure repeatability. store An optional storage object to store results at the end of optimization. Tuple[np.ndarray, np.ndarray]: A tuple containing the optimal decision variables (x) and the corresponding objective function values (y). If optimization fails, returns (None, None).
Referenced by fcmaes.mode.minimize_plot.
fcmaes.mode._check_bounds(bounds, dim)
fcmaes.mode._filter(x, y)
Filters and sorts input arrays based on specific conditions.
This function processes two input arrays x and y. It first determines the maximum value along the first axis of y, sorts both arrays based on this criterion, and then applies additional filtering conditions on y to exclude specific rows. x The input array to be processed and filtered. y A 2D array whose maximum values along the first axis determine the sorting order, and which is filtered according to additional conditions. A tuple containing: The filtered and sorted version of the input array x. The filtered and sorted version of the array y.
fcmaes.mode.objranks(objs)
Computes the rank of objects based on their sum of ranks across all columns.
The function calculates the rank of each object in each column, then sums these ranks across the columns to produce a single rank value for each object. objs A 2-dimensional numpy array where each row represents an object, and each column represents a category or feature. numpy A 1-dimensional numpy array containing the computed rank for each object based on the sum of its ranks across all columns.
Referenced by fcmaes.mode.pareto_domination.
fcmaes.mode.ranks(cons, feasible, eps)
Computes the ranks of constraint values, adjusted by their feasibility and scaled by the fraction of violations for each constraint.
cons A 2D array of constraint values where rows represent different samples and columns represent different constraints. feasible A 1D boolean array indicating whether each row (sample) in cons is feasible (True) or not (False). eps A scalar threshold value used to determine the violation of constraints. numpy A 1D array that contains the computed rank for each sample in cons.
Referenced by fcmaes.mode.pareto_domination.
fcmaes.mode.get_valid(xs, ys, nobj)
Filters the input data based on a validity condition and returns the valid elements.
xs Array-like structure containing input data. ys Array-like structure, typically associated with xs, used for the validity check. nobj Integer specifying the number of columns to skip in ys for the validity check. Tuple containing: The filtered elements of xs that satisfy the validity condition. The filtered elements of ys that align with the valid xs.
fcmaes.mode.pareto_sort(x0, y0, nobj, ncon)
Sorts solutions based on Pareto dominance and crowding distance.
This function sorts a given set of solutions into levels based on Pareto dominance. Within each level, solutions are further sorted by crowding distance to ensure diversity. The input arrays x0 and y0 are reordered accordingly, and the resulting sorted arrays are returned. x0 Array-like structure representing the original decision variables of the solutions. y0 Array-like structure representing the objectives of the solutions. nobj Integer specifying the number of objectives for each solution. ncon Integer specifying the number of constraints for each solution. Tuple of two NumPy arrays: The reordered x0 array based on Pareto dominance and crowding distance. The reordered y0 array based on Pareto dominance and crowding distance.
References fcmaes.mode.crowd_dist, fcmaes.mode.pareto_domination.
fcmaes.mode.pareto_domination(ys, nobj, ncon, last_ycon=None, last_eps=0)
Determines Pareto domination levels for a set of solutions considering objectives and constraint violations.
Divides solutions into feasible and infeasible sets, calculates their dominance levels based on objectives and constraints, and returns the relevant rankings. ys (list or np.ndarray): A list or array of solutions where each solution contains concatenated values of objectives and constraints. nobj Number of objectives in each solution. ncon Number of constraints in each solution. last_ycon (np.ndarray, optional): Array representing constraint violations used in the previous iteration for adjusting tolerance to small violations. Defaults to None. last_eps (float, optional): Tolerance level for constraint violations in the last iteration. Defaults to 0. tuple A tuple containing: np.ndarray: Array of Pareto domination levels for all solutions. np.ndarray: Array of adjusted constraint violations for each solution. float: Adjusted tolerance for constraint violations. None
References fcmaes.mode.objranks, fcmaes.mode.pareto_levels, fcmaes.mode.ranks.
Referenced by fcmaes.mode.pareto_sort, fcmaes.mode.MODE.pop_update.
fcmaes.mode.pareto_levels(ys)
Determines the Pareto levels of a given set of points.
This function identifies the domination levels of a set of points, where the domination level of a point represents the number of other points dominating it. Domination is determined based on whether one point strictly dominates another in all dimensions. ys A 2D array where each row represents a point in a multi-dimensional space, and domination is evaluated across dimensions. numpy A 1D array where each index corresponds to the domination level of the respective point in the input array.
Referenced by fcmaes.mode.pareto_domination.
fcmaes.mode.crowd_dist(y)
Calculates the crowding distance for the first objective in a multi-objective optimization problem.
This function determines for each solution how dense the neighborhood is based on the distances to its nearest neighbors in the sorted objective space. It assigns a numerical value to each solution reflecting this crowding distance. y A list of solutions, where each solution is represented as a list of objective values. This function specifically uses the first objective value for the crowding distance calculation. numpy An array of crowding distances for each solution in the input.
Referenced by fcmaes.mode.pareto_sort, fcmaes.mode.MODE.pop_update.
fcmaes.mode.variation(pop, lower, upper, rg, pro_c=1, dis_c=20, pro_m=1, dis_m=20)
Applies genetic variation operations, including simulated binary crossover (SBX) and polynomial mutation, on a population to produce offspring.
The method modifies the population based on crossover and mutation probabilities, as well as distribution control parameters. pop numpy.ndarray Input population array, where each row represents an individual and each column represents a design variable. lower numpy.ndarray Lower bounds for each design variable. upper numpy.ndarray Upper bounds for each design variable. rg numpy.random.Generator Random number generator instance. pro_c float, optional Probability of performing crossover, default is 1. dis_c float, optional Distribution index for crossover, default is 20. pro_m float, optional Probability of performing mutation, default is 1. dis_m float, optional Distribution index for mutation, default is 20. numpy.ndarray Modified population (offspring) after applying crossover and mutation operations.
Referenced by fcmaes.mode.MODE.pop_update.
fcmaes.mode.feasible(xs, ys, ncon, eps=1E-2)
Determines feasible solutions based on constraints and filters the input arrays xs and ys accordingly.
It evaluates constraint violations and ensures that violations are below the threshold (eps) for feasibility. xs Input array of solutions. ys Array of objective and constraint values corresponding to the solutions in xs. ncon Number of constraints. Constraints are assumed to be the last ncon columns of the ys array. eps (float, optional): Feasibility threshold. Defaults to 1E-2. Tuple[np.ndarray, np.ndarray]: Filtered solutions (xs) and their corresponding objective values (ys), with infeasible solutions removed.
fcmaes.mode.is_feasible(y, nobj, eps=1E-2)
Determines if a given solution is feasible based on constraints and tolerance.
This function evaluates feasibility by checking whether the sum of violated constraints (if any) is less than the provided tolerance value. If there are no constraints, the solution is automatically considered feasible. y List or array-like containing values of both objectives and constraints. nobj Integer specifying the number of objectives in the array 'y'. The rest are treated as constraints. eps Float representing the tolerance level for determining feasibility. Defaults to 1E-2. bool True if the solution is feasible (i.e., sum of violated constraints is below the specified tolerance), otherwise False.
Referenced by fcmaes.mode.wrapper.__call__.
Tuple[np.ndarray, np.ndarray] fcmaes.mode.minimize_plot(str name, Callable[[ArrayLike], ArrayLike] fun, int nobj, int ncon, Bounds bounds, Optional[int] popsize=64, Optional[int] max_evaluations=100000, Optional[bool] nsga_update=True, Optional[int] pareto_update=0, Optional[ArrayLike] ints=None, Optional[int] workers=mp.cpu_count())
References fcmaes.mode.minimize.