examples::solo_mgar_udp
examples::solo_mgar_udp.bval
examples::solo_mgar_udp.stdout
examples::solo_mgar_udp.format
examples::solo_mgar_udp.level
examples.solo_mgar_udp._dv_mga(pl1, pl2, tof, max_revs, rvt_outs, rvt_ins, rvt_pls, dvs, lps=None)
Referenced by examples.solo_mgar_udp.solo_mgar_udp._compute_dvs.
examples.solo_mgar_udp.compute_resonance(pl, resonances, beta, safe_distance, used_resos, reso_dts, rvt_outs, rvt_ins, rvt_pls, dvs, resos=None)
Referenced by examples.solo_mgar_udp.solo_mgar_udp._compute_dvs.
examples.solo_mgar_udp._angle(v1, v2)
Referenced by examples.solo_mgar_udp.solo_mgar_udp.pretty.