examples::siemens
examples::siemens.stdout
examples::siemens.format
examples::siemens.level
int examples::siemens.buffer_capacity
int examples::siemens.setup_time
examples::siemens.dtime_orig
examples::siemens.dtime_2
examples.siemens.simulate(plant)
examples.siemens.optimize_de(plant)
examples.siemens.optimize_bite(plant)
References examples.siemens.plot3d.
Referenced by examples.siemens.main.
examples.siemens.plot3d(store, name, xlabel='batch1', ylabel='batch2', zlabel='number')
Referenced by examples.siemens.optimize_bite.
examples.siemens.main()
References examples.siemens.main, examples.siemens.optimize_bite.
Referenced by examples.siemens.main.