acmaes
static ivec acmaes::inverse(const ivec &indices)
References inverse.
Referenced by inverse, acmaes::AcmaesOptimizer::updateCovariance.
static vec acmaes::sequence(double start, double end, double step)
Referenced by acmaes::AcmaesOptimizer::AcmaesOptimizer.