predict
predict.stdout
predict.format
predict.level
predict.r(v, n=3)
Referenced by find_harris_estimate_eps, find_other_model, find_other_model_eps, rl.
predict.rl(l, n=3)
References r.
Referenced by find_harris_estimate_eps, find_other_model, find_other_model_eps.
predict.is_false(s)
Referenced by read_data.
predict.read_data(fname)
References is_false.
Referenced by collect_all_data.
predict.collect_all_data()
References read_data.
Referenced by test_harris_estimate_eps, test_harris_prediciton, test_harris_prediciton_eps.
predict.fit(n, props, inc_is_winner, x)
predict.find_other_model(data, harris_predict=True)
References r, rl.
Referenced by test_harris_prediciton.
predict.test_harris_prediciton()
References collect_all_data, find_other_model.
Referenced by test_harris_estimate_eps.
predict.fit_eps(n, props, inc_is_winner, x)
predict.find_other_model_eps(data, harris_predict=True)
References r, rl.
Referenced by test_harris_prediciton_eps.
predict.test_harris_prediciton_eps()
References collect_all_data, find_other_model_eps.
Referenced by test_harris_estimate_eps.
predict.single_sum(n, single_props, weights)
predict.find_harris_estimate_eps(data)
References r, rl.
Referenced by test_harris_estimate_eps.
predict.test_harris_estimate_eps()
References collect_all_data, find_harris_estimate_eps, test_harris_estimate_eps, test_harris_prediciton, test_harris_prediciton_eps.
Referenced by test_harris_estimate_eps.