fcmaes::diversifier
Archive fcmaes.diversifier.minimize(Callable[[ArrayLike], Tuple[float, np.ndarray]] qd_fitness, Bounds bounds, Bounds qd_bounds, Optional[int] niche_num=10000, Optional[int] samples_per_niche=20, Optional[int] max_evals=None, Optional[int] workers=mp.cpu_count(), Optional[Archive] archive=None, Optional[Dict] opt_params={}, Optional[bool] use_stats=False)
Performs parallel optimization to minimize the fitness function with a focus on quality-diversity.
The function initializes an archive that stores optimal inputs and their fitness values, organizes the records into defined niches, and carries out optimization using parallel processing. qd_fitness Callable fitness function that takes an input array and returns a tuple containing a scalar objective value and an array of descriptor values. bounds Bounds object defining the lower and upper bounds of the search space. qd_bounds Bounds object defining the lower and upper bounds for the quality-diversity archive. niche_num Optional; The number of niches to partition the archive. Defaultis10000. samples_per_niche: Optional; The number of samples to initialize in each niche.Defaultis20. max_evals: Optional; The maximum number of function evaluations. If not provided, the default is workers * 50000. workers Optional; The number of parallel processes to use. Default is the number of CPU cores available. archive Optional; An existing archive object to initialize the optimization process. If not provided, a new archive is created. opt_params Optional; A dictionary of parameters used by the optimization function. Default is an empty dictionary. use_stats Optional; A flag to determine whether to track statistical properties within the archive. Default is False. Archive An archive object containing the optimized results, including fitness values and descriptors.
References fcmaes.diversifier.minimize_parallel_.
fcmaes.diversifier.apply_advretry(Callable[[ArrayLike], float] fitness, Callable[[ArrayLike], Tuple[float, np.ndarray]] qd_fitness, Bounds bounds, Archive archive, Optional[Optimizer] optimizer=None, Optional[int] num_retries=1000, Optional[int] workers=mp.cpu_count(), Optional[float] max_eval_fac=5.0, Optional[np.ndarray] xs=None, Optional[np.ndarray] ys=None, Callable[[ArrayLike], ArrayLike] x_conv=None)
Applies an advanced retry mechanism to optimize solutions for a given fitness function and update an archive with optimized results.
This function manages an iterative process where previously computed solutions from an archive are refined and optimized using a specified optimizer. Advanced retry logic is utilized to ensure the process effectively minimizes the given fitness function within the defined bounds and constraints. fitness Callable that evaluates the fitness of a solution. Must return a floating-point fitness score for a given input. qd_fitness Callable that evaluates the quality-diversity of a solution. Returns a tuple where the first item is the fitness value (float) and the second item is a feature descriptor (e.g., NumPy array). bounds Boundary constraints for the optimization process. archive Archive object that stores and manages solutions. optimizer Optional optimizer to be used for the minimization process. If none, defaults to a DE-CMA optimizer with 1500 iterations. num_retries Optional integer setting the number of retries allowed in advanced retry logic. Defaults to 1000. workers Optional integer specifying the number of workers for parallelization. Defaults to the number of CPUs available. max_eval_fac Optional floating-point factor setting the maximum allowed fitness function evaluations per retry. Defaults to 5.0. xs Optional NumPy array containing a set of previously obtained solutions. If none, solutions are derived from the archive's current entries. ys Optional NumPy array containing fitness values corresponding to xs. If none, fitness values are derived from the archive's entries. x_conv Optional callable to transform or convert solutions (xs) before evaluating their quality-diversity fitness. If none, no transformation is applied.
fcmaes.diversifier.minimize_parallel_(archive, fitness, bounds, workers, opt_params, max_evals)
Minimizes a fitness function in parallel using multiple workers.
This function utilizes multiprocessing to divide the workload of minimizing a fitness function across several worker processes. Each worker operates independently using its own random number generator, and the results are combined to find the minimum value. archive Object or structure used to store and manage state or intermediate results during the optimization process. Details of its structure or behavior depend on the implementation. fitness Callable that evaluates the fitness or cost function to be minimized. Accepts input variables and returns a numerical value representing the cost/fitness. bounds Defines the boundaries within which the optimization process is allowed to search. Typically, this can be a list of tuples specifying the lower and upper bounds for each dimension. workers Integer specifying the number of parallel workers (processes) to execute the fitness function evaluation and optimization tasks. opt_params Parameters or configuration values required for the optimization method. Includes details specific to the optimization algorithm being employed. max_evals Integer representing the maximum number of fitness function evaluations allowed across all worker processes in total.
Referenced by fcmaes.diversifier.minimize.
fcmaes.diversifier.run_minimize_(archive, fitness, bounds, rg, opt_params, p, workers, evals, max_evals)
Executes the optimization processes involving MAP-Elites or solvers in a sequential or multiple configuration depending on the provided optimization parameters.
The method adapts to the given opt_params, evaluating various solvers until the maximum number of allowed evaluations (max_evals) is reached. archive Archive object used for storing solutions and managing population niches. fitness A callable fitness function used to evaluate solutions. bounds Boundary constraints associated with the problem. rg Random generator for deterministic random processes. opt_params Optimization parameters, which can be in the form of a dictionary, list, tuple, or NumPy array. p Integer indicating the number of processing resources available. workers Integer specifying the number of worker threads or processes allocated for solver execution. evals A shared counter object tracking the current total number of evaluations performed. max_evals Maximum allowed number of evaluations over the optimization processes.
References fcmaes.diversifier.minimize_, fcmaes.diversifier.run_map_elites_.
fcmaes.diversifier.run_map_elites_(archive, fitness, bounds, rg, evals, max_evals, opt_params={})
Executes the MAP-Elites algorithm for a given archive and fitness function.
The function iteratively generates a population of individuals, applies variation operators on them, evaluates their fitness, and updates the archive with the newly generated individuals. It can utilize either simulated binary crossover (SBX) or isolation distribution crossover (ISO/DD) depending on the specified optimization parameters. Additionally, the function includes boundaries for the search space and adjusts the archive to maintain its capacity. archive The data structure representing the archive of solutions. fitness The fitness function to evaluate each solution. bounds The search space bounds containing lower (lb) and upper (ub) limits for variables. rg Random number generator for stochastic operations. evals Object to track the number of evaluations performed. max_evals Maximum number of evaluations allowed for the algorithm. opt_params (dict, optional): A dictionary of optional parameters for optimization. Includes popsize (int): Population size for the algorithm (default: 32). use_sbx (bool): Whether to use simulated binary crossover (default: True). dis_c (float): Distribution index for simulated binary crossover (SBX) (default: 20). dis_m (float): Distribution index for mutation (default: 20). iso_sigma (float): Standard deviation for isotropic distribution (default: 0.01). line_sigma (float): Standard deviation for line distribution (default: 0.2).
Referenced by fcmaes.diversifier.run_minimize_.
fcmaes.diversifier.minimize_(archive, fitness, bounds, rg, evals, max_evals, opt_params, x0=None)
Minimizes a given objective function using an evolutionary algorithm or the B.I.T.E.
solver. The function determines the solver type based on the provided optimization parameters and runs the optimization process accordingly. It continuously updates an archive of candidate solutions and evaluates their fitness while adhering to the specified evaluation and iteration limits. A stopping condition is also applied based on lack of improvement. archive Archive object for storing solution candidates and their respective fitness evaluations. fitness Callable representing the fitness function or objective function to be minimized. bounds Bounds or constraints for the solution search space. rg Random number generator to ensure reproducibility. evals A mutable object, typically an integer, tracking the number of evaluations performed. max_evals Integer specifying the maximum number of fitness evaluations to allow. opt_params Dictionary containing optimization parameters, such as solver type and stopping criteria. x0 Optional initial guess or starting point for the optimization process. The best found solution, represented as a real-valued array, that optimizes the provided fitness function.
References fcmaes.diversifier.get_solver_, fcmaes.diversifier.run_bite_.
Referenced by fcmaes.diversifier.run_minimize_.
fcmaes.diversifier.run_bite_(archive, fitness, bounds, rg, evals, max_evals, opt_params, x0=None)
Runs the BiteOpt algorithm to optimize a given fitness function.
The function utilizes the BiteOpt implementation from bitecpp to minimize the provided fitness function over the given bounds and constraints. It supports dynamic updates to the solution archive and stops execution based on a defined maximum evaluation limit or optimization parameters. archive An archive to keep track of the solution space explored during the optimization process. fitness A callable that takes an input, evaluates it, and returns a fitness value. bounds The variable bounds for the optimization problem. rg A random generator instance to ensure reproducibility in the optimization process. evals An object containing a mutable integer used to track the number of evaluations performed. max_evals An integer defining the maximum number of evaluations before the optimization halts. opt_params A dictionary containing optimization parameters such as 'max_evals' and 'stall_criterion'. x0 Optional starting point for the optimization. Defaults to None. The optimized solution vector obtained from BiteOpt.
Referenced by fcmaes.diversifier.minimize_.
fcmaes.diversifier.get_solver_(bounds, opt_params, rg, x0=None)
Selects and initializes the appropriate optimization solver based on the specified parameters.
The solver is chosen from a set of predefined options, and it is configured with the given dimensions, bounds, mean, population size, and other solver-specific parameters. bounds Object representing the bounds for the optimization problem. It provides attributes like lower bounds (lb) and upper bounds (ub). opt_params Dictionary containing optional solver parameters, such as: 'popsize': Population size 'sigma': Step size 'mean': Initial mean position 'solver': Name of the solver to use, e.g., 'CMA', 'CMA_CPP', etc. rg Random number generator for initializing values within the specified bounds or for stochastic components of the solver. x0 Optional starting position for the optimization. Overrides the mean parameter if provided. The initialized optimization solver object if the specified solver name is valid. Returns None if an invalid solver name is provided.
Referenced by fcmaes.diversifier.minimize_.