examples::benchmark_gtop_pygmo
examples::benchmark_gtop_pygmo.stdout
examples::benchmark_gtop_pygmo.format
Referenced by examples.benchmark_gtop_pygmo._test_archipelago.
examples::benchmark_gtop_pygmo.level
examples.benchmark_gtop_pygmo.de_cma_pyg(max_evaluations=50000, popsize=31, stop_fitness=-np.inf, de_max_evals=None, cma_max_evals=None)
Sequence de1220 -> cmaes pagmo.
Referenced by examples.benchmark_gtop_pygmo.test_coordinated_retry.
examples.benchmark_gtop_pygmo.pyg_de_cma(max_evaluations=50000, popsize=31, stop_fitness=-np.inf, de_max_evals=None, cma_max_evals=None)
Sequence de1220 -> cmaes c++.
examples.benchmark_gtop_pygmo.de_pyg_cma(max_evaluations=50000, popsize=31, stop_fitness=-np.inf, de_max_evals=None, cma_max_evals=None)
Sequence de c++ -> cmaes pagmo.
examples.benchmark_gtop_pygmo._test_optimizer(opt, problem, num_retries=10000, num=1, value_limit=100.0, stop_val=-1E99, log=logger())
Referenced by examples.benchmark_gtop_pygmo.test_coordinated_retry.
examples.benchmark_gtop_pygmo._test_archipelago(algo, problem, num=10000, stop_val=-1E99, log=logger())
References examples.benchmark_gtop_pygmo.format.
Referenced by examples.benchmark_gtop_pygmo.test_archipelago.
examples.benchmark_gtop_pygmo.test_archipelago()
References examples.benchmark_gtop_pygmo._test_archipelago.
examples.benchmark_gtop_pygmo.test_coordinated_retry()
References examples.benchmark_gtop_pygmo._test_optimizer, examples.benchmark_gtop_pygmo.de_cma_pyg, examples.benchmark_gtop_pygmo.test_coordinated_retry.
Referenced by examples.benchmark_gtop_pygmo.test_coordinated_retry.