examples::damp
examples::damp.stdout
examples::damp.format
examples::damp.level
float examples::damp.max_alpha
int examples::damp.max_time
examples::damp.integrateDamp_C
Referenced by examples.damp.integrate_C.
examples::damp.argtypes
examples::damp.restype
examples::damp.freemem
Referenced by examples.damp.integrate_C.
int examples::damp.dim
examples.damp.spring(t, y)
examples.damp.integrator()
examples.damp.integrate(I, t)
examples.damp.integrate_C(y, dt, alpha, step)
References examples.damp.freemem, examples.damp.integrateDamp_C.
Referenced by examples.damp.fitness.__call__.
examples.damp.parallel_retry(dim, opt=De_cpp(20000))
examples.damp.plot3d(ys, name, xlabel='', ylabel='', zlabel='')
Referenced by examples.damp.plot_archive.
examples.damp.plot_archive(problem, archive=None)
References examples.damp.plot3d.
Referenced by examples.damp.optimize_qd.
examples.damp.optimize_qd(dim)
References examples.damp.plot_archive.