examples::prophet_opt
examples::prophet_opt.logger
examples::prophet_opt.null_handler
examples.prophet_opt.load_data(symbol='BTC-USD', start_date='2013-01-01', end_date='2024-10-30')
Referenced by examples.prophet_opt.btc_strategy, examples.prophet_opt.optimize_btc, examples.prophet_opt.optimize_btc_ask_tell, examples.prophet_opt.show_good_result.
examples.prophet_opt.btc_strategy()
References examples.prophet_opt.load_data, examples.prophet_opt.plot_df.
examples.prophet_opt.plot_df(df)
Referenced by examples.prophet_opt.btc_show_params, examples.prophet_opt.btc_strategy.
examples.prophet_opt.btc_eval_params(df, changepoint_prior_scale, period, fourier_order, seasonality_mode)
Referenced by examples.prophet_opt.btc_show_params, examples.prophet_opt.fitness.
examples.prophet_opt.btc_show_params(df, changepoint_prior_scale, period, fourier_order, seasonality_mode)
References examples.prophet_opt.btc_eval_params, examples.prophet_opt.plot_df.
Referenced by examples.prophet_opt.btc_show_x.
examples.prophet_opt.convert_x(x)
Referenced by examples.prophet_opt.btc_show_x, examples.prophet_opt.fitness.
examples.prophet_opt.btc_show_x(df, x)
References examples.prophet_opt.btc_show_params, examples.prophet_opt.convert_x.
Referenced by examples.prophet_opt.optimize_btc, examples.prophet_opt.optimize_btc_ask_tell, examples.prophet_opt.show_good_result.
examples.prophet_opt.fitness(df, x)
References examples.prophet_opt.btc_eval_params, examples.prophet_opt.convert_x.
Referenced by examples.prophet_opt.show_good_result.
examples.prophet_opt.optimize_btc()
References examples.prophet_opt.btc_show_x, examples.prophet_opt.load_data.
examples.prophet_opt.optimize_btc_ask_tell()
References examples.prophet_opt.btc_show_x, examples.prophet_opt.load_data.
examples.prophet_opt.show_good_result()
References examples.prophet_opt.btc_show_x, examples.prophet_opt.fitness, examples.prophet_opt.load_data, examples.prophet_opt.show_good_result.
Referenced by examples.prophet_opt.show_good_result.