quant.py
examples::quant.backend
examples::quant.stdout
examples::quant.format
examples::quant.level
int examples::quant.NUM_SHOTS
list examples::quant.fits
examples.quant.get_var_form(params)
Referenced by examples.quant.objective_function.
examples.quant.get_probability_distribution(counts)
Referenced by examples.quant.objective_function.
examples.quant.random_target_distr()
examples.quant.objective_function(params, target_distr)
References examples.quant.get_probability_distribution, examples.quant.get_var_form.
Referenced by examples.quant.Fitness.__call__.
examples.quant.opt_differential_evolution_loop(fits)
examples.quant.opt_cmaes_loop(fits)
examples.quant.opt_biteopt_loop(fits)
examples.quant.opt_COBYLA_evolution_loop(fits)
examples.quant.find_COBYLA_weakness()