quantumcomm.py
quantumcomm.stdout
quantumcomm.format
Referenced by quantumcomm.constellation_udp.fitness, quantumcomm.constellation_udp.plot.
quantumcomm.level
quantumcomm.udp
int quantumcomm.nobj
int quantumcomm.ncon
int quantumcomm.dim
quantumcomm.ref_point
quantumcomm.ubs
quantumcomm.bounds
quantumcomm.max_evals
quantumcomm.manager
quantumcomm.ys
quantumcomm.ys0
quantumcomm.xs
quantumcomm.min_ys
int quantumcomm.count
quantumcomm.mutex
quantumcomm.n
int quantumcomm.max_hv
int quantumcomm.evals
quantumcomm.pid
quantumcomm.xs_out
quantumcomm.ys_out
quantumcomm.get_mothership_satellites()
Construct array of mothership orbital elements (the TLEs of actual Earth-orbiting satellites below are used as a proxy for plausible orbital dynamics around a habitable planet)
Referenced by quantumcomm.constellation_udp.compute_orbit_motherships.
quantumcomm.line_of_sight(r1, r2)
Given two position vectors returns the distance of the line of sight to the origin.
r1 (numpy array): first point r2 (numpy array): second point
Referenced by quantumcomm.get_adjmatrix.
quantumcomm.zenith_angle(src, dst)
Computes the cosine of the zenith angle (theta_z) of the LOS between source and destination node.
src (numpy array, N_r x 3): rover x, y, z positions dst (numpy array, N_s x 3): mothership x, y, z positions float cosine of the zenith angle
Referenced by quantumcomm.get_adjmatrix.
quantumcomm.qkd_metric(idx, src, dst, cos_theta_z, eta, eps_z, n_rovers)
Computes the edge weight according to QKD probabilities.
idx index of node in the graph src (numpy array, 1x3): position of source node dst (numpy array, 1x3): position of destination node cos_theta_z cosine of the zenith angle of qkd link eta satellite quality indicator for corresponding constellation float edge weight float communications link distance between src and dst
Referenced by quantumcomm.get_adjmatrix.
quantumcomm.get_adjmatrix(pos, ep_idx, eta, num_w1_sats, LOS, N, eps_z, n_rovers)
References quantumcomm.line_of_sight, quantumcomm.qkd_metric, quantumcomm.zenith_angle.
Referenced by quantumcomm.constellation_udp.build_graph.
quantumcomm.construct_rover_pos(lambda0, phi0, n_rovers, jds, R_p, w_p)
Computes the position of the rovers at time t based on the initial latitude and longitude.
lambda0 (float, N_r x 1): initial latitudes of the rovers phi0 (float, N_r x 1): initial longitudes of the rovers float, n_rovers x n_epochs x 3: rover x, y, z positions
Referenced by quantumcomm.constellation_udp.fitness, quantumcomm.constellation_udp.plot.
quantumcomm.combine_scores(points)
Function for aggregating single solutions into one score using hypervolume indicator.
quantumcomm.fitness(x)
Referenced by quantumcomm.qd_fun, quantumcomm.so_par.
quantumcomm.select_valid(xs, ys)
quantumcomm.read_solution(fname)
Referenced by quantumcomm.get_arch, quantumcomm.pymoo_par.
quantumcomm.mo_par()
Referenced by quantumcomm.reduce.
quantumcomm.mo_to_qd(y)
Referenced by quantumcomm.qd_fun.
quantumcomm.qd_fun(x)
References quantumcomm.fitness, quantumcomm.mo_to_qd.
quantumcomm.get_arch(qd_bounds, niche_num, samples_per_niche)
References quantumcomm.read_solution.
Referenced by quantumcomm.nd_par.
quantumcomm.nd_par(niche_num=10000)
References quantumcomm.get_arch.
quantumcomm.so_par()
References quantumcomm.fitness.
quantumcomm.pymoo_par()
References quantumcomm.read_solution, quantumcomm.reduce.
quantumcomm.reduce(xs, ys, num, evals=50000, retries=mp.cpu_count())
References fcmaes.retry.minimize, quantumcomm.mo_par.
Referenced by quantumcomm.pymoo_par.