robot.py
examples.robot.create_body(base, b2world_interface, body_shape, body_size, body_friction, body_density, obj_loc)
Referenced by examples.robot.PushReward.__call__.
examples.robot.make_base(table_width, table_length, b2world_interface)
Referenced by examples.robot.PushReward.__call__.
examples.robot.add_obstacles(b2world_interface, obsverts)
examples.robot.run_simulation(world, body, body2, robot, robot2, xvel, yvel, xvel2, yvel2, rtor, rtor2, simulation_steps, simulation_steps2)
Referenced by examples.robot.PushReward.__call__.
examples.robot.main()
References examples.robot.main.
Referenced by examples.robot.main.