testfun.py
fcmaes.testfun._rosen(xs, alpha=1e2)
Computes the Rosenbrock function for the given input.
The Rosenbrock function is a non-convex mathematical function often used as a performance test problem for optimization algorithms. This function takes a list of numerical inputs and evaluates the Rosenbrock polynomial for those inputs. It also supports handling scalars and will return outputs as either a scalar or a list depending on the input. xs A numerical iterable or scalar. The input values for which the Rosenbrock function is to be computed. If the first element of xs is scalar, it is treated as a single value. alpha An optional numerical value. Represents the parameter to scale the quadratic term in the Rosenbrock function. Defaults to 1e2. float or list: The evaluated Rosenbrock function result. If the input is a scalar or a single list, it returns a scalar result. If the input is a list of multiple numerical iterables, it returns a list of computed results for each input iterable.
fcmaes.testfun._rastrigin(x)
Computes the Rastrigin function value for a given input vector.
The Rastrigin function is commonly used as a non-convex test function for optimization algorithms. It is highly multimodal, meaning it has many local minima, which makes it a challenging benchmark for optimization techniques. x A vector of input values on which the Rastrigin function is evaluated. Must be convertible to a NumPy array. float The computed value of the Rastrigin function for the input vector.
Referenced by fcmaes.testfun._rastrigin_mean.
fcmaes.testfun._cigar(x)
Calculates the value of the "cigar" function for a given input array.
The "cigar" function is a common benchmark function in optimization studies. It is designed to simulate an elliptical-shaped function with one dominant dimension. It is used to evaluate optimization algorithms in high-dimensional spaces. x Input array for which the "cigar" function value is to be computed. float Calculated "cigar" function value for the given input array.
fcmaes.testfun._sphere(x)
Calculates the sum of squares of elements in an input array.
This function computes the sum of the squares of each element in the input array. It is typically used in mathematical or optimization contexts. x Input array or iterable whose squared elements will be summated. The sum of the squares of the elements in the input array or iterable.
fcmaes.testfun._elli(x)
Calculates the elliptic function value for the given input.
The elliptic function is commonly used in optimization problems as a benchmark function. It is computed using the input array and a factor that exponentially grows based on the dimension of the input. x Input array representing the variables for which the elliptic function is calculated. float The computed value of the elliptic function for the input.
fcmaes.testfun._modify(x, delta)
Applies a random modification to an array.
This function takes an array as input, and applies a random modification to each of its elements using a Gaussian (normal) distribution scaled by a specified delta factor. x (list or np.ndarray): Input array to be modified. delta Scaling factor for the random noise to be added. list A new list containing the modified elements.
Referenced by fcmaes.testfun._rastrigin_mean.
fcmaes.testfun._rastrigin_mean(x, n)
Computes the mean output of the Rastrigin function over n modifications of input x.
This function applies a slight modification to the input value x before passing it to _rastrigin and accumulates the results to compute the mean. x The initial input value for the Rastrigin function that will be slightly modified for each iteration. n The number of iterations or modifications of input x for computing the average. The mean result of the Rastrigin function after applying it to n modified versions of the input x.
References fcmaes.testfun._modify, fcmaes.testfun._rastrigin.
Referenced by fcmaes.testfun.RastriginMean.__init__.
fcmaes.testfun._eggholder(x)
Calculates the Eggholder function value for a given input.
The Eggholder function is a complex mathematical function often used in optimization problems to test the performance of algorithms due to its multiple local minima. x A list or array-like object with two elements representing the input values for the Eggholder function. float The result of evaluating the Eggholder function for the given input values.